### ISSUE TITLE
value of Brightness is not correct

### ISSUE THREAD

**Issue by Bonze255** [jasonacox/tinytuya#102]
i set the brightness to the value as percentage of 100,  (.set_brightness_percentage(percentage)) 
when i read the brightness(.brightness()) i got 10 ?
the tuya app shows also 100% 

is this a known bug, or is it a special device?

**Comment by jasonacox** [comment]
Hi @Bonze255  - If it is a bug it has not been reported before.  Can you paste a debug trace and your code?

```python
tinytuya.set_debug(True)
```

**Comment by Bonze255** [comment]
> ←[31;1mDEBUG:TinyTuya [1.2.9]
←[0m
←[31;1mDEBUG:status() entry (dev_type is default)←[0m
←[31;1mDEBUG:building payload=b'{"gwId":"bf66554f0553b951f3bdfq","devId":"bf66554f0553b951f3bdfq","uid":"bf66554f0553b951f3bdfq","t":"1643353695"}'←[0m
←[31;1mDEBUG:payload generated=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x88G:`H\x1b\xcc{\xe1\xd0\x84\xfdV.\xcd\xf3\xb2CAoS\xc0C\x7f\x1c\xe3\x8e0\xc1\x83*\xdc\xc0\x95\x88\xb8c\xb5{\xe3\x8b\x12\xe7\x06[X\x812\xf1\xaem\x81\x05\x9b\x8c\xc5\xe0.6\xa3\x04y\xf3_y\x8f.\x08\xb6\xf9\x1c\xca\x8b\xec3\xd86%P4`CAoS\xc0C\x7f\x1c\xe3\x8e0\xc1\x83*\xdc\xc0\xf8H\xd0\xb5z`c\xd2\xf4\x9f\xab\x0e:\x9d\xe6\xbe~\x85e8\xe1\x1e\x9b\xea1UvQ\xfa\x1d\\"\xbd$\xf9\xb9\x00\x00\xaaU'←[0m
←[31;1mDEBUG:received data=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\\\x00\x00\x00\x00\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7\x9a\xb0Q\'\x00\x00\xaaU'←[0m
←[31;1mDEBUG:raw unpacked message = TuyaMessage(seqno=0, cmd=10, retcode=0, payload=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7', crc=2595246375)←[0m
←[31;1mDEBUG:decode payload=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7'←[0m
←[31;1mDEBUG:decrypting=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7'←[0m
←[31;1mDEBUG:decrypted 3.3 payload='{"dps":{"20":true,"21":"colour","22":10,"24":"002903e803e8","26":0}}'←[0m
←[31;1mDEBUG:payload type = <class 'str'>←[0m
←[31;1mDEBUG:decoded results='{"dps":{"20":true,"21":"colour","22":10,"24":"002903e803e8","26":0}}'←[0m
←[31;1mDEBUG:status() received data={'dps': {'20': True, '21': 'colour', '22': 10, '24': '002903e803e8', '26': 0}}←[0m
←[31;1mDEBUG:bulb type set to B←[0m
←[31;1mDEBUG:status() entry (dev_type is default)←[0m
←[31;1mDEBUG:building payload=b'{"gwId":"bf66554f0553b951f3bdfq","devId":"bf66554f0553b951f3bdfq","uid":"bf66554f0553b951f3bdfq","t":"1643353697"}'←[0m
←[31;1mDEBUG:payload generated=b'\x00\x00U\xaa\x00\x00\x00\x01\x00\x00\x00\n\x00\x00\x00\x88G:`H\x1b\xcc{\xe1\xd0\x84\xfdV.\xcd\xf3\xb2CAoS\xc0C\x7f\x1c\xe3\x8e0\xc1\x83*\xdc\xc0\x95\x88\xb8c\xb5{\xe3\x8b\x12\xe7\x06[X\x812\xf1\xaem\x81\x05\x9b\x8c\xc5\xe0.6\xa3\x04y\xf3_y\x8f.\x08\xb6\xf9\x1c\xca\x8b\xec3\xd86%P4`CAoS\xc0C\x7f\x1c\xe3\x8e0\xc1\x83*\xdc\xc0s\x84\xb4\xf7\xcd\xe8?~s\x16\xde\xd2!\xe8\xa9M~\x85e8\xe1\x1e\x9b\xea1UvQ\xfa\x1d\\"\xff\xce\xed\x8f\x00\x00\xaaU'←[0m
←[31;1mDEBUG:received data=b'\x00\x00U\xaa\x00\x00\x00\x01\x00\x00\x00\n\x00\x00\x00\\\x00\x00\x00\x00\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7\xcb~K>\x00\x00\xaaU'←[0m
←[31;1mDEBUG:raw unpacked message = TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7', crc=3414051646)←[0m
←[31;1mDEBUG:decode payload=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7'←[0m
←[31;1mDEBUG:decrypting=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7'←[0m
←[31;1mDEBUG:decrypted 3.3 payload='{"dps":{"20":true,"21":"colour","22":10,"24":"002903e803e8","26":0}}'←[0m
←[31;1mDEBUG:payload type = <class 'str'>←[0m
←[31;1mDEBUG:decoded results='{"dps":{"20":true,"21":"colour","22":10,"24":"002903e803e8","26":0}}'←[0m
←[31;1mDEBUG:status() received data={'dps': {'20': True, '21': 'colour', '22': 10, '24': '002903e803e8', '26': 0}}←[0m
←[31;1mDEBUG:status() entry (dev_type is default)←[0m
←[31;1mDEBUG:building payload=b'{"gwId":"bf66554f0553b951f3bdfq","devId":"bf66554f0553b951f3bdfq","uid":"bf66554f0553b951f3bdfq","t":"1643353697"}'←[0m
←[31;1mDEBUG:payload generated=b'\x00\x00U\xaa\x00\x00\x00\x02\x00\x00\x00\n\x00\x00\x00\x88G:`H\x1b\xcc{\xe1\xd0\x84\xfdV.\xcd\xf3\xb2CAoS\xc0C\x7f\x1c\xe3\x8e0\xc1\x83*\xdc\xc0\x95\x88\xb8c\xb5{\xe3\x8b\x12\xe7\x06[X\x812\xf1\xaem\x81\x05\x9b\x8c\xc5\xe0.6\xa3\x04y\xf3_y\x8f.\x08\xb6\xf9\x1c\xca\x8b\xec3\xd86%P4`CAoS\xc0C\x7f\x1c\xe3\x8e0\xc1\x83*\xdc\xc0s\x84\xb4\xf7\xcd\xe8?~s\x16\xde\xd2!\xe8\xa9M~\x85e8\xe1\x1e\x9b\xea1UvQ\xfa\x1d\\"\xf5\x8f\x80\xd0\x00\x00\xaaU'←[0m
←[31;1mDEBUG:received data=b'\x00\x00U\xaa\x00\x00\x00\x02\x00\x00\x00\n\x00\x00\x00\\\x00\x00\x00\x00\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc79,e\x15\x00\x00\xaaU'←[0m
←[31;1mDEBUG:raw unpacked message = TuyaMessage(seqno=2, cmd=10, retcode=0, payload=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7', crc=959210773)←[0m
←[31;1mDEBUG:decode payload=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7'←[0m
←[31;1mDEBUG:decrypting=b'\xaa\xf8C\x14\xfc^g\x16\x9c\xec6\t\xc8/ d\xfe!f8e\xa6\xc5\xc5\x8e\x03\x11\x99\x00\xd2a\x02\x92\x07F\tJ7\xe5#\xb8\x05\xb6/z\xb4\xc9\xe1(\x947\x0ep\xee\xeb\xb4w3\xf5"\xd3.\xaa\x95\xb2G~\x0e7\xbf\xcb\xe2\xe4a\x1b\xd9\x13o\x7f\xc7'←[0m
←[31;1mDEBUG:decrypted 3.3 payload='{"dps":{"20":true,"21":"colour","22":10,"24":"002903e803e8","26":0}}'←[0m
←[31;1mDEBUG:payload type = <class 'str'>←[0m
←[31;1mDEBUG:decoded results='{"dps":{"20":true,"21":"colour","22":10,"24":"002903e803e8","26":0}}'←[0m
←[31;1mDEBUG:status() received data={'dps': {'20': True, '21': 'colour', '22': 10, '24': '002903e803e8', '26': 0}}←[0m
{'is_on': True, 'mode': 'colour', 'brightness': 10, 'colour': '002903e803e8'}

`      self.device = tinytuya.BulbDevice('xxx','192.168.178.xx',localkey)
        self.device.set_version(float('3.3'))
        time.sleep(2)
        self.device.detect_available_dps()
        print(self.device.state())`

**Comment by jasonacox** [comment]
Looks like you are using a Windows PC with a command windows shell.  Try this to fix the color formatting symbols:

```
tinytuya.set_debug(True, False)
```
This is the key section:
```json
{'dps': {'20': True, '21': 'colour', '22': 10, '24': '002903e803e8', '26': 0}
```
You are correct the data DPS value for brightness is 22 and that data point shows "10" as the value.   I haven't seen that before.  So I wonder if the devices uses the range 0-10 to represent 0%-100%.  Most devices uses [this](https://github.com/jasonacox/tinytuya#version-33---light-type-rgb).

You could verify that by looking at what Tuya cloud reports as the values for the device with a script like this:

```python
import tinytuya

# Connect to Tuya Cloud
# c = tinytuya.Cloud()  # uses tinytuya.json 
c = tinytuya.Cloud(
        apiRegion="us", 
        apiKey="xxxxxxxxxxxxxxxxxxxx", 
        apiSecret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 
        apiDeviceID="xxxxxxxxxxxxxxxxxxID")

# Display list of devices
devices = c.getdevices()
print("Device List: %r" % devices)

# Select a Device ID to Test
id = "xxxxxxxxxxxxxxxxxxID"

# Display Properties of Device
result = c.getproperties(id)
print("Properties of device:\n", result)
```

**Comment by Bonze255** [comment]
on tuya cloiud service device debugging, it shows me 
![grafik](https://user-images.githubusercontent.com/16838128/151517187-3f75debb-e9f6-42c4-969b-74fb8351d839.png)


and this are the json values , which are possible ..

> <html><body>


switch_led | Boolean | "{true,false}"
-- | -- | --
work_mode | Enum | {   "range": [     "white",     "colour",     "scene",     "music"   ] }
bright_value | Integer | {   "min": 10,   "max": 1000,   "scale": 0,   "step": 1 }
colour_data | Json | {   "h": {     "min": 0,     "scale": 0,     "unit": "",     "max": 360,     "step": 1   },   "s": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "v": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   } }
scene_data | Json | {   "scene_num": {     "min": 1,     "scale": 0,     "max": 8,     "step": 1   },   "scene_units": {     "unit_change_mode": {       "range": [         "static",         "jump",         "gradient"       ]     },     "unit_switch_duration": {       "min": 0,       "scale": 0,       "max": 100,       "step": 1     },     "unit_gradient_duration": {       "min": 0,       "scale": 0,       "max": 100,       "step": 1     },     "bright": {       "min": 0,       "scale": 0,       "max": 1000,       "step": 1     },     "temperature": {       "min": 0,       "scale": 0,       "max": 1000,       "step": 1     },     "h": {       "min": 0,       "scale": 0,       "unit": "",       "max": 360,       "step": 1     },     "s": {       "min": 0,       "scale": 0,       "unit": "",       "max": 1000,       "step": 1     },     "v": {       "min": 0,       "scale": 0,       "unit": "",       "max": 1000,       "step": 1     }   } }
countdown | Integer | {   "min": 0,   "max": 86400,   "scale": 0,   "step": 1 }
music_data | Json | {   "change_mode": {     "range": [       "direct",       "gradient"     ]   },   "bright": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "temperature": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "h": {     "min": 0,     "scale": 0,     "unit": "",     "max": 360,     "step": 1   },   "s": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   },   "v": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   } }
control_data | Json | {   "change_mode": {     "range": [       "direct",       "gradient"     ]   },   "bright": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "temperature": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "h": {     "min": 0,     "scale": 0,     "unit": "",     "max": 360,     "step": 1   },   "s": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   },   "v": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   } }


</body>
</html>

**Comment by Bonze255** [comment]
ok ive testet some, when i use mode colour , then i got brightness  10 and copuld not change anything 
when i use mode 'white' , tehn i could change the brightness, and get the right value back

**Comment by jasonacox** [comment]
Some of the bulbs do not support brightness for color.

I think I missed answering the Issue question: 'value of Brightness is not correct'.  I know this is confusing, but the function `brightness()` only returns the VALUE of the brightness DPS from the device, not the percentage.  Here is the raw function in tinytuya:

```python
    def brightness(self):
        """Return brightness value"""
        return self.status()[self.DPS][self.DPS_INDEX_BRIGHTNESS[self.bulb_type]]
```

I decided not to create a function to return percentages because it seems to vary wildly with the different bulbs and would require a Tuya Cloud API call to get the range.

As to the error.  Restarting a device will cause it to break the connection.  Tinytuya will not auto-reconnect if you are in a loop.  You will need to create some code to reconnect if the device is restarted. 

Does that help?
