### ISSUE TITLE
improvement proposition

### ISSUE THREAD

**Issue by Tixav** [jasonacox/tinytuya#108]
It should be great if we could use a function to get the active_time of a device to check via tinytuya.Cloud the last time a door sensor was been activated

Regards,

Reivax

**Comment by Tixav** [comment]
I answer to myself :active_time is not the good data for this (update_time neither), I do not know where the timestamp of the last change of door sensor is stored :-(

**Comment by jasonacox** [comment]
Thanks @Tixav - I agree, this would be a good feature but I'm not sure if this information is available.  Are you using the cloud functions?  Can you post what you have now?  And please keep us updated if you discover anything.  Thanks for your help!

**Comment by Tixav** [comment]
Hi!

After may tests, it works!

I had this code to __init__.py
`import datetime`

`    #on the tuya website : device management -> Query device log
    #curl --request GET "https://openapi.tuyaeu.com/v1.0/devices/ID/logs?codes=doorcontact_state&end_time=1645520208930&size=2&start_time=1605520208930&type=7"
    #Type: 1 online, 2 offline, 3 device activation, 4 device reset, 5 instructions Issue, 6 firmware upgrade, 7 data point report, 8 device semaphore, 9 device restart, 10 timing information
    def getDeviceLog(self, deviceid=None,duration=7776000000):
        #7776000000 = 3 months in ms
        if deviceid is None:
            return error_json(
                ERR_PARAMS,
                "Missing DeviceID Parameter"
            )
            
        END_T = round(datetime.datetime.utcnow().timestamp() * 1000)
        STA_T = (END_T - duration)
        
        uri = 'devices/%s/logs?codes=doorcontact_state&end_time=%s&size=1&start_time=%s&type=7' % (deviceid,str(END_T),str(STA_T))
        response_dict = self._tuyaplatform(uri)
        
        print("response_dict "+str(len(response_dict['result']['logs'])))

        if not response_dict['success']:
            log.debug(
                    "Error from Tuya Cloud: %r" % response_dict['msg'],
            )
        if len(response_dict['result']['logs'])==0:
            log.debug("Nothing to show")
            return
        
        return(response_dict)`

and for using 

`# Display Status/date of Device change
result = c.getstatus(id)
print("Status of device:\n", result)

# Display Last log of Device since last 5 hours (value in ms)
result = c.getDeviceLog(id,10*3600*1000)

DeviceVal=str(result['result']['logs'][0]['value'])

DeviceTps=str(result['result']['logs'][0]['event_time'])
dt_object = datetime.fromtimestamp(int(DeviceTps)/1000)

#false =close / true=open
print('State=%s and timestamp=%s' % (DeviceVal,dt_object))`

I hope that will help

Tixav.

**Comment by jasonacox** [comment]
Nice!  Thanks for sharing the code.  I am wondering if there is an abstract way to represent this for any device not just the door sensor device.   If so, it would be good to add it to the project.   In any case, your code will help anyone else looking to do the same.
