### ISSUE TITLE
Current status only with an active Internet connection after standby

### ISSUE THREAD

**Issue by corus87** [jasonacox/tinytuya#112]
Hi, 

I've got an Eufy Robovac G10 and I can control it with this lib without problems but when I block the device in my firewall
the status is not updating after the device was in standby and it keeps the last state. 
I can still send commands and the vacuum is working but it would be nice to get the current status without having the vacuum dialing home. 

Status when it was working:
```{'dps': {'2': False, '3': 'forward', '5': 'Nosweep', '15': 'Charging', '102': 'Standard', '103': False, '104': 100, '106': 0, '109': 8, '110': 0, '111': 4, '112': 18802, '113': 18802, '114': 18802, '122': 'Nosweep', '127': 18802, '135': False, '140': '001250000000008'}}```

Status after Standby:
```{'dps': {'2': False, '3': 'forward', '5': 'Nosweep', '15': 'standby', '102': 'Standard', '104': 100, '106': 0, '111': 4, '122': 'Nosweep'}}```

Any chance to update the status without internet connection? Or better, is this a known issue on Tuya devices? 

Thanks in advanced.

**Comment by jasonacox** [comment]
Hi @corus87 - thanks for sharing the info about the Eufy Robovac.  You are right, most of the Tuya devices are designed to "phone home" to update state.  I suspect the firmware is updating the cloud before the local status is able to update.  

You might be able to force the update using the UPDATEDPS command.  It works on some power monitoring Tuya devices:

```python
    print(" > Send DPS Update Request < ")
    payload = d.generate_payload(tinytuya.UPDATEDPS)
    d.send(payload)   
```

**Comment by corus87** [comment]
Hi @jasonacox 
thanks for the tip with updating the DPS. I read a lot about this issue after posting this question here in all kind of Tuya GitHUb repos and I almost tried everything I found but unfortunately none of this worked. 

I have monitored the Eufy a bit after turning it off without blocking the internet and there were send some unknown dps and values, I tried to set them when the Eufy was blocked but this didn't worked too.

The robot is now blocked from the internet for almost 2 days and the status is still updating (Also with closed and logout Eufy app, I read some Tuya devices need the app to be open to update status) so I assume it does work as long as I don't switch the main power button off, and this is something I can live with. 

After all I can say, your library is working great with the Eufy robot, is by far the easiest way to control the Eufy of all the other library/projects I found on GitHub..

Here are the DPS I found on the internet for Eufy Robots, maybe this will help someone else too:

```
2 = pause, bool 

3 = direction:
    left
    right
    forward
    backward (Not working on the G10)

5 = work mode:
    Nosweep
    auto
    SmallRoom
    Edge
    Spot

15 = work status returns:
    Charging
    standby
    Sleeping
    Recharge

101 = go home, bool

102 = clean speed:
    No_suction
    Standard (Not working on the G10)
    Boost_IQ (Not working on the G10)
    Max

103 = find robot status, bool

104 = battery level:
    returns int 0-100

106 = returns error codes: 
    (The G10 returns an int from 0-8 instead of the above string)
    no_error
    Wheel_stuck
    R_brush_stuck
    Crash_bar_stuck
    sensor_dirty
    N_enough_pow
    Stuck_5_min
    Fan_stuck
    S_brush_stuck

131 = Activate Remote control, bool


Example to start cleaning:

d = tinytuya.OutletDevice(device_id, host, local_key)
payload = generate_payload(7, {"5": "auto"})
d.send(payload)

Or to going back home:

payload = {"101": True}
d.send(7, payload)
```

**Comment by jasonacox** [comment]
Awesome!  What was the trick to get it to work?  Are you sending UPDATEDPS or do you just need to have the internet unblocked until it is powered on and then you can block internet and it continues to update?

Thanks for the DPS list!

**Comment by corus87** [comment]
Yes, I just need to have the Eufy unblocked until it's powered on, then I can block the internet connection and I get the current status when calling the status() method, so no need to sending the UPDATEDPS.

It's now working fully offline without the official App and I can managed it through Home-Assistant.
