### ISSUE TITLE
Error from Tuya server: request time is invalid

### ISSUE THREAD

**Issue by Burraby** [jasonacox/tinytuya#124]
![image](https://user-images.githubusercontent.com/70784752/161406992-91ba91bd-9d32-431b-b48b-b1c768ae33d2.png)

**Comment by Burraby** [comment]
Fixed, just needed to sync my clock.

**Comment by DeadSix27** [comment]
Yeah, I figured it out, I changed it to British time.. which is 1hr back or so.. either way I think it has issues with Summer/Winter time.. after the wizard I changed it back to CEST and it seems to work .. still annoying

**Comment by jasonacox** [comment]
I agree on annoying.  Is there anything we could do from the wizard that would help?  I suppose it could loop through all the timezones if it sees a "request time is invalid" error:

Would likely just be here:
 
https://github.com/jasonacox/tinytuya/blob/daacd413bad207e0570195a5b9d6da3c6437cd43/tinytuya/wizard.py#L115-L122
