### ISSUE TITLE
How to control lights?

### ISSUE THREAD

**Issue by Hawk2811** [jasonacox/tinytuya#128]
I'm trying to control lamps with tinytuya but I send the command to turn on lamp and it doesn't turn on

used code

import time
import tinytuya

device = tinytuya.BulbDevice('DEVICE_ID','IP',LOCAL_KEY')
device.set_version(3.3)
data = device.status()
print(data)
device.turn_off(switch=1)

**Comment by jasonacox** [comment]
Hi @Hawk2811 can you paste the output from the script (the `print(data)` part)?

Also, you can try (I assume you knew you were using the turn_off() function) without the ID:

```python
device.turn_on()
```

You can also add debug mode (at the top of your code):

```python
import tinytuya

tinytuya.set_debug(True)
```

**Comment by Hawk2811** [comment]
> Hi @Hawk2811 can you paste the output from the script (the `print(data)` part)?
> 
> Also, you can try (I assume you knew you were using the turn_off() function) without the ID:
> 
> ```python
> device.turn_on()
> ```
> 
> You can also add debug mode (at the top of your code):
> 
> ```python
> import tinytuya
> 
> tinytuya.set_debug(True)
> ```

I already solved it but thanks for the set_debug tip
