### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by fmarzocca** [jasonacox/tinytuya#129]
I am making tests on a Tuya RGB bulb.
I am using either the "cloud" method and the "local" one, but with both methods I am experiencing a delay (2 seconds) from when I send the command to when the light comes on or off. Firing the same command from the SmartLife app it is almost immediate.
How can I improve the responsiveness? What are the pros and cons of the two methods?

Thanks
Fabio

**Comment by jasonacox** [comment]
Hi @fmarzocca - it would be interesting to see if you are getting errors.  You can turn on debut to see if you are getting errors that are causing it to slow down:

```python
tinytuya.set_debug(True)
```
Here is a test script to run through the rainbow.  For me, the color changes as fast as it display the color in the terminal:

```python
import tinytuya
import time

#tinytuya.set_debug(True) # uncomment for debug

d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)  

# Flip through colors of rainbow - set_colour(r, g, b):
print('\nColor Test - Cycle through rainbow')
rainbow = {"red": [255, 0, 0], "orange": [255, 127, 0], "yellow": [255, 200, 0],
           "green": [0, 255, 0], "blue": [0, 0, 255], "indigo": [46, 43, 95],
           "violet": [139, 0, 255]}
for x in range(2):
    for i in rainbow:
        r = rainbow[i][0]
        g = rainbow[i][1]
        b = rainbow[i][2]
        print('    %s (%d,%d,%d)' % (i, r, g, b))
        d.set_colour(r, g, b)
        time.sleep(1)
    print('')

time.sleep(1)
d.set_white()

```

**Comment by fmarzocca** [comment]
Thanks, I'll run the test in debug mode and let you know. In the meantime, what are the pros and cons of cloud mode vs local mode?

**Comment by fmarzocca** [comment]
This is the time to turn ON the lamp (with command `d.turn_on()` ):

```
real	0m1.163s
user	0m0.661s
sys	0m0.080s
```

..and this is the related debug output (I have masked the ID's):

`DEBUG:TinyTuya [1.3.1]

DEBUG:status() entry (dev_type is default)
DEBUG:building payload=b'{"gwId":"xxxxxxxx","devId":"xxxxxxx","uid":"xxxxxx","t":"1651662823"}'
DEBUG:payload generated=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x88i\xf5\x07\xd0\xd9\xc9\xa2+\x04b\xb9\x7f\x8a\xaa\xca"H)\xa7h\xb5Q(]2\xb8\xbc\xc9\x85,\xcc!\xfa\x95TmR\xd3Y\xcd\x11\xdf\'T\xeez\x9f{\xd1S\xc6\x99}\\+\x02\xbb\x132\xb9\xb9\xbf\xb8\xfci\x86\xb43\x94\x18\xb1\xb1\xfa\xe91*\xe0\xb5\xc9nH)\xa7h\xb5Q(]2\xb8\xbc\xc9\x85,\xcc!\xbb\xce\xd1aNv,=\x1ba?Q\x95>\xeeN\xc6I\x8c\xb6\xc0W\x8d\xa6?\xb4\xcb\x1e\x01ANG\xf9\xe4*\x9a\x00\x00\xaaU'
DEBUG:received data=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x9c\x00\x00\x00\x00w\x13\xb8(f(p\x1f\xa0\xc2mi\xe2\x16\xba\xc9g!\x94 Q\xd3sE\xc7\x92z\xfd\xac58\xf78\xcb\x8b\x8b\x85\x10\x9d}\xc9\xe4u\xe44\x10 \xbae\x08\xe25\xf1\xb6i\xdbWNa\x96\x8a\xf5\xef\xc1o\xdc\xc9\xcd\xe0\x89\xc4h\xc0\xff\xb3\xdd\xd5R\xf4\xc7\x1cX\xc8r\xf1M\xf7F \x00\xaf~\x1f\x96V|c*\x9fmI\x98A\x82\xf3lW\xf5i\x07y\xe0\xa2`+\xd2\x91\x94G|\xfe\xfa\xb7R\n\nO\x14X\x00T9\x8f\x8d8\xa5\xd0\xd0\xfe\x9e\x8e>\x86\x0b\xa9.\xf2r\x00\x00\xaaU'
DEBUG:raw unpacked message = TuyaMessage(seqno=0, cmd=10, retcode=0, payload=b'w\x13\xb8(f(p\x1f\xa0\xc2mi\xe2\x16\xba\xc9g!\x94 Q\xd3sE\xc7\x92z\xfd\xac58\xf78\xcb\x8b\x8b\x85\x10\x9d}\xc9\xe4u\xe44\x10 \xbae\x08\xe25\xf1\xb6i\xdbWNa\x96\x8a\xf5\xef\xc1o\xdc\xc9\xcd\xe0\x89\xc4h\xc0\xff\xb3\xdd\xd5R\xf4\xc7\x1cX\xc8r\xf1M\xf7F \x00\xaf~\x1f\x96V|c*\x9fmI\x98A\x82\xf3lW\xf5i\x07y\xe0\xa2`+\xd2\x91\x94G|\xfe\xfa\xb7R\n\nO\x14X\x00T9\x8f\x8d8\xa5\xd0\xd0\xfe\x9e\x8e>\x86\x0b', crc=2838426226)
DEBUG:decode payload=b'w\x13\xb8(f(p\x1f\xa0\xc2mi\xe2\x16\xba\xc9g!\x94 Q\xd3sE\xc7\x92z\xfd\xac58\xf78\xcb\x8b\x8b\x85\x10\x9d}\xc9\xe4u\xe44\x10 \xbae\x08\xe25\xf1\xb6i\xdbWNa\x96\x8a\xf5\xef\xc1o\xdc\xc9\xcd\xe0\x89\xc4h\xc0\xff\xb3\xdd\xd5R\xf4\xc7\x1cX\xc8r\xf1M\xf7F \x00\xaf~\x1f\x96V|c*\x9fmI\x98A\x82\xf3lW\xf5i\x07y\xe0\xa2`+\xd2\x91\x94G|\xfe\xfa\xb7R\n\nO\x14X\x00T9\x8f\x8d8\xa5\xd0\xd0\xfe\x9e\x8e>\x86\x0b'
DEBUG:decrypting=b'w\x13\xb8(f(p\x1f\xa0\xc2mi\xe2\x16\xba\xc9g!\x94 Q\xd3sE\xc7\x92z\xfd\xac58\xf78\xcb\x8b\x8b\x85\x10\x9d}\xc9\xe4u\xe44\x10 \xbae\x08\xe25\xf1\xb6i\xdbWNa\x96\x8a\xf5\xef\xc1o\xdc\xc9\xcd\xe0\x89\xc4h\xc0\xff\xb3\xdd\xd5R\xf4\xc7\x1cX\xc8r\xf1M\xf7F \x00\xaf~\x1f\x96V|c*\x9fmI\x98A\x82\xf3lW\xf5i\x07y\xe0\xa2`+\xd2\x91\x94G|\xfe\xfa\xb7R\n\nO\x14X\x00T9\x8f\x8d8\xa5\xd0\xd0\xfe\x9e\x8e>\x86\x0b'
DEBUG:decrypted 3.3 payload='{"dps":{"20":false,"21":"colour","22":10,"23":0,"24":"008f03a0036e","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}'
DEBUG:payload type = <class 'str'>
DEBUG:decoded results='{"dps":{"20":false,"21":"colour","22":10,"23":0,"24":"008f03a0036e","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}'
DEBUG:status() received data={'dps': {'20': False, '21': 'colour', '22': 10, '23': 0, '24': '008f03a0036e', '25': '04464602007803e803e800000000464602007803e8000a00000000', '26': 0}}
DEBUG:bulb type set to B
DEBUG:building payload=b'{"devId":"xxxxxxx","uid":"xxxxxx","t":"1651662823","dps":{"20":true}}'
DEBUG:payload generated=b'\x00\x00U\xaa\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x873.3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\r\xb3\xdd\xa4\\\n\xd1\r~\x8b9\xe8\x06\xf7-\xde\xd1S\xc6\x99}\\+\x02\xbb\x132\xb9\xb9\xbf\xb8\xfci\x86\xb43\x94\x18\xb1\xb1\xfa\xe91*\xe0\xb5\xc9nH)\xa7h\xb5Q(]2\xb8\xbc\xc9\x85,\xcc!\xbb\xce\xd1aNv,=\x1ba?Q\x95>\xeeN\x81\xa0\x12-iY2\r\x9f\x92\xbc\x1b\xe1>?\xfa\x0f\xc1\xfd\xf5a6G\xb6\x9bS\xad\x14a\xcasc\xefY\xef\xcf\x00\x00\xaaU'
DEBUG:received data=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00K\x00\x00\x00\x003.3\x00\x00\x00\x00\x00\x00h"\x00\x00\x00\x01\xff\x81\x11h_\xf1\x8c\x02\xac\xdal\r{\xd0\x9f\x0f\xb2\x19\x88\xb0\xd9\xe1\xf6\x1f\x109\x97\x7f\xf7\xb2?w4\x12P\x1f\xae}eZ\xffK+-\xf5\xee\xc8\x89\xc2E\xdaf\x00\x00\xaaU'
DEBUG:raw unpacked message = TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00h"\x00\x00\x00\x01\xff\x81\x11h_\xf1\x8c\x02\xac\xdal\r{\xd0\x9f\x0f\xb2\x19\x88\xb0\xd9\xe1\xf6\x1f\x109\x97\x7f\xf7\xb2?w4\x12P\x1f\xae}eZ\xffK+-\xf5\xee\xc8\x89', crc=3259357798)
DEBUG:decode payload=b'3.3\x00\x00\x00\x00\x00\x00h"\x00\x00\x00\x01\xff\x81\x11h_\xf1\x8c\x02\xac\xdal\r{\xd0\x9f\x0f\xb2\x19\x88\xb0\xd9\xe1\xf6\x1f\x109\x97\x7f\xf7\xb2?w4\x12P\x1f\xae}eZ\xffK+-\xf5\xee\xc8\x89'
DEBUG:removing 3.3=b'\xff\x81\x11h_\xf1\x8c\x02\xac\xdal\r{\xd0\x9f\x0f\xb2\x19\x88\xb0\xd9\xe1\xf6\x1f\x109\x97\x7f\xf7\xb2?w4\x12P\x1f\xae}eZ\xffK+-\xf5\xee\xc8\x89'
DEBUG:decrypting=b'\xff\x81\x11h_\xf1\x8c\x02\xac\xdal\r{\xd0\x9f\x0f\xb2\x19\x88\xb0\xd9\xe1\xf6\x1f\x109\x97\x7f\xf7\xb2?w4\x12P\x1f\xae}eZ\xffK+-\xf5\xee\xc8\x89'
DEBUG:decrypted 3.3 payload='{"dps":{"20":true},"t":1651662822}'
DEBUG:payload type = <class 'str'>
DEBUG:decoded results='{"dps":{"20":true},"t":1651662822}'
DEBUG:set_status received data={'dps': {'20': True}, 't': 1651662822}
`

**Comment by jasonacox** [comment]
Hi @fmarzocca - I don't see any errors or other concerns in your logs.  I believe the time is expect for a `d.turn_on()` command.  Here is why:

When you run the script it must first connect to the device (TCP) before it sends the command. I have seen Tuya devices take a considerable amount of time to do this (>1s).  Once connected, sending commands are fast.

When you launch the Tuya app (Smart Life), it first connects to all the devices and pulls status to display in the UI.  If you notice the amount of time it takes to launch the app you will see it is >1s too.  Now, the app does not disconnect from the devices so that when you go issue a command, it sends the payload immediately.

You can simulate the app method by doing this in code:

```python
import tinytuya

print('\nConnecting')
d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)
data = d.status()

input("Press enter to turn on")
print('    Turn on light')
d.turn_on()

input("Press enter to turn off")
print('    Turn off light')
d.turn_off()

input("Press enter to turn on")
print('    Turn on light')
d.turn_on()

```

**Comment by fmarzocca** [comment]
Hi Jason,

thank you very much for your very detailed comment. You're right, the delay is due to connecting to Tuya. I an using your library in a Python app, which I call from NodeRed as it is part of an automation, so I am afraid I have to live with this small delay.

BTW: I thought that using the "local" mode it would have been faster. But it isn't. What are the differences between "local" and "cloud" mode? Is local mode always conecting the cloud?

**Comment by jasonacox** [comment]
Hi Fabio!  When the Tuya device boots, its default action is to connect to the cloud.  It keeps a TCP connection open to the cloud waiting for instructions while also updating the cloud with any state change (e.g. on/off).  It also opens up TCP port 6668 on the local network and starts sending out local UDP discovery packets on ports 6666 or 6667.  The local communication is to allow the Smart Life app to discover and control devices locally as well as via the cloud (of course, if you are off of your network with your smartphone, it will use the cloud).  TinyTuya basically uses that local communication to control the devices like the app would.  

Tuya devices are running a fairly lightweight web service.  On most of them, they do not support multi-threading so it can only handle one request at a time.  The SoC that most of them use is similar to the ESP8266 which is a very capable chip, but generally not incredibly fast at managing the TCP stack and web services required for the IoT functions.

For your situation, you could create a python based proxy or service that stays connected to all the devices and listens (or watches) for a signal from NodeRed when an action is requested.  That would eliminate the delay.

**Comment by fmarzocca** [comment]
The idea of a proxy (or service) is great.
Thank you very much for your support and keep up the great work!

**Comment by fmarzocca** [comment]
Thanks, I'll run the test in debug mode and let you know. In the meantime,
what are the pros and cons of cloud mode vs local mode?
