### ISSUE TITLE
Additional Data Points when scanning for data points for Wipro 16Amp Smart plug

### ISSUE THREAD

**Issue by manj9501** [jasonacox/tinytuya#132]
Hi @jasonacox 

Great work, this library!

So I'm based in India and I recently purchased [this](https://www.amazon.in/gp/product/B08HN9Q2SZ/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&th=1) particular 16 Amp Smart Plug, which is based on Tuya protocol version 3.3. I'm using it with Smart Life app and it's working without any hiccups.

Now when I poll for local devices using the `scan` command with tiny tuya, the following status is returned:
`Status: {'1': False, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2295, '21': 1, '22': 552, '23': 35482, '24': 18486, '25': 1850, '26': 0, '38': 'memory', '39': True, '40': 'on', '41': False, '42': '', '43': '', '44': ''}`

As you can see, we get a few additional Data Points which aren't listed in the readme for the library. 
If we click on the 'setting' option in the app after setting up the device, as shown in the following picture,

![Screenshot_20220519-204359_Smart Life](https://user-images.githubusercontent.com/36984979/169333941-e74a3d43-7257-436e-9c9e-233f2e6d345b.jpg) 

we land on page in the Smart Life app:
![Screenshot_20220519-204103_Smart Life](https://user-images.githubusercontent.com/36984979/169333924-a501fe21-bbc3-48c3-a8ae-59624838c95f.jpg)

Now, I've already mapped the extra Data Points(in red) to their respective settings as can be seen in the second image above.

Here's a summary:

| DP ID | Function Point | Type | Range |
| ------------- | ------------- | ------------- | ------------- |
| 38  | Power-on state setting  | enum | off, on, memory |
| 39 | Overcharge Switch  | bool | True/False |
| 40 | Indicator status setting  | enum | none, on, relay, pos |
| 41 | Child Lock  | bool | True/False |
| 42 | UNKNOWN  | NA | NA |
| 43 | UNKNOWN  | NA | NA |
| 44 | UNKNOWN  | NA | NA |

Can you please add this info to the readme? Please let me know if any concerns.

Thanks!

**Comment by jasonacox** [comment]
Hi @manj9501 - Thanks for great information!  Would you want to submit a pull request for the README.md change so you get credit for this contribution?  If not, I can add it.

**Comment by manj9501** [comment]
Submitted PR #133, please take a look.

**Comment by jasonacox** [comment]
Thank you @manj9501 !  Changes merged.

**Comment by manj9501** [comment]
Thanks much @jasonacox !
