### ISSUE TITLE
3.4 protocol is not supported

### ISSUE THREAD

**Issue by koyaya** [jasonacox/tinytuya#148]
Access rejected by 192.168.0.138: Unexpected Payload from Device

**Comment by jasonacox** [comment]
Hi @koyaya - thanks for opening this issue.  You are correct.  TinyTuya does not yet support 3.4 protocol.  I don't have a 3.4 device yet so I'm limited on what I can do.  I'm very happy to accept any PRs to help us expand support to 3.4.

Can you provide a bit more context to help us?

* What device are you using (a link would be helpfpul)?
* Have you find another project that works with your 3.4 device?

Ref: 
- https://github.com/codetheweb/tuyapi/issues/481
- https://github.com/rospogrigio/localtuya/issues/812

**Comment by jasonacox** [comment]
Note on protocol: https://github.com/codetheweb/tuyapi/issues/481#issuecomment-921756711

@harryzz has figured out the protocol and added code to a forked version of tuyapi (node library) to support 3.4.  This could be incorporated into TinyTuya if someone has a device they can use to test.

**Comment by koyaya** [comment]
i didn't find anything that supports 3.4
will be cool if you would be the first one to support it

i can help you

this is the device that i have

US $5.80  42%OFF | Tuya Smart Wifi Motor Switch Module 5V 12V 32V 220V RF
433 Radio Remote Control 4 Channels Inching Relay for Alexa Google Home
https://a.aliexpress.com/_vl0Ak2

**Comment by harryzz** [comment]
Hi,
This gateway from silvercrest (lidl) support v 3.4:
https://paulbanks.org/projects/lidl-zigbee/#overview
available on ebay.de.

regards,
Zahari

**Comment by koyaya** [comment]
what i have isn't a gateway, this is a smart relay, like a switch, only
with 4 channels

**Comment by jasonacox** [comment]
Agree @koyaya , it would be great to get this added.  I will see if I can get one of these devices.

Hi @harryzz , thanks for your help!  Are you aware of any other smart plugs, lights or others that use 3.4?

**Comment by pretoriano80** [comment]
@jasonacox i got this [Mini Smart Switch](https://a.aliexpress.com/_mOLnb2q) and it's a 3,4 device and it's also cheap.
With mine,on  **tinytuya scan** i get this:

 `Access rejected by 192.168.188.50: Unexpected Payload from Device`

**Comment by jasonacox** [comment]
Thanks @pretoriano80 - I'll working on getting a 3.4 device so I can see what we can do to add this support to TinyTuya. It does seem like 3.4 device are still very scarce.

**Comment by orrious** [comment]
Hi folks, I just received 10x superbrightleds.com G4-RGBW3W.  To my surprise they are running 3.4.  Please let me know which branch to pull and what debugs you would like.

**Comment by jasonacox** [comment]
HI @orrious - thanks for the info, can you post the link?  Also, can you try to run scan with the latest version (1.6.4)?  `python -m tinytuya scan`

**Comment by jasonacox** [comment]
Thanks!  Positive sign is that it is broadcasting the Tuya discovery UDP packets.  We need to add the code to handle the 3.4 decryption in the core.py `_decode_payload()` function. 

@harryzz has done the discovery and has working code in Node (JS) https://github.com/codetheweb/tuyapi/issues/481#issuecomment-921756711  (see [code here](https://github.com/harryzz/tuyapi/commit/ef4473b4679c29d07ae504490503b6fa87d3e733)) - we need to convert it to python.

**Comment by orrious** [comment]
Due to not being able to tuya-convert these devices to my own firmware, I've no choice but to run them on an isolated network.  That said, it makes it easy to provide a developer with access to them while implementing version 3.4  I'm happy to provide a RPi or run a container of your choice on that network.

**Comment by manj9501** [comment]
I'm using this [smart bulb](https://www.amazon.in/12-Watt-Enabled-Compatible-Assistant-SSK-SMW-12W-5C/dp/B08BKWMBBJ/ref=sr_1_1_sspa?crid=1R71IXRKWYGAJ&keywords=syska+smart+bulb&qid=1658507006&sprefix=syska+sm%2Caps%2C257&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyNU9PSU40MVJIODZPJmVuY3J5cHRlZElkPUEwMjcxNTc5MjlaSkdITlk1RVUzSSZlbmNyeXB0ZWRBZElkPUEwMDg0MDQ5UjhRUlBHUjY4S1pFJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==) and it's also running version 3.4. I can help with testing, if need be.

Logs:
```
TinyTuya (Tuya device scanner) [1.6.4]

[Loaded devices.json - 3 devices]

Scanning on UDP ports 6666 and 6667 for devices (18 retries)...

First hall light   Product ID = key8u54q9dtru5jw  [Valid payload]:
    Address = 192.168.0.103,  Device ID = bf9cbf4d50f588d20ebwac, Local Key = 7544f9f750819bee,  Version = 3.4, MAC = cc:8c:bf:4e:bb:22
    Access rejected by 192.168.0.103: Unexpected Payload from Device
```

**Comment by jasonacox** [comment]
Thank you, @manj9501 

A few more things could help if anyone has time to explore:

* What information do you see about these 3.4 devices in the iot.tuya.com console?  Specifically any documentation that appears about the 3.4 version.
* Are you able to use the TinyTuya cloud functions to control these 3.4 devices?
* Has there been any official communication from Tuya about 3.4 devices since it seems the adoption of this new protocol is extremely low.  I ask to help understand why they proposed a different protocol. 3.1 to 3.3 was to introduce full encryption.  I'm not able to determine the 3.3 to 3.4 justification. 

I have a 3.4 device on order to use for testing.  @orrious I would like to try to avoid using your network for my disruptive testing but I'll let you know, and will definitely appreciate your help once we have code to test.

Thanks for the help!

**Comment by expertsonline** [comment]
I just ordered some WiFi bulbs and one of them came with Firmware version 1.3.21 which has protocol 3.4 which brought me here.

Cloud function in native Tuya integration can send state change commands but does not receive any state updates.
I also compared the device debugging screen on the iot.tuya.com between a protocol 3.3 and a protocol 3.4 device and all the data is identical ... cant see any difference on the portal between the two devices.

Using harryzz/tuyapi version I can connect to the light and get the data packet with all the values for the relevant dps. However, device.set does not work and times out with an error message : Error! Timeout waiting for status response from device id: xxxxxx

Let me know if there is anything I can do to help push this further.

Thanks!

**Comment by uzlonewolf** [comment]
Although I do not yet have any 3.4 devices myself, I made an attempt at adding support for them.  If people could try my fork at https://github.com/uzlonewolf/tinytuya/tree/v34 and let me know if it works it would be greatly appreciated.

**Comment by jasonacox** [comment]
Thanks to the brilliant work by @uzlonewolf we now have 3.4 device support in TinyTuya.  We have not yet released this to PyPI, but that will come after some additional testing.  

Everyone here, if you can, please test this new code on your 3.4 devices:

```bash
git clone https://github.com/jasonacox/tinytuya.git
cd tinytuya

# Use Wizard to Scan
python3 -m tinytuya wizard

# Use Scanner
cp /path/to/devices.json devices.json
python3 -m tinytuya scan

# Test with your local key
python3
```

```python
import tinytuya

d = tinytuya.OutletDevice('id', '10.0.1.90', 'key')
d.set_version(3.4)

print(" > Fetch Status < ")
data = d.status()
print(data)

print(" > Turn On < ")
d.turn_on()
data = d.status()
print(data)

print(" > Wait 5 sec < ")
time.sleep(5)

print(" > Turn Off< ")
d.turn_off()
data = d.status()
print(data)
```

**Comment by manj9501** [comment]
Upon using `python3 -m tinytuya scan`, I get the following output:
```
TinyTuya (Tuya device scanner) [1.7.0]

[Loaded devices.json - 3 devices]

Scanning on UDP ports 6666 and 6667 for devices (18 retries)...

Second hall light   Product ID = keytg5kq8gvkv9dh  [Valid payload]:
    Address = 192.168.0.102,  Device ID = eb0123456789001234567890, Local Key = 0123456789ABCDEF,  Version = 3.3, MAC = cc:xx:xx:09:xx:71
    Status: {'20': False, '21': 'white', '22': 10, '23': 270, '24': '000003e803e8', '25': '000e0d0000000000000000c80000', '26': 0, '34': True}
Third light   Product ID = keytg5kq8gvkv9dh  [Valid payload]:
    Address = 192.168.0.100,  Device ID = eb0123456789001234567890, Local Key = 0123456789ABCDEF,  Version = 3.3, MAC = xx:1f:xx:ef:xx:77
    Status: {'20': False, '21': 'colour', '22': 10, '23': 270, '24': '003203e8000a', '25': '000e0d0000000000000000c80000', '26': 0, '34': True}
First hall light   Product ID = key8u54q9dtru5jw  [Valid payload]:
    Address = 192.168.0.101,  Device ID = bfce70xxxxxxxxx69tll2, Local Key = 1055xxxxxx6f120d,  Version = 3.4, MAC = xx:8c:xx:4e:xx:22
    Status: {'20': True, '21': 'white', '22': 10, '23': 270, '24': '000003e803e8', '25': '000e0d0000000000000000c80000', '26': 0, '34': True, '41': True}

Scan Complete!  Found 3 devices.

>> Saving device snapshot data to snapshot.json
```

I can successfully see the DPs connected to my v3.4 Smart Bulb (though not sure what DP 41 is).

Now after modifying the script given by @jasonacox for Bulb Devices, I get the following output:
```
$ python3 Tuya.py
 > Fetch Status <
{'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
 > Turn On <
Traceback (most recent call last):
  File "C:\Users\manj9\tinytuya\Tuya.py", line 11, in <module>
    d.turn_on()
  File "C:\Users\manj9\tinytuya\tinytuya\BulbDevice.py", line 257, in turn_on
    self.set_status(True, switch, nowait=nowait)
  File "C:\Users\manj9\tinytuya\tinytuya\core.py", line 1252, in set_status
    payload = self.generate_payload(CONTROL, {switch: on})
  File "C:\Users\manj9\tinytuya\tinytuya\core.py", line 1215, in generate_payload
    return self._generate_message(command_override, payload)
  File "C:\Users\manj9\tinytuya\tinytuya\core.py", line 928, in _generate_message
    payload = self.version_header + payload
AttributeError: 'BulbDevice' object has no attribute 'version_header'
```

Here's the modified script:
```
import tinytuya

d = tinytuya.BulbDevice('bfce70xxxxxxxxxb69tll2', '192.168.0.101', '1055xxxxxx6f120d')
d.set_version(3.4)

print(" > Fetch Status < ")
data = d.status()
print(data)

print(" > Turn On < ")
d.turn_on()
data = d.status()
print(data)

print(" > Wait 5 sec < ")
time.sleep(5)

print(" > Turn Off< ")
d.turn_off()
data = d.status()
print(data)
```

**Comment by uzlonewolf** [comment]
@manj9501 Fixed with #182.  tinytuya/BulbDevice.py needs set_version to call `super(BulbDevice, self).set_version(version)` instead of simply doing `self.version = version`

**Comment by manj9501** [comment]
I can confirm that the modifications made in #182 have solved the previously encountered error whilst running the BulbDevice script.

Thanks for the great work, @uzlonewolf!

**Comment by jasonacox** [comment]
@manj9501 -Thanks for testing and the bug find on the BulbDevice!

And, thanks @uzlonewolf ! Brilliant work!  Also, I love the `version=` to constructor addition!  Old code will still work (as will anything using pytuya) but would allow us to update all the README and example scripts to a more intuitive (and if wanted, self descriptive) way:

```python
d = tinytuya.OutletDevice(
    dev_id='xxxxxxxxxxxxxxxxxxxxxxxx',
    address='x.x.x.x',
    local_key='xxxxxxxxxxxxxxxx',
    version=3.4)

print(d.status())
```

PR #182 merged.

Others - please test if you can and post results.

**Comment by jasonacox** [comment]
TinyTuya v1.7.0 with 3.4 protocol support has been released to PyPI.  Credit to @uzlonewolf !  

```bash
pip install --upgrade tinytuya

python -m tinytuya version
TinyTuya [1.7.0]
```

Thanks everyone for your interest and support.
