### ISSUE TITLE
Ledvance smart plug fetching and pairing issue

### ISSUE THREAD

**Issue by devmet34** [jasonacox/tinytuya#150]
Hello,

I paired Ledvance smart+ wifi plug with its own app on android. Its working ok. I tried tuyapower py. It scans find and outputs all the parameters including plugkey something like "keyj5dhdbjch". When i try to get device info with given parameters, it says no power data. I suppose plugkey is not the actual key?

I reset the device and tried to pair with both smart life and tuya smart app but it fails. During manual pairing with smart life or tuya smart app,  device's led stops blinking but app fails to pair with timeout even though device connects to wifi router. 

Appreciate helps. Thanks

**Comment by jasonacox** [comment]
Hi @devmet34, thanks for opening this issue. Can you also post a link to the specific device in case others see this?

You are correct.  PlugKey (aka Product Key, Product ID) is essentially a device SKU but is not the local security KEY used to encrypt communication.  When you set up a device using the App (e.g. Smart Life or Tuya Smart), a local key is created and the device is paired with the Tuya Cloud.  That key is stored on the device and in the Tuya Cloud.  The instructions to fetch the key is not simple, unfortunately, but if you have a Tuya compatible plug and you follow the steps it does work: https://github.com/jasonacox/tinytuya#setup-wizard---getting-local-keys

However, I'm not sure your device is compatible.  You could still try the instructions to see if the Ledvance app would work. Unfortunately, it is likely not going to work.  A quick search and I see several post in reddit.com about people not getting Ledvance devices to work with the Tuya echo system.  I do wonder what they are doing.

Has anyone else had any luck with these devices?

**Comment by devmet34** [comment]
Hey Jason, thanks for the quick reply. The model name and link given below. I'll try that method and post the result. If it doesnt work, which i too think it wont work, is there any workaround for getting the key from device. It's probably encrypted so cant sniff it. Maybe ledvance support can help? Or is there any other way to get power info like using ifttt, web api, mqtt etc. with given ledvance cloud credentials?

Device model: AC27825
Official link: https://www.ledvance.com/consumer/products/smart-home/smart-home-products-with-wifi-technology/smart-home-components/plug-with-smart-socket-to-control-non-smart-devices-with-wifi-technology--pairable-with-remote-controller-c6482

**Comment by jasonacox** [comment]
Thanks @devmet34 - appreciate the link!

I think you have some good ideas here.  I don't have any of these devices so I don't have a way of testing or helping.  I wish there was a better way to get these KEYs (even for traditional Tuya devices).  Some thoughts I have:

* The local KEY may exist on your Android phone so there may be a path to pick up that file in the phone file system if you have a jail-broken android.  
* You could do some investigation to see if the Ledvance cloud provides API access.  I would search their websites and contact their support to see if they do.  They may even have a way to get the local KEYs similar to Tuya.  I would also ask them if there is a way to use SmartLife App instead and if not, suggest they add that as a feature request. 

Thanks again for opening this and keeping us all updated on your discovery!

**Comment by devmet34** [comment]
Ok got the answer it seems like yes its working :)

**Comment by jasonacox** [comment]
Awesome!  Thanks @devmet34 !  Can you share the method you used to get the keay?

**Comment by jasonacox** [comment]
Thanks @devmet34 !  Great tip.  And just to confirm, you are able to get status and control this Ledvance device with TinyTuya once you had those keys?

**Comment by devmet34** [comment]
Yes, i can get power values with the key.  Cheers
