### ISSUE TITLE
d.status() not working

### ISSUE THREAD

**Issue by TheConfax** [jasonacox/tinytuya#16]
The outlet is  correctly turning on and off, but d.status() is raising a JSONDecodeError

`Traceback (most recent call last):
  File "C:/Users/theco/Desktop/AA.py", line 11, in <module>
    data= d.status()
  File "C:\Users\theco\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya\__init__.py", line 502, in status
    result = json.loads(result)
  File "C:\Users\theco\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\theco\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\theco\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Any help on this?

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
🖕🖕🤬😩😩😊😊🤧🎃😶😶🙀🙀😉😉😉😲😲😭😶😶😡😡🧐😺😺🤒🤒😡😡😶😶🥵🤪🤪🤪🥺🥺😮😮😴😴🤧🤧👹👹👹👿😈👏🏻👏🏻👏🏻🙌🏻😻😻😼😼😼🙀🙀🙀🤟🙌🏻🙌🏻😻☠️☠️👹👺👺😷😷😷🤧🤧🤧🤧🖕🖕🤬😩😩😊😊🤧🎃😶😶🙀🙀😉😉😉😲😲😭😶😶😡😡🧐😺😺🤒🤒😡😡😶😶🥵🤪🤪🤪🥺🥺😮😮😴😴🤧🤧👹👹👹👿😈👏🏻👏🏻👏🏻🙌🏻😻😻😼😼😼🙀🙀🙀🤟🙌🏻🙌🏻😻☠️☠️👹👺👺😷😷😷🤧🤧🤧🤧🖕🖕🤬😩😩😊😊🤧🎃😶😶🙀🙀😉😉😉😲😲😭😶😶😡😡🧐😺😺🤒🤒😡😡😶😶🥵🤪🤪🤪🥺🥺😮😮😴😴🤧🤧👹👹👹👿😈👏🏻👏🏻👏🏻🙌🏻😻😻😼😼😼🙀🙀🙀🤟🙌🏻🙌🏻😻☠️☠️👹👺👺😷😷😷🤧🤧🤧🤧🖕🖕🤬😩😩😊😊🤧🎃😶😶🙀🙀😉😉😉😲😲😭😶😶😡😡🧐😺😺🤒🤒😡😡😶😶🥵🤪🤪🤪🥺🥺😮😮😴😴🤧🤧👹👹👹👿😈👏🏻👏🏻👏🏻🙌🏻😻😻😼😼😼🙀🙀🙀🤟🙌🏻🙌🏻😻☠️☠️👹👺👺😷😷😷🤧🤧🤧🤧🖕🖕🤬😩😩😊😊🤧🎃😶😶🙀🙀😉😉😉😲😲😭😶😶😡😡🧐😺😺🤒🤒😡😡😶😶🥵🤪🤪🤪🥺🥺😮😮😴😴🤧🤧👹👹👹👿😈👏🏻👏🏻👏🏻🙌🏻😻😻😼😼😼🙀🙀🙀🤟🙌🏻🙌🏻😻☠️☠️👹👺👺😷😷😷🤧🤧🤧🤧

**Comment by jasonacox** [comment]
Can you paste the code you are using (AA.py)?   Based on the error trace, it is getting a null response (None).

Also are you seeing the outlet when you do a scan?: 
```
python -m tinytuya scan
```

**Comment by TheConfax** [comment]
The code is just a simple test:

`import tinytuya
LOC_KEY = "local key string"
DEV_ID = "device id string"
IP_ADDR = "192.168.1.9"

d = tinytuya.OutletDevice(DEV_ID,IP_ADDR,LOC_KEY)
d.set_version(3.3)
d.status()
`

d.turn_off() // d.turn_on() are working regularly.

This is the result of scan in Windows:
![Scan](https://user-images.githubusercontent.com/33484856/103725599-3de65400-4fd7-11eb-9c4f-d9022e58e33a.jpg)

**Comment by jasonacox** [comment]
Thanks for the tests!

There seems to be some strange behavior with some devices that have a 22 character IDs.  I don't know if that is your case.   Try adding device22 to the initialization for dev_type:

```python
a = tinytuya.OutletDevice('here_is_my_key', '192.168.1.9', 'secret_key_here', 'device22')
a.set_version(3.3)
data =  a.status()
print(data)
```

Also, in case it helps, I see you are using a Windows command window instead of a powershell terminal.  Tinytuya sends terminal color codes that don't show up in command windows, but you can disable color codes:

```bash
python -m tinytuya scan -nocolor      
``` 

If you can, I would also recommend pulling the local key again and let tinytuya run a scan on the device as well:
```bash
python -m tinytuya wizard -nocolor      
``` 

Finally, if none of that helps, make sure there isn't a firmware update for the device (I have seem some odd tuya behavior on early 3.3 devices).

**Comment by TheConfax** [comment]
The wizard produced the same local key as before, but my device has indeed a 22 character id. By using "device22" the error changed into this:

```
Traceback (most recent call last):
  File "C:\Users\theco\Desktop\SS Off.pyw", line 10, in <module>
    data =  d.status()
  File "C:\Users\theco\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya\__init__.py", line 467, in status
    payload = self.generate_payload(DP_QUERY)
  File "C:\Users\theco\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya\__init__.py", line 410, in generate_payload
    json_data['dps'] = self.dpsUsed
AttributeError: 'OutletDevice' object has no attribute 'dpsUsed'
```

**Comment by jasonacox** [comment]
Ah!  That's encourage result.  I left out a line, try this (notice set_dpsUsed):

```python
a = tinytuya.OutletDevice('here_is_my_key', '192.168.1.9', 'secret_key_here', 'device22')
a.set_version(3.3)
a.set_dpsUsed({"1": None})
data =  a.status()
print(data)
```

**Comment by TheConfax** [comment]
Solved! 🎉🎉
Thank you for your help Jason, I'm really a beginner at Python but maybe you could add remarks to 22 characters id and dps & 22 edits to the main guide, that could have been useful!
