### ISSUE TITLE
Exception when status() receives 28byte payload

### ISSUE THREAD

**Issue by ljw1004** [jasonacox/tinytuya#17]
I got a local key via the wizard, construct an OutletDevice, and invoke status(). Sometimes it works but often it crashes with an exception (below).

I believe there's a bug in the following line. The device is sending me a 28 byte response. This line should test "len(data) <= 28" to catch the 28-byte case, and try again. But it's not catching the 28 byte response, and so isn't retrying. Once I changed this line in the tinytuya library to be "<= 28" rather than "< 28", then my invocations of status() all started working reliably.
```
                # Some devices fail to send full payload in first response
                # Note - some devices respond with len = 28 for error response
                if self.retry and len(data) < 28:  
                    time.sleep(0.1)
                    data = self.socket.recv(1024)  # try again
```

Here is the debug trace from when I invoked status(). (the line numbers are marginally off because I deleted a few python2-compatible lines from my copy of tinytuya.py so it would pass clean in MyPy).
```
DEBUG:tinytuya:status() entry (dev_type is default)
DEBUG:tinytuya:json_payload=b'{"gwId":"10871285d8bfc016260e","devId":"10871285d8bfc016260e","uid":"10871285d8bfc016260e","t":"1610307603"}'
DEBUG:tinytuya:status received data=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x0c\x00\x00\x00\x00x\x93p\x91\x00\x00\xaaU'
DEBUG:tinytuya:result=b''
[2021-01-10 11:40:03.156686] Table lamps: exception - TypeError('ord() expected a character, but string of length 0 found')
Traceback (most recent call last):
  File "./lights.py", line 92, in set_dimmer_loop
    status = device.status()
  File "/Users/ljw/code/bell/tinytuya.py", line 484, in status
    result = cipher.decrypt(result, False)
  File "/Users/ljw/code/bell/tinytuya.py", line 162, in decrypt
    return self._unpad(raw).decode('utf-8')
  File "/Users/ljw/code/bell/tinytuya.py", line 177, in _unpad
    return s[:-ord(s[len(s)-1:])]
TypeError: ord() expected a character, but string of length 0 found
```

**Comment by jasonacox** [comment]
Good find!  The minimum valid payload is 28, but as your example shows, that could be an empty payload.  I'll test to ensure there are no negative side effects and add this to the next release.
