### ISSUE TITLE
Detect_Available_DPS fails on my smart PIR Light

### ISSUE THREAD

**Issue by Stueypoo** [jasonacox/tinytuya#171]
Hi,
The PIR light I have seems to not use any standard DPS values. When I call 'detect_available_dps', I get the following error:
```
File "C:\Users\PS\AppData\Local\Programs\Python\Python310\lib\site-packages\tinytuya\core.py", line 803, in detect_available_dps
    if "dps" in data:
TypeError: argument of type 'NoneType' is not iterable
```
If I modify line 803 in core.py as follows, then the code works fine.
`            if data is not None and "dps" in data:
`

**Comment by jasonacox** [comment]
Great find @Stueypoo - Do you want to submit at PR with this fix to get credit for your contribution?  If not, I'll make the edit.
