### ISSUE TITLE
Version 3.4. Error 904. Unexpected Payload from Device', 'Err': '904', 'Payload': None

### ISSUE THREAD

**Issue by Dn1234567** [jasonacox/tinytuya#178]
Hello,
Wizard pulled succefully the data from Tuya IOT cloud. But at the end ("pool local devices = y") says 
"Scanning local network for Tuya devices (retry 26 times)...
    1 local devices discovered
Polling local devices...
    [Aubess Smart Switch 1-gang] - 192.168.70.2 - No Response
"
"python -m tinytuya scan" says 

"Aubess Smart Switch 1-gang   Product ID = xxxxxxxxxxx [Valid payload]:
    Address = 192.168.70.2,  Device ID = yyyyyyyyyyyyyy, Local Key = zzzzzzz,  **Version = 3.4**, MAC = cc:8c:bf:a4:45:90
    Access rejected by 192.168.70.2: Unexpected Payload from Device"

And tinytuya in debug mode (tinytuya.set_debug(True))

DEBUG:Error decoding received data - read retry 0/5
Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\tinytuya\core.py", line 594, in _send_receive
    msg = self._receive()
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\tinytuya\core.py", line 538, in _receive
    data = self._recv_all(header_len+ret_end_len)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\tinytuya\core.py", line 523, in _recv_all
    raise DecodeError('No data received - connection closed?')
tinytuya.core.DecodeError: No data received - connection closed?

Seems to something wrong due to the Newest version of API 3.4 of device (just a simple switch - Aubess Smart Switch )? 
Thanks in advance!

**Comment by jasonacox** [comment]
Hi @Dn1234567 - thanks for this post.  Tinytuya does not yet support the 3.4 devices.  There are a few others who are reporting 3.4 showing up but they are rare - see this issue: https://github.com/jasonacox/tinytuya/issues/148 - We are looking for help in decoding them. Can you send a link to the device you have?

**Comment by Dn1234567** [comment]
Hi!
https://aliexpress.ru/item/1005003948341679.html?sku_id=12000027538887560

**Comment by uzlonewolf** [comment]
@Dn1234567 can you check out https://github.com/uzlonewolf/tinytuya/tree/v34 and let me know if it works?

**Comment by jasonacox** [comment]
@Dn1234567 thanks to the brilliant work by @uzlonewolf we now have 3.4 device support in TinyTuya.  We have not yet released this to PyPI, but that will come after some additional testing.  If you can, please test this new code on your 3.4 device:

```bash
git clone https://github.com/jasonacox/tinytuya.git
cd tinytuya

# Use Wizard to Scan
python3 -m tinytuya wizard

# Use Scanner
cp /path/to/devices.json devices.json
python3 -m tinytuya scan

# Test with your local key
python3
```

```python
import tinytuya

d = tinytuya.OutletDevice('id', '10.0.1.90', 'key')
d.set_version(3.4)

print(" > Fetch Status < ")
data = d.status()
print(data)

print(" > Turn On < ")
d.turn_on()
data = d.status()
print(data)

print(" > Wait 5 sec < ")
time.sleep(5)

print(" > Turn Off< ")
d.turn_off()
data = d.status()
print(data)
```

**Comment by jasonacox** [comment]
TinyTuya v1.7.0 with 3.4 protocol support has been released to PyPI.  Credit to @uzlonewolf !  

```bash
pip install --upgrade tinytuya

python -m tinytuya version
TinyTuya [1.7.0]
```

@Dn1234567 please test and let us know your results.

Thanks everyone for your interest and support.
