### ISSUE TITLE
Works via Python and Smart Life app to change color. Alexa however loses it ability to change color

### ISSUE THREAD

**Issue by SouDescolado** [jasonacox/tinytuya#180]
Basically the title

I can control it perfectly via python. I can control it perfectly via Smart Life.
However now when I ask 'Alexa, bedroom blue', while it does change the lamp mode to color, it doesnt actually change the color

I THINK it has something to do with the `set_version` command, but I am not entirely sure

Edit: I tried to remove the lamp from smartlife and add it back, to see if it somehow makes it work again, but no dice. Still able to control via python and straight from the Smart Life app, not from Alexa Voice or Alexa App

**Comment by jasonacox** [comment]
Hi @SouDescolado - That sounds like an integration issue between SmartLife and Amazon Alexa.  I'm not sure how TinyTuya could help in this case since it isn't in the loop.  I suggest contacting the Smart Bulb manufacturer and let them know that the Alexa integration isn't working.  In the meantime at least you can use TinyTuya (python) to manage the bulb. :)

**Comment by SouDescolado** [comment]
To be fair, I think I can close the issue. I think it has to deal with the Light bulb brand instead of tuya. It just happened that I only noticed after I used the tinytuya module. I decided to ask in case there were any options that I should try here, but it seems totally an alexa/light bulb thing

**Comment by jasonacox** [comment]
Understood! Thanks for opening the issue and the update.  I can't think of a way that TinyTuya would cause a problem with Alexa. The `set_version()` function is used to let TinyTuya know what firmware protocol version the device is using which is then used to auto-detect the type of SmartBulb it might be, it doesn't send any commands to device that should change the behavior.  If you discover anything more, please feel free to re-open or update us here.  Thanks!
