### ISSUE TITLE
Unexpected payload from device

### ISSUE THREAD

**Issue by maxmonz69** [jasonacox/tinytuya#193]
I have 5 USB switch.
The device scan receives correct payload from four of them while for the last one I see "No response".
When I try to get the status from python I get Unexpected payload from device.
The device work perfectly with SmartLife and Amazon Alexa.
Any help please?
Thanks

**Comment by maxmonz69** [comment]
ok solved, nevermind

**Comment by jasonacox** [comment]
Thanks @maxmonz69 - closing this.
