### ISSUE TITLE
Outlets (pow monitor), no response when 0

### ISSUE THREAD

**Issue by gabrielklein** [jasonacox/tinytuya#197]
Hi, I don't know if this issue is related to tinytuya or tuya.

I have a few power plugs monitor.

When the devices are under load, I receive current at dps=18, power at dps=19, voltage as dps=20.

With UpdateDPS, I receive {'dps': {'18': 2133, '19': 4742, '20': 2396}, 't': 1665952232}

When the devices are not under load (example my coffee machine is off.

With DPQuery, I receive: 
{'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2401, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}

But with UpdateDPS, I receive  **{'dps': {'20': 2396}, 't': 1665952019}**

My issue is that I cannot notify my system that not current or power is used.

**Comment by jasonacox** [comment]
Hi @gabrielklein  - UpdateDPS is only for certain plugs that don't update their power data points automatically.  Also, it will only shows the data points that updated.  If you are getting accurate data with a standard query, you should use that.  Alternatively, if your device needs UpdateDPS, you can send the UpdateDPS command first then poll for status.

```python
import tinytuya

d = tinytuya.OutletDevice('DEVICEID', 'DEVICEIP', 'DEVICEKEY')
d.set_version(3.3)

print(" > Fetch Status < ")
data = d.status()
print(data)

print(" > Wait 5 sec < ")
time.sleep(5)

print(" > Request Update < ")
result = d.updatedps(['18','19','20'])
print(result)

print(" > Fetch Status Again < ")
data2 = d.status()
print(data2)

print("")
print("Before %r" % data)
print("After  %r" % data2)

```

If you stay connected to them, the Tuya devices emit changes in state.   Here is an example loop that gives you state changes over time:

```python
import tinytuya

d = tinytuya.OutletDevice('DEVICEID', 'DEVICEIP', 'DEVICEKEY')
d.set_version(3.3)
d.set_socketPersistent(True)

print(" > Send Request for Status < ")
payload = d.generate_payload(tinytuya.DP_QUERY)
d.send(payload)

print(" > Begin Monitor Loop <")
while(True):
    # See if any data is available
    data = d.receive()
    print('Received Payload: %r' % data)

    # Send keyalive heartbeat
    print(" > Send Heartbeat Ping < ")
    payload = d.generate_payload(tinytuya.HEART_BEAT)
    d.send(payload)

    # NOTE If you are not seeing updates, you can force them - uncomment:
    # print(" > Send Request for Status < ")
    # payload = d.generate_payload(tinytuya.DP_QUERY)
    # d.send(payload)

    # NOTE Some smart plugs require an UPDATEDPS command to update power data
    # print(" > Send DPS Update Request < ")
    # payload = d.generate_payload(tinytuya.UPDATEDPS)
    # d.send(payload)    
```

**Comment by gabrielklein** [comment]
Thank you @jasonacox for the code, it's really useful!

I run a cron every minutes to update all my power plugs.
(I bought them from a company called hombli).

I've named them "Pow...".
I share the code as it might be useful for other people.

I'm using python 3.10

I'll try your approach and use data2 = d.status() as it seams to do the job.

Process: PowSalonDelComp
{'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2376, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}
 > Wait 5 sec < 
 > Request Update < 
{'dps': {'20': 2386}, 't': 1665955108}
 > Fetch Status Again < 
{'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2386, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}

Before {'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2376, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}
After  {'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2386, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}
Process: PowElouanAqua
{'dps': {'1': True, '9': 0, '17': 7, '18': 41, '19': 86, '20': 2365, '21': 1, '22': 602, '23': 30117, '24': 16545, '25': 2510, '26': 0}}
 > Wait 5 sec < 
 > Request Update < 
{'dps': {'19': 84}, 't': 1665955416}
 > Fetch Status Again < 
{'dps': {'1': True, '9': 0, '17': 7, '18': 41, '19': 84, '20': 2365, '21': 1, '22': 602, '23': 30117, '24': 16545, '25': 2510, '26': 0}}

Before {'dps': {'1': True, '9': 0, '17': 7, '18': 41, '19': 86, '20': 2365, '21': 1, '22': 602, '23': 30117, '24': 16545, '25': 2510, '26': 0}}
After  {'dps': {'1': True, '9': 0, '17': 7, '18': 41, '19': 84, '20': 2365, '21': 1, '22': 602, '23': 30117, '24': 16545, '25': 2510, '26': 0}}
Process: PowBuanderieCongelateur
{'dps': {'1': True, '9': 0, '17': 7, '18': 0, '19': 0, '20': 2362, '21': 1, '22': 554, '23': 27888, '24': 14888, '25': 2800, '26': 0}}
 > Wait 5 sec < 
 > Request Update < 
None
 > Fetch Status Again < 
{'dps': {'1': True, '9': 0, '17': 7, '18': 0, '19': 0, '20': 2362, '21': 1, '22': 554, '23': 27888, '24': 14888, '25': 2800, '26': 0}}

Before {'dps': {'1': True, '9': 0, '17': 7, '18': 0, '19': 0, '20': 2362, '21': 1, '22': 554, '23': 27888, '24': 14888, '25': 2800, '26': 0}}
After  {'dps': {'1': True, '9': 0, '17': 7, '18': 0, '19': 0, '20': 2362, '21': 1, '22': 554, '23': 27888, '24': 14888, '25': 2800, '26': 0}}
Process: PowInternet
{'dps': {'1': True, '9': 0, '17': 8, '18': 122, '19': 155, '20': 2390, '21': 1, '22': 551, '23': 28138, '24': 14742, '25': 2820, '26': 0}}
 > Wait 5 sec < 
 > Request Update < 
{'dps': {'18': 125, '19': 158, '20': 2386}, 't': 1665955423}
 > Fetch Status Again < 
{'dps': {'1': True, '9': 0, '17': 8, '18': 125, '19': 158, '20': 2386, '21': 1, '22': 551, '23': 28138, '24': 14742, '25': 2820, '26': 0}}

Before {'dps': {'1': True, '9': 0, '17': 8, '18': 122, '19': 155, '20': 2390, '21': 1, '22': 551, '23': 28138, '24': 14742, '25': 2820, '26': 0}}
After  {'dps': {'1': True, '9': 0, '17': 8, '18': 125, '19': 158, '20': 2386, '21': 1, '22': 551, '23': 28138, '24': 14742, '25': 2820, '26': 0}}
Process: PowSalonDelComp
{'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2381, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}
 > Wait 5 sec < 
 > Request Update < 
{'dps': {'20': 2386}, 't': 1665955426}
 > Fetch Status Again < 
{'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2386, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}

Before {'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2381, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}
After  {'dps': {'1': True, '9': 0, '17': 1, '18': 0, '19': 0, '20': 2386, '21': 1, '22': 524, '23': 26684, '24': 14140, '25': 2950, '26': 0}}


```
import tinytuya
import json
import time

# Only one instance at a time
from tendo import singleton
me = singleton.SingleInstance() # will sys.exit(-1) if other instance is running

# Open snapshot.json and find strings that start with "Pow"
f = open('tinytuya/snapshot.json')
data = json.load(f)
f.close()

# Add outlet to o
# The outlet must start with "Pow!"
# o = []
for i in data['devices']:
  if i["name"][0:3] == 'Pow':
    print('Process: ' + i["name"])
    d = tinytuya.OutletDevice(i["id"], i["ip"], i["key"])
    d.set_version(3.3)
    d.set_socketPersistent(True)
    #d.set_socketTimeout(5)
    #d.set_socketRetryLimit(5)
  
    payload = d.generate_payload(tinytuya.UPDATEDPS,['18','19','20'])
    #payload = d.generate_payload(tinytuya.UPDATEDPS)
    
    d.send(payload)
    json2 = d.receive()
    print('UpdateDPS (',i["name"],'): ', json2)
    time.sleep(2)
    
  elif i["name"][0:3] == 'Led':
    print('Don\'t process: ' + i["name"])

  elif i["name"][0:4] == 'Temp':
    print('Don\'t process: ' + i["name"])
      
  elif i["name"][0:4] == 'Ring':
    print('Don\'t process: ' + i["name"])
      
  else:
    print('Unknown: ' + i["name"])

```

**Comment by gabrielklein** [comment]
Here is my final script, fell free to add it to your samples if you think it's useful.

This script post on my mqtt an updated status of the power consumption of all my plugs.

```
# This script is executed once a minute in my cron.
# It will post current, volts and power of all Tuya's power plugs. You need a snapshot.json (with the IPs).
# Only process power plugs that start with "Pow"!
# basetopic + "/" + name + "/current"
# Example:
# tuya/PowBuanderieLaveLinge/current 0.0
# tuya/PowBuanderieLaveLinge/power 0.0
# tuya/PowBuanderieLaveLinge/voltage 236.8

import tinytuya
import json
import time
from paho.mqtt import client as mqtt_client

# Only one instance at a time
from tendo import singleton
me = singleton.SingleInstance()  # will sys.exit(-1) if other instance is running

# ------------------------------------------------
# Config
# ------------------------------------------------
snapshotpath = 'tinytuya/snapshot.json'
broker = '127.0.0.1'
port = 1883
basetopic = "tuya"
client_id = 'TinyTuyaMqtt'

# ------------------------------------------------
# Main process
# ------------------------------------------------
def main():

    # Open snapshot.json and find strings that start with "Pow"
    f = open(snapshotpath)
    data = json.load(f)
    f.close()

    client = connectMqtt()

    for i in data['devices']:
        # Change this line to match your naming convention
        # My power plugs are named: PowABC, PowX, ...
        if i["name"][0:3] == 'Pow':
            try:
                print('Process: ' + i["name"])
                d = tinytuya.OutletDevice(i["id"], i["ip"], i["key"])
                d.set_version(3.3)
                d.set_socketPersistent(True)
                d.set_socketTimeout(1)
                d.set_socketRetryLimit(1)

                data = d.status()
                result = d.updatedps(['18', '19', '20'])
                data2 = d.status()

                current = float(data2["dps"]["18"])
                power = float(data2["dps"]["19"]) / 10
                voltage = float(data2["dps"]["20"]) / 10

                print("Values: %r mA, %r W, %r V" % (current, power, voltage))
                sendMqttPower(client, i["name"], current, power, voltage)

            except KeyError:
                print("Problem reading device informations")

        elif i["name"][0:3] == 'Led':
            print('Don\'t process: ' + i["name"])

        elif i["name"][0:4] == 'Temp':
            print('Don\'t process: ' + i["name"])

        elif i["name"][0:4] == 'Ring':
            print('Don\'t process: ' + i["name"])

        else:
            print('Unknown: ' + i["name"])

# ------------------------------------------------
# Send to mqtt power info
# ------------------------------------------------
def sendMqttPower(client, name, current, power, voltage):
  # print("Values for %r: %r mA, %r W, %r V" % (name, current, power, voltage))
  client.publish(basetopic + "/" + name + "/current", current)
  client.publish(basetopic + "/" + name + "/power", power)
  client.publish(basetopic + "/" + name + "/voltage", voltage)

# ------------------------------------------------
# Connect to mqtt
# ------------------------------------------------
def connectMqtt():
    client = mqtt_client.Client(client_id)
    #client.username_pw_set(username, password)
    client.connect(broker, port)
    return client

# ------------------------------------------------
# Run main
# ------------------------------------------------
main()

```

**Comment by jasonacox** [comment]
Awesome! Excellent work @gabrielklein... Thanks for sharing this!
