### ISSUE TITLE
[WinError 10054]

### ISSUE THREAD

**Issue by burakmartin** [jasonacox/tinytuya#2]
Sometimes this error appears, probably because a connection hasnt been closed before connecting to it again. How would I make sure that a connection to a device is closed?

**Comment by jasonacox** [comment]
Interesting. The `_send_receive()` function calls `s.close()` each time.

What is your `python --version`?  Also, what version of Windows are you using?

**Comment by elfman03** [comment]
I see this too.

Windows 10 (19042.572)
python --version : 3.8.6

`C:\Users\Perez family\Desktop\projector_control>python tuya_test.py
on
Traceback (most recent call last):
  File "tuya_test.py", line 23, in <module>
    data=tuya.turn_on()
  File "C:\Users\Perez family\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tinytuya\__init__.py", line 449, in turn_on
    self.set_status(True, switch)
  File "C:\Users\Perez family\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tinytuya\__init__.py", line 423, in set_status
    data = self._send_receive(payload)
  File "C:\Users\Perez family\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tinytuya\__init__.py", line 280, in _send_receive
    s.send(payload)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
`

**Comment by elfman03** [comment]
Sample app.  If I run it back to back, sometimes it runs, sometimes it gives the error a few times then runs again.

tuya=tinytuya.BulbDevice('bulb_id_here','ip_addr_here','key_here')
tuya.set_version(3.3)
data=tuya.status()
#print('Dictionary %r' % data)
if(data['dps']['1']==False):
  print("off")
else:
  print("on")
data=tuya.turn_on()
print('PostDictionary %r' % data)
data=tuya.set_colour(0xde,0xad,0)
print('PostDictionary %r' % data)
data=tuya.status()
#print('Dictionary %r' % data)
if(data['dps']['1']==False):
  print("off")
else:
  print("on")

**Comment by elfman03** [comment]
Another sample:

tuya=tinytuya.BulbDevice('bulb_id_here','ip_addr_here','key_here')
tuya.set_version(3.3)
for i in range(20):
  print("try "+str(i))
  data=tuya.status()
  if(data['dps']['1']==False):
    print("off")
  else:
    print("on")

on my system, the loop runs 0-6 steps before running into 10054 (and in one place a socket timeout)

**Comment by jasonacox** [comment]
Thanks for the additional details!  Can you try making this minor change to your test?

```python
import time

tuya=tinytuya.BulbDevice('bulb_id_here','ip_addr_here','key_here')
tuya.set_version(3.3)
for i in range(20):
    print("try "+str(i))
    while(True):
        try:
            data=tuya.status()
            if(data['dps']['1']==False):
                print("off")
            else:
                print("on")
            break
        except:
            time.sleep(5)
    # while
# for
```

**Comment by elfman03** [comment]
I will try sometime tomorrow.

**Comment by elfman03** [comment]
I brought the bulb to a different network/system
python --version : 3.8.6
Windows 10 (18363.1198).  Looks like I need to upgrade.

I added a print statement to the exception block in your test suggestion.

       except:
            print("---------------------oops--------------------")
            time.sleep(5)

It got thru 20 cycles with no oops a number of times and had a single oops several times.  Then I had a run that looked like this with one 20 second issue and another 15 second issue:

C:\Users\Chris\Desktop\projector_control>python tuya-test.py
try 0
off
try 1
off
try 2
off
try 3
off
try 4
off
try 5
off
try 6
off
try 7
off
try 8
off
try 9
off
try 10
off
try 11
off
try 12
off
try 13
off
try 14
---------------------oops--------------------
---------------------oops--------------------
---------------------oops--------------------
off
try 15
---------------------oops--------------------
---------------------oops--------------------
off
try 16
off
try 17
off
try 18
off
try 19
off

I can't really handle a 20 second delay in a bulb transition (we are using it to turn colors to indicate states in live streaming).  We're currently using the official app with Android widgets and am trying to make an alternate way to control it.  I may try to pull the code and try to make more persistent connection to the bulb instead of separate connections per command.  I'm not sure if the bulb insists on connection teardown on each command or not.

**Comment by elfman03** [comment]
i pulled from master instead of doing a pip install and it seems a bit more stable.  I'm not sure what the difference between this and what is in pip.

I also removed from _send_receive() and it seems to be have fewer momentary pauses during the test.
 #s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

**Comment by elfman03** [comment]
added a fork which attempts a couple of change:
persistent socket that is just restarted if there is an issue with the send/receive or if the destructor is called
retry loop if the send or receive fails (similar to your test kindof)
added initial hook to set scenes that were configured in the SmartLife app

**Comment by jasonacox** [comment]
Awesome!  Thanks @elfman03.  I see your changes... 
https://github.com/jasonacox/tinytuya/compare/master...elfman03:master

Did this fix the latency issue?  Any side effects?

**Comment by PHunHouse** [comment]
> Awesome! Thanks @elfman03. I see your changes...
> [master...elfman03:master](https://github.com/jasonacox/tinytuya/compare/master...elfman03:master)
> 
> Did this fix the latency issue? Any side effects?

I am going to sound like a complete noob:

elfman03 made some changes to the code. Can we mirror those changes to the original in order to mitigate the issue?

**Comment by jasonacox** [comment]
Yes, that was my plan.  I just need to verify that there are no side effects to other projects that use **tinytuya**.

**Comment by elfman03** [comment]
I haven't seen any negative side effects under basic testing with basic sequences of on/off/color/mode changes.  I have seen a few instances where it did a retry (which I assume was the 10054 error being caught) but the retry loop has only taken like one to two 0.1 second retrys for me so far which is a pretty quick recovery.

I'll try to test it a bit more with a looping test but it probably won't be until early next week depending on when I get my test bulb back again.

Note that there is one print statement in the retry code that probably should be a proper log command to avoid polluting application output but I was fine with a quick and dirty print for testing.

**Comment by elfman03** [comment]
I got access to the bulb here again for a bit more testing.  
- the persistent socket definately helps.  When running a loop of get_status() closing the socket every time, it gets the error every 3-20 instances.  With the persistent socket it was able to issue 2000 get_status() commands with no retry.
- the 0.1 second retry when the error does happen seems to work as well.  When I closed the socket after every time but kept the 0.1 second retry it seemed to recover within 1 (2 at the worst) retries in a loop of 2000 get_status() commands

Let me know if you need me to do any cleanup to the code before you merge.

**Comment by elfman03** [comment]
if you are concerned about side effects and this problem is not widely sen, we could add something like a set_persistentSocket(True/False) call...

**Comment by jasonacox** [comment]
Thanks @elfman03 - I really like that idea!  Would you mind adding that logic (default to non-persistent to eliminate any uninential side effects), cleaning up the code as you mention, and submit a pull request?  Make sure you have a valid email associated with your github ID and when I merge you should get credit as a contributor.

**Comment by elfman03** [comment]
Sure, I'll try to do it in the next 2-4 days.

**Comment by jasonacox** [comment]
Awesome! Thanks @elfman03 - I'll cancel my PR.  Submit a new pull request when you have it ready.

**Comment by jasonacox** [comment]
I merged your PR - thank you!  I may revisit the `while not success` loop just to ensure we have a proper timeout mechanism instead of an infinite loop.  Once I complete that and test, I'll push to PyPI and update this thread.

**Comment by elfman03** [comment]
Want a set_socketRetryLimit(int) [default 5]?

**Comment by jasonacox** [comment]
Yes, I think that would be perfect!

**Comment by elfman03** [comment]
Ok, I should be able to do it tomorrow.

**Comment by jasonacox** [comment]
Updates pushed v1.0.5 - https://pypi.org/project/tinytuya/1.0.5/

**Comment by elfman03** [comment]
I think this one may be ready to close.  I was able to run successfully against the pip installed 1.0.5.

thanks for pushing a new version!

**Comment by jasonacox** [comment]
That's great news!  I will close this. Thanks @elfman03 for your help and for being a *TinyTuya* contributor!
