### ISSUE TITLE
Python ERROR when trying to run 'wizzard'

### ISSUE THREAD

**Issue by FScociety** [jasonacox/tinytuya#20]
When I type the command: 'python3 -m tinytua wizard' I can enter the: 'api Key, apiSecret, apiRegion, apiDeviceID'. But then running the command an error shows up after like 2sec:

> Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/tinytuya/__main__.py", line 48, in <module>
    tinytuya.wizard(color)
  File "/usr/local/lib/python3.8/dist-packages/tinytuya/__init__.py", line 1548, in wizard
    uid = response_dict['result']['uid']
KeyError: 'result'

Tested platforms: mac osx high Sierra 10.13.6 and linux(pop os! 2020)
Also I have 3 tuya devices(Breaker) and they are connected using the Tuya Smart app.

**Comment by jasonacox** [comment]
Unfortunately there needs to be more error handling in the wizard.  What you see could be the result of not getting a valid token back from the Tuya Platform (likely a bad apiKey and apiSecret) or it could be that you are getting a valid authorization token from the Tuya Platform, but it is not able to find that DeviceID in your account.  Run this:

```python
python3 -m tinytuya scan
```

You should see a DeviceID from the 3 devices you have.  PIck one of those and use that in the Wizard.

Did you follow the process https://github.com/jasonacox/tinytuya#get-the-tuya-device-local_key to get the iot.tuya.com developer account?

**Comment by FScociety** [comment]
Omg, iam so dumb.
I forget: Verify under Cloud Development -> select your project -> API Setting that the following API groups have status "Open": Authorization management, Device Management and Device Control (see here)

Now it works fine. But thanks for your time and support 👍

**Comment by oscarenzo** [comment]
Hello,

I'm still in the same problem, my subscription are:

![image](https://user-images.githubusercontent.com/22533441/111233171-c7745c80-85ec-11eb-8dd1-ff43a5275f17.png)

and the error persist:

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/pyenv/smartlife/lib/python3.8/site-packages/tinytuya/__main__.py", line 48, in <module>
    tinytuya.wizard(color)
  File "/opt/pyenv/smartlife/lib/python3.8/site-packages/tinytuya/__init__.py", line 1587, in wizard
    uid = response_dict['result']['uid']
KeyError: 'result'
`
I had linked my smartlife account to the tuya platform, can you help me?, thank you

**Comment by jasonacox** [comment]
Out of curiosity, are you subscribe to all the APIs?

![image](https://user-images.githubusercontent.com/836718/111419675-1d0d3f80-86a7-11eb-81ad-f6078ee391fe.png)
