### ISSUE TITLE
Does it work with motion sensor?

### ISSUE THREAD

**Issue by estebanroblesluna** [jasonacox/tinytuya#22]
Thanks for you hard work

**Comment by jasonacox** [comment]
I understand that some of the Tuya devices, like sensors, just send to the Tuya Cloud and do not broadcast on the local network.  If you see the motion sensor when doing a scan (e.g. `python -m tinytuya scan`) then it is highly likely that you can use tinytuya to monitor it.  Otherwise, you would need to use the wizard to get the local key AND somehow figure out its IP address.  I don't have any sensors to test so let me know if you are able to get it to work.

**Comment by estebanroblesluna** [comment]
Hi @jasonacox, thanks for replying.
I'll try it this week and get back to you with my results so that you can add them to the library
Regards
Esteban

**Comment by estebanroblesluna** [comment]
Hi @jasonacox,
I have the IP, local key (obtained from https://iot.tuya.com/cloud/appinfo/cappId/explorer using get device details) and the device id and I tried to reversed engineer using Wireshark without success yet.
The scan tool doesn't see it, however I was able to get the initial ip from my Cisco router. A device appears and disappears when it find a move in the sensor: ESP_C3FE07.
Using sudo nmap -sU  -p6668 192.168.1.0/24 I was able to validate that 6666, 6667 and 6668 are open momentarily for a few seconds every now and then. In wireshark I don't see any packages with 'udp.port == 6666 or udp.port == 6667'.

Do you have the documentation of where the cloud api is located so that I can filter the packages in wireshark?

**Comment by jasonacox** [comment]
I suspect the motion sensor is designed to operate in low power mode which means it shuts down the WiFi subsystem when not needed.  As with all Tuya devices, they are designed to interact with the TuyaCloud.  The sensor would only need to send something if state changes (motion in this case).  With that in mind, if it is disabling WiFi or the websocket to save power, it may not be possible to access it locally. 

Can you post a link to the sensor you have?  Also, does your motion sensor have a separate powered bridge/gateway device? 

One random thought, if the sensor only comes online when it detect motion, or every 5m or so to update the Cloud, we could construct a constant loop service that continually tries to reach the device and pull state.  It may respond with motion data for that brief moment it is updating the cloud.

**Comment by estebanroblesluna** [comment]
Hi @jasonacox ,
The sensor is this one: https://expo.tuya.com/product/322368

I did what you mentioned and pull the state from the Cloud system every 10 seconds and it worked fine. However, I have to avoid using this solution for 2 reasons:
- They sensors are battery hungry
- The sensor became unstable and was marked as in PIR state in the cloud even though it was off in my physical device (I guess the sensor hang and never marked as normal in the cloud).

I end up buying an analog sensor with cables and code an Arduino gateway that broadcast the state of the sensors to my local LAN. By far a more stable and trusted solution.

Sorry for not updating the ticket before

**Comment by jasonacox** [comment]
Thanks @estebanroblesluna !  I was worried it was likely a power issue.  Funny thing, I did the same thing as you and use an Arduino for my motion sensors.  

Can you share the code you used to do the 10s polling?

**Comment by estebanroblesluna** [comment]
Sure @jasonacox, we end up in the same place.
For the Tuya service, I had to prune the code as it contains some information from the project but in essence is the following gists:

AbstractScheduledService (exposed from my framework): https://gist.github.com/estebanroblesluna/932642885a02bb1b2cc2b9b3e2b234ad

TuyaService (some methods have been removed): https://gist.github.com/estebanroblesluna/8baa5df2347f484e788b1e0d3d5866ee 

Hope it helps and if you have any comments please let me know.
Just FYI, it is too OO, I'm a former Smalltalk engineer ;)

**Comment by jasonacox** [comment]
Thanks, @estebanroblesluna!  That's Beautiful code!  I like OO... I still code in Objective C. ;)
