### ISSUE TITLE
Add support for devices connected via zigbee gateway

### ISSUE THREAD

**Issue by LesTR** [jasonacox/tinytuya#221]
I would like to communicate with devices connected via zigbee gateway. I got [this set](https://www.aliexpress.com/item/4001332022929.html), and I would like to connect it to HomeAssistant via [tuya-local](https://github.com/make-all/tuya-local) plugin. As the first `tinytuya` needs to support this type of device - tuya-local use this library.

According to other implementations ([example](https://github.com/codetheweb/tuyapi/blob/v7.5.1/index.js#L123)) we should connect to the gateway and pass another param `cid`, which is the id of subdevice connected to the gateway.

I have a working prototype in my fork of tuya-local.

**Comment by jasonacox** [comment]
Hi @LesTR - Thanks for opening this issue and PR.  This is a great addition!!  

However, I have one minor request before we merge and release as a minor patch:  While an extremely low chance of being a breaking change for someone directly using the base class, I would prefer to move all new additional argument in functions and `__init__` constructors to the end (for positional argument continuity):

Changing this: 

```python
# From this

class XenonDevice(object):
    def __init__(
            self, dev_id, address=None, local_key="", dev_cid = None, dev_type="default", connection_timeout=5, version=3.1, persist=False
    ):

# To this

class XenonDevice(object):
    def __init__(
            self, dev_id, address=None, local_key="", dev_type="default", connection_timeout=5, version=3.1, persist=False, dev_cid = None
    ):
```

Does that make sense?  

@uzlonewolf - I know you are doing zigbee work as well (e.g. #31).  Any thoughts or concerns?

**Comment by uzlonewolf** [comment]
Not really.  The one I'm working on includes the changes in #222 along with a bunch of others.  #222 works fine as long as you do not use persistence with more than one sub-device.  I was also going to call it "node_id" instead of "cid" in order to match the name of the variable in devices.json (once `node_id` is added to `DEVICEFILE_SAVE_VALUES` so the wizard saves it as well), though I'm also fine with `cid` as that's what the device returns.

**Comment by LesTR** [comment]
Hi @jasonacox and @uzlonewolf,

> I would prefer to move all new additional argument in functions and __init__ constructors to the end (for positional argument continuity):

It makes absolute sense; thanks for pointing it out. Changed.

> https://github.com/jasonacox/tinytuya/pull/222 works fine as long as you do not use persistence with more than one sub-device.

@uzlonewolf can you please explain this issue? Sorry, I'm new to this. My Home Assistant is right now in read-only mode.

>  I was also going to call it "node_id" instead of "cid"

Initially, this was my first choice, as they named it in explore API, but then I changed it to returned JSON field and kept it consistent with node.js lib. I still don't have a strong opinion on this.

**Comment by uzlonewolf** [comment]
@LesTR Are you able to turn Zigbee devices on and off with this?  With my gateway, adding `cid` allows me to poll the device status, however commands like `turn_on()` are not working.

**Comment by uzlonewolf** [comment]
The bridge keeps track of the state and answers the query for the device.

To receive async events just set `persist=True` on the parent device and use a monitor loop such as https://github.com/jasonacox/tinytuya/blob/master/examples/zigbee_gateway.py
