### ISSUE TITLE
Sombody Help me with my code

### ISSUE THREAD

**Issue by Electrik-rich546456** [jasonacox/tinytuya#23]
I have managed to make two simple scripts to turn a light on and off.
I would like to know, how i can make the script a bit more interactive & check status of power before flipping it to the other state. I cannot seem to make it show power status bol of 1 or 0 but using the smart life app it displays the status just fine so my bulbs are capable of providing that data.

So to clarify I have got two 432mhz switches that my rpi is listening to. i would like to assign them to the power flip flop i was asking about.

At the moment it works using a bash script. It monitors the exec binary that prints a "signal received" msg. and that in turn triggers my two independent simple py scripts 

So how do i add it all into one python script that can also control a group of lights.

I hope this is possible to someone with greater knowledge than me.
Thank you in advance if you decide to help.

**Comment by jasonacox** [comment]
I think this was answered in the other issue thread #25 with something like this:

```python
if(data['dps']['20'] == True):
    print("its on Turning off")
    d.turn_off()
else:
    print("its off Turing on")
    d.turn_on()
```
