### ISSUE TITLE
scan not showing device ID

### ISSUE THREAD

**Issue by abhishekranaji** [jasonacox/tinytuya#24]
>py -m tinytuya scan -nocolor

TinyTuya (Tuya device scanner) [1.1.3]

Scanning on UDP ports 6666 and 6667 for devices (15 retries)...

*  Unexpected payload=%r
 b"\xd0\x97fgo3i\xeb\x10\xb5\xe9\xf12\xfd\x80*\xc1w\xcf=\x9e\xc5\xe6\x8dD\xed'\xad\xe5\xe7U0\xde\x19\xf6\x08\xc0\xf6\x16&\xb1\xf8w\x87'\x97\xc
ao\x1a{\xcbu\xef[\xb8\xeb3\n\xd3D\xdd\x0b\x10h\xdb\x19\xaf\x80#H\xb8\x03B\x1e@\xba\n{|x\xfa@g\xfbZs\x89\xaf\xbe\xaf\x88\n\x12\xd3\xbbl\x9f9`\x
8aV\xbc\x82\x10\x8d\xd9\x84\xa5\xbf\xdc\x87\xe3ZtL95'>\xa5*ez\xcc\xeeOT\xa4\xa1,\xcaMo\xba\xcc\x17l\xe6\xa4\x01T\xedr2b\x7f,=\x9cGDX^G\x1bj/\x
c4y\xca"
 Device Found [Unknown payload]: 192.168.1.3
    ID = , Product ID = , Version =
    No Stats - Device Key required to poll for status
*  Unexpected payload=%r
 b"\xd0\x97fgo3i\xeb\x10\xb5\xe9\xf12\xfd\x80*\xc1w\xcf=\x9e\xc5\xe6\x8dD\xed'\xad\xe5\xe7U0\xde\x19\xf6\x08\xc0\xf6\x16&\xb1\xf8w\x87'\x97\xc
ao\x1a{\xcbu\xef[\xb8\xeb3\n\xd3D\xdd\x0b\x10h\xdb\x19\xaf\x80#H\xb8\x03B\x1e@\xba\n{|x\xfa@g\xfbZs\x89\xaf\xbe\xaf\x88\n\x12\xd3\xbbl\x9f9`\x
8aV\xbc\x82\x10\x8d\xd9\x84\xa5\xbf\xdc\x87\xe3ZtL95'>\xa5*ez\xcc\xeeOT\xa4\xa1,\xcaMo\xba\xcc\x17l\xe6\xa4\x01T\xedr2b\x7f,=\x9cGDX^G\x1bj/\x
c4y\xca"
*  Unexpected payload=%r
 b"\xd0\x97fgo3i\xeb\x10\xb5\xe9\xf12\xfd\x80*\xc1w\xcf=\x9e\xc5\xe6\x8dD\xed'\xad\xe5\xe7U0\xde\x19\xf6\x08\xc0\xf6\x16&\xb1\xf8w\x87'\x97\xc
ao\x1a{\xcbu\xef[\xb8\xeb3\n\xd3D\xdd\x0b\x10h\xdb\x19\xaf\x80#H\xb8\x03B\x1e@\xba\n{|x\xfa@g\xfbZs\x89\xaf\xbe\xaf\x88\n\x12\xd3\xbbl\x9f9`\x
8aV\xbc\x82\x10\x8d\xd9\x84\xa5\xbf\xdc\x87\xe3ZtL95'>\xa5*ez\xcc\xeeOT\xa4\xa1,\xcaMo\xba\xcc\x17l\xe6\xa4\x01T\xedr2b\x7f,=\x9cGDX^G\x1bj/\x
c4y\xca"
*  Unexpected payload=%r
 b"\xd0\x97fgo3i\xeb\x10\xb5\xe9\xf12\xfd\x80*\xc1w\xcf=\x9e\xc5\xe6\x8dD\xed'\xad\xe5\xe7U0\xde\x19\xf6\x08\xc0\xf6\x16&\xb1\xf8w\x87'\x97\xc
ao\x1a{\xcbu\xef[\xb8\xeb3\n\xd3D\xdd\x0b\x10h\xdb\x19\xaf\x80#H\xb8\x03B\x1e@\xba\n{|x\xfa@g\xfbZs\x89\xaf\xbe\xaf\x88\n\x12\xd3\xbbl\x9f9`\x
8aV\xbc\x82\x10\x8d\xd9\x84\xa5\xbf\xdc\x87\xe3ZtL95'>\xa5*ez\xcc\xeeOT\xa4\xa1,\xcaMo\xba\xcc\x17l\xe6\xa4\x01T\xedr2b\x7f,=\x9cGDX^G\x1bj/\x
c4y\xca"

Scan Complete!  Found 1 devices.

On scanning i am not getting device details like version, device id
These are beca thermostat sensor it was working fine before, Now  it is not showing anything
Please help

**Comment by jasonacox** [comment]
> These are beca thermostat sensor it was working fine before, Now it is not showing anything

When you say "before" - what changed or is different between when it worked and now?

**Comment by abhishekranaji** [comment]
Before it was showing ID, Product ID, version , Now it is not showing them for the device.
And i have all info of device when i used d.status()
I am getting 

Traceback (most recent call last):
  File "C:/BECA APP/beca-pypass/scan/test42.py", line 8, in <module>
    data = d.status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tinytuya\__init__.py", line 401, in status
    result = cipher.decrypt(result, False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tinytuya\__init__.py", line 165, in decrypt
    plain_text += cipher.feed()  # flush final block
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyaes\blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyaes\blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyaes\util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte

**Comment by jasonacox** [comment]
If it was working and just suddenly stopped working without any change by you, I would troubleshoot:

* Python Corrupt - Your windows systems installation of of python has become corrupt - you may want to remove and re-install
* Tinytuya Corrupt - The install of tinytuya may be corrupt, you can run:
```
python -m pip uninstall tinytuya
python -m pip install tinytuya
```
* Device Key Change - If you re-activated any of your devices, they may have reset their local key.  You will need to retrive these agian:
```
python -m tinytuya wizard
```

**Comment by abhishekranaji** [comment]
Yes, device local key was changed as i changed wifi of device from app
