### ISSUE TITLE
WiFi Air Quality Detector - documentation

### ISSUE THREAD

**Issue by mar-svo** [jasonacox/tinytuya#251]
Hello everybody,

I've bought this device:
 - Tuya WiFi 6 In 1 Air Quality Detector PM2.5/Formaldehyde/VOC/CO2/Temperature/Humidity
 - https://www.aliexpress.com/item/1005005034880204.html

After my reverse-engineering here is part to fill in documentation:

Version 3.3 Devices

Version 3.3 - WiFi Air Quality Detector PM2.5/Formaldehyde/VOC/CO2/Temperature/Humidity

^ DP ID ^ Function Point                        ^ Type    ^ Range      ^ Units                 ^
| 2     | PM2.5 value                           | integer | 0 - 999    | ug/m3                 |
| 18    | Current Temperature                   | integer | 0 - 850    | ˚C (multiplied by 10) |
| 19    | Current Humidity                      | integer | 0 - 1000   | % (multiplied by 10)  |
| 20    | CH2O (Formaldehyde) value             | integer | 0 - 1000   | ppm                   |
| 21    | VOC (Volatile organic compound) value | integer | 0 - 2000   | ppm                   |
| 22    | CO2 value                             | integer | 350 - 2000 | ppm                   |

All the best,
Martin Svoboda

**Comment by jasonacox** [comment]
Thanks for this @mar-svo !  I've added this table to the 3.3 device section in the [README](https://github.com/jasonacox/tinytuya#version-33---wifi-air-quality-detector-pm25formaldehydevocco2temperaturehumidity).

The list of devices is getting long. I'm wondering if we should separate out all the device DPS lists into its own document, e.g. DEVICES.md linked from the README with its own TOC/index.
