### ISSUE TITLE
Network Error: Device Unreachable

### ISSUE THREAD

**Issue by anar4732** [jasonacox/tinytuya#263]
Hi. I have got a [smart plug device](https://www.aliexpress.us/item/2255800695524155.html?spm=a2g0o.order_list.order_list_main.5.73051802syi00Q&gatewayAdapt=glo2usa&_randl_shipto=US).

when running `tinytuya scan` I got this.
```
Address = 192.168.0.137,  Device ID = ebd4d219e570de778cc5ga, Local Key = aa555573d1xxxxx,  Version = 3.3, MAC = fc:67:1f:9f:75:29
    Access rejected by 192.168.0.137: Network Error: Device Unreachable
```
Other devices work fine so I don't think It's related to the network.
Also, the device works fine on the tuya app. so it's not actually unreachable.

**Comment by uzlonewolf** [comment]
The 2 most common causes of this I've seen are either the device got into a partially-hung state and needs to be rebooted, or there are too many simultaneous open connections to it (most devices only support 1-3 simultaneous connections).  I'd reboot the device and try again.

**Comment by anar4732** [comment]
> The 2 most common causes of this I've seen are either the device got into a partially-hung state and needs to be rebooted, or there are too many simultaneous open connections to it (most devices only support 1-3 simultaneous connections). I'd reboot the device and try again.

It worked! Thank you!
