### ISSUE TITLE
Not an issue, just a Thanks!

### ISSUE THREAD

**Issue by johnno1962** [jasonacox/tinytuya#281]
Thanks very much for posting this excellent repo. I was able to connect to my obscure tuya device through the cloud first try with your excellent README's and documentation. 👍 👍 👍

**Comment by jasonacox** [comment]
Thanks @johnno1962 !  This feedback is gold.  Thanks for taking the time to send it!

You may already know this, but one note on Tuya Cloud usage:  The free Tuya IoT (Trial) account allows a very limited number of Cloud API calls. Be careful with any automation that makes frequent calls. 😉

**Comment by johnno1962** [comment]
Thanks, I'll keep an eye out but it seems like I should squeak in under the allowance if it is monthly. Quite amazed that It all "just works".
