### ISSUE TITLE
Fast color changing

### ISSUE THREAD

**Issue by szymeq17** [jasonacox/tinytuya#29]
Hi, I came across a certain problem.

I am trying to make my BulbDevice change color every 0.2 second. The desired effect is blinking light.
Unfortunately, while program is running, bulb starts blinking in a desired way, but after a few blinkings it starts pulsating and then stars blinking again. I change color from (255, 0, 255) to (0, 0, 0) and by "pulsating" I mean that bulb only darkens a little and comes back to (255, 0, 255). I am wondering now, if it results from bulb limitations or it is something wrong with my code.

My code:

```
import tinytuya
import time
import random

d = tinytuya.BulbDevice('x', 'x', 'x, 'device22')
d.set_dpsUsed({"1": None})
d.set_version(3.3) 
d.set_socketPersistent(True)
d.set_socketNODELAY(False)

for i in range(100):
    d.set_colour(255, 0, 255)
    time.sleep(0.2)
    d.set_colour(0, 0, 0)
    time.sleep(0.2)
```

**Comment by jasonacox** [comment]
The smart bulbs I have like to "fade" between the RGB values changes instead of just switching.  I haven't been able to locate a setting that causes it to just do the direct change without a fade.  So, what you see is that the bulb begins to ramp fade from purple to black, just in time to get the next 200ms update to push it back to purple, so it looks like a pulse.  

For what you are doing, you could do something more direct, like this:

```python
for i in range(100):
    d.set_colour(255, 0, 255)      # purple
    d.turn_on()
    time.sleep(0.2)
    d.turn_off()                   # black
    time.sleep(0.2)
```

With my bulb that does a nice blink, but I did notice some cycles that were not exactly 400ms causing some uneven effect. It could be network related, but I suspect the device is just not going to be as precise with these subsecond changes.

**Comment by elfman03** [comment]
Does one of the SmartLife app scenes do what you want?  If so, you can use the smartlife app to set up the scene then use the api to set the scene using set_scene().

I use rainbow, rave and nature preconfigured colors in the SmartLife app to get some slow blink and pulse effects when I use set_scene() in the tinytuya api.

I've not checked if any of the SmartLife app scenes do a fast blink or not.

**Comment by szymeq17** [comment]
@elfman03 I figured out that I can set speed of the scene. When I set speed to 100% bulb changes colors immediately exactly as I want. Although I don't see how that would help :/

**Comment by jasonacox** [comment]
There have been several enhancement since this thread was started. For one, the `nowait` parameter is now available for many of the functions. This can help with fast color changing:

```python
import tinytuya
import time

# tinytuya.set_debug(True)
d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY, version=DEVICEVERS)

# Keep socket connection open between commands
d.set_socketPersistent(True)  

# Flip through colors of rainbow - set_colour(r, g, b):
print('\nColor Test - Cycle through rainbow')
rainbow = {"red": [255, 0, 0], "orange": [255, 127, 0], "yellow": [255, 200, 0],
           "green": [0, 255, 0], "blue": [0, 0, 255], "indigo": [46, 43, 95],
           "violet": [139, 0, 255]}
for x in range(5):
    for i in rainbow:
        r = rainbow[i][0]
        g = rainbow[i][1]
        b = rainbow[i][2]
        print('    %s (%d,%d,%d)' % (i, r, g, b))
        d.set_colour(r, g, b, nowait=False)
        time.sleep(0.1)
    print('')

time.sleep(1)
d.set_white()
```
