### ISSUE TITLE
set_brightness() sets White Mode

### ISSUE THREAD

**Issue by szymeq17** [jasonacox/tinytuya#30]
Is it possible to change brightness of RGB color? When i use set_brightness() color is changing to white.

**Comment by jasonacox** [comment]
The `set_brightness()` function set the DPS index for brightness which the bulb interprets as you wanting to switch back to white mode.  To set the brightness of a color, you increase the RGB values:

```python
 d.set_colour(255,0,0)     # bright red
 d.set_colour(10,0,0)      # dark red

 d.set_colour(255,255,255)   # full white brightness
 d.set_colour(128,128,128)   # half brightness
 d.set_colour(0,0,0)         # black
```

As a feature, I could add a handler to the `set_brightness()` function to do the RGB adjustments if the bulb is in colour mode.  I'll add that to the list. ;)

**Comment by jasonacox** [comment]
@szymeq17 : I'm happy to report that the latest [version v1.2.3](https://github.com/jasonacox/tinytuya/releases/tag/v1.2.3) now has updated `set_brightness()` and `set_brightness_percentage()` functions that work with the *colour* mode of the Bulbs. 

How it works: These functions convert RGB values to HSV (hue, saturation, value) color space and increase or decrease the V (brightness) values.  Any feedback on how well this performs would be appreciated.

How to upgrade:
```
pip install --upgrade tinytuya
```

```python
import tinytuya
import time

d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)  
d.set_colour(255,0,0) # red
time.sleep(1)

# ramp down
x = 100
while x > 0:
    d.set_brightness_percentage(x)
    x = x - 5
    time.sleep(0.1)

# ramp up
while x <= 100:
    d.set_brightness_percentage(x)
    x = x + 5
    time.sleep(0.1)

```
