### ISSUE TITLE
Cannot Link account - QR code has expired.

### ISSUE THREAD

**Issue by Miniontoby** [jasonacox/tinytuya#310]
I cannot link my account at Devices on the IOT:
![image](https://user-images.githubusercontent.com/47940064/227539734-e2a1d2cc-2bb6-42ed-a885-22648ec37a63.png)

Idk if this has to do with the fact I use LSC Smart Connect app or not

*And maybe this is not the correct place to ask this, but idk*

**Comment by uzlonewolf** [comment]
> Idk if this has to do with the fact I use LSC Smart Connect app or not

It does.  AFAIK only the Smart Life app is supported, I have yet to see any other app link successfully.

**Comment by Miniontoby** [comment]
But it does tell my phone that "(CHINESE CHARACTERS)" wants to login.

**Comment by uzlonewolf** [comment]
![Screenshot_20230324_072054_com lscsmartconnection smart](https://user-images.githubusercontent.com/16113541/227553717-2b57804a-384c-437b-bcf1-09764fdab4a3.jpg)

**Comment by Miniontoby** [comment]
Btw the Device info tab also not shows the local key, or does it?

**Comment by Miniontoby** [comment]
So I installed Tuya app and linked account, but I cannot find my device nor the local key. 

I don't know what I could do

**Comment by Miniontoby** [comment]
Oke, I fixed it by using the [Mitm method](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#deprecated---linking-a-tuya-device-with-mitm) that tuyapi 'suggests'. This in combination with an older version of the LSC Smart Connect app did the job for me! So now I can interact with my LED's using code.

**Comment by jasonacox** [comment]
Thanks for following up and posting the link!
