### ISSUE TITLE
Scan not working!!

### ISSUE THREAD

**Issue by skatbr** [jasonacox/tinytuya#322]
I have obtained the device ID and key, but I am not able to locate the device ID.
python -m tinytuya scan

TinyTuya (Tuya device scanner) [1.12.2]

Scanning on UDP ports 6666 and 6667 and 7000 for devices for 18 seconds...

Scan completed in 18.0269 seconds

Scan Complete!  Found 0 devices.
Broadcasted: 0
Versions:

>> Saving device snapshot data to snapshot.json
Why is it only looking at UDP? The device I am using is on TCP.
The scanner is not working; it always returns the same message: "Found 0 devices."

**Comment by jasonacox** [comment]
Hi @skatbr !

TinyTuya needs to run on the same network (subnet) as the device. If you have your devices on a different network (or are on a host or behind a firewall blocking certain traffic), the UDP traffic will not show up so it will not be able to discover your device.  You can for it to scan the IP range of your device network: 

```bash
python -m tinytuya scan -f
```

**Comment by m32** [comment]
pyaes isnt sufficient while scanning, pycryptodome must be installed:
Scanning on UDP ports 6666 and 6667 and 7000 for devices for 18 seconds...

DEBUG:tinytuya.scanner:Listening for Tuya devices on UDP ports 6666, 6667 and 7000
Traceback (most recent call last):                 
  File "/devel/00mirror-cvs/00-iot/tinytuya/tinytuya/scanner.py", line 1323, in devices
    result = tinytuya.decrypt_udp( data )
  File "/devel/00mirror-cvs/00-iot/tinytuya/tinytuya/core.py", line 1836, in decrypt_udp
    return decrypt(msg[20:-8], udpkey)
  File "/devel/00mirror-cvs/00-iot/tinytuya/tinytuya/core.py", line 1825, in decrypt
    return unpad(AES.new(key, AES.MODE_ECB).decrypt(msg)).decode()
AttributeError: 'NoneType' object has no attribute 'new'
