### ISSUE TITLE
Unable to find devices in wizard

### ISSUE THREAD

**Issue by job2310** [jasonacox/tinytuya#323]
Hi, I've been using tinytuya for a while but after upgrading to the latest version, I'm unable to find my devices using the wizard.  All of my details have stayed the same but it's returning 0 devices found (in the cloud).  If I run the local scan it finds all 8 devices.  I've double and triple checked my API key, Secret and example DeviceID but nothing seems to help.

Wondering if you might have any advice?

Many thanks,
Josh

**Comment by uzlonewolf** [comment]
That's odd, I'm seeing this too.  Seems the API we are calling suddenly stopped returning devices.  I'm looking into it now.

**Comment by uzlonewolf** [comment]
Hmm, it seems this API is now requiring a `Content-type: application/json` header or it won't return anything.  I'll try to release an update to fix this later today.

**Comment by job2310** [comment]
Many thanks.  Very odd that they would change that particular requirement at this point.

**Comment by Frefdt** [comment]
valid lmao, i'll try this in the meantime ty

**Comment by jasonacox** [comment]
Release fix as[ v1.12.3](https://pypi.org/project/tinytuya/1.12.3/). 

```bas
pip install --upgrade tinytuya
```

 Please report any issue.... Thanks all! 🙏

**Comment by uzlonewolf** [comment]
It seems Tuya made the API we were using private and is now returning a "permission deny" error instead of returning an empty list.  The fix in #324 still works.
