### ISSUE TITLE
Typo or intentional?

### ISSUE THREAD

**Issue by teejo75** [jasonacox/tinytuya#333]
https://github.com/jasonacox/tinytuya/blob/de222a5bae96b0ef1bf0c5babf0d6e79648f13ce/tinytuya/scanner.py#L71

Is that supposed to be `ablilty`?

**Comment by uzlonewolf** [comment]
That's what devices report.  It's a typo on Tuya's part, just like boardcast.

**Comment by teejo75** [comment]
Thanks for the insight. I searched the codebase and there were no code hits for 'ability' and only scanner.py for the typo. I was curious.
