### ISSUE TITLE
Cloud Development plan has expired

### ISSUE THREAD

**Issue by GitHub-source-42** [jasonacox/tinytuya#346]
<h2> Error When Scanning</h2>

Error from Tuya server: Error from Tuya Cloud: Code 28841002: 'No permissions. Your subscription to cloud development plan has expired.'
Check DeviceID and Region

There is no indication under my account that it is expired and the region is correct

<h2> python -m tinytuya wizard -debug</h2>
Scanning to find a Device ID...
DEBUG:Listening for Tuya devices on UDP ports 6666, 6667 and 7000
DEBUG:Received valid UDP packet: {'ip': '192.168.1.10', 'gwId': 'bfbf25a315d986faa3dqrm', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyx7semxnwsecug', 'version': '3.3'}
DEBUG:Scan complete with 1 devices found

Scan found Device ID 'bfbf25a315d986faa3dqrm'
DEBUG:Starting new HTTPS connection (1): openapi.tuyaeu.com:443
DEBUG:https://openapi.tuyaeu.com:443 "GET /v1.0/token?grant_type=1 HTTP/1.1" 200 235
DEBUG:GET: URL=https://openapi.tuyaeu.com/v1.0/token?grant_type=1 HEADERS={'secret': '8fa9fecc250241c3a70b63085920ae10', 'client_id': 'tpfgc59k7m3vkhauyuwf', 'sign': '25C14A05FF79B29DA77CDD4436B6551ED70F2363CDF3341658B4CDE214EA780A', 't': '1683808864987', 'sign_method': 'HMAC-SHA256', 'mode': 'cors'} response code=200 text={"result":{"access_token":"d6331dce64aacea64a0ff9cfc3d260c2","expire_time":6209,"refresh_token":"0930d55f368fe9791b752f2257e8a76b","uid":"bay1680099684461HQkz"},"success":true,"t":1683808865388,"tid":"186813a7eff911edb63796ce6b547e6f"} token=None
DEBUG:server_time_offset: 0
DEBUG:Starting new HTTPS connection (1): openapi.tuyaeu.com:443
DEBUG:https://openapi.tuyaeu.com:443 "GET /v1.0/devices/bfbf25a315d986faa3dqrm HTTP/1.1" 200 173
DEBUG:GET: URL=https://openapi.tuyaeu.com/v1.0/devices/bfbf25a315d986faa3dqrm HEADERS={'client_id': 'tpfgc59k7m3vkhauyuwf', 'sign': 'C75C8448AAFB0694E01DCC725E54577C13A5A633B24E2499DD2B7BA2E2F1AD3C', 't': '1683808865269', 'sign_method': 'HMAC-SHA256', 'mode': 'cors', 'access_token': 'd6331dce64aacea64a0ff9cfc3d260c2'} response code=200 text={"code":28841002,"msg":"No permissions. Your subscription to cloud development plan has expired.","success":false,"t":1683808865561,"tid":"18829f0aeff911edb8e6f637b158923e"} token=d6331dce64aacea64a0ff9cfc3d260c2
DEBUG:Error from Tuya Cloud: 'No permissions. Your subscription to cloud development plan has expired.'
DEBUG:ERROR Error Response from Tuya Cloud - 913 - payload: "Error from Tuya Cloud: Code 28841002: 'No permissions. Your subscription to cloud development plan has expired.'"

Error from Tuya server: Error from Tuya Cloud: Code 28841002: 'No permissions. Your subscription to cloud development plan has expired.'
Check DeviceID and Region

**Comment by jasonacox** [comment]
Hi @GitHub-source-42 

> response code=200 text={"code":28841002,"msg":"No permissions. Your subscription to cloud development plan has expired.","success":false,"t":1683808865561,"tid":"18829f0aeff911edb8e6f637b158923e"}

The Tuya IoT API definitely thinks your account is expired.  Do you see your deviceID bfbf25a315d986faa3dqrm in the IoT dev portal? Also, check your [subscriptions](https://github.com/jasonacox/tinytuya/files/8145832/Tuya.IoT.API.Setup.pdf) to make sure they don't show error/expired.

**Comment by GitHub-source-42** [comment]
It did say expired and yes I can see it. sorry classic PEBCAC
