### ISSUE TITLE
Returning none 

### ISSUE THREAD

**Issue by Dhruveshp** [jasonacox/tinytuya#360]
I am trying get_status and it always returns None.

Updated latest version 
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinytuya
>>> print(tinytuya.__version__)
1.12.8

import tinytuya

deviceID = 'xxxxxxxxxxxxxxx'
ipAddress = "10.0.0.9"
local_key = "xxxxxxxxxxxxxx"

d = tinytuya.OutletDevice(deviceID, ipAddress, local_key, 'device22')
d.set_version(3.3)
d.set_dpsUsed({"1": None})
data = d.status() 

print('Dictionary %r' % data)

**Comment by jasonacox** [comment]
Do you get anything with:

```
python3 -m tinytuya scan
```

Also, I recommend you try using without specifying `device22` and turning on debug:

```python
import tinytuya

tinytuya.set_debug(True)

d = tinytuya.OutletDevice(
      dev_id=DEVICEID,
      address=DEVICEIP,
      local_key=DEVICEKEY,
      version=3.3)
print(d)

print(" > Fetch Status < ")
data = d.status()
print(data)
```

**Comment by jasonacox** [comment]
Thanks @Dhruveshp

Can you run the wizard to get the local key file (devices.json)? It would be interesting to see the DPS values this device supports.

```
python -m tinytuya wizard
```

I may also  suggest try having it determine the DPS values:

```python
import tinytuya

tinytuya.set_debug(True)

d = tinytuya.OutletDevice(
      dev_id=DEVICEID,
      address=DEVICEIP,
      local_key=DEVICEKEY,
      version=3.3)
print(d)


print(" > Fetch Status < ")
data = d.status()
print(data)
```

**Comment by Dhruveshp** [comment]
this is the DPS  value 

DEBUG:status() received data=None
DEBUG:Detected dps: {'20': None, '21': None, '24': None, '25': None, '26': None}
{'20': None, '21': None, '24': None, '25': None, '26': None}
 > Fetch Status <
DEBUG:status() entry (dev_type is device22)
DEBUG:building command 10 payload=b'{"devId":"eb2f9fe6e361fd5291ffkh","uid":"eb2f9fe6e361fd5291ffkh","t":"1686286177","dps":{"20":null,"21":null,"24":null,"25":null,"26":null}}'
DEBUG:sending payload
DEBUG:payload encrypted=b'000055aa000000060000000d000000a7332e330000000000000000000000003986a7d971bbd504d29410af14c0c1a0b9eb025e43fc4f5f28a2550c8dade97f804ab5af3685534b1a6cc96ee6ae82638c009143b1ea6f65f577a881d0900108f8f98fa8020b809fd6d9370a2cb2706772b242c3e7aaf022e4715861ec43d6109e7c37d140dfc4dd7adbd39f4f885a13c51a1da537ff6120a3de5d0615118c53e378963d74055dd4f546417972928769bf894ebb0000aa55'
DEBUG:received data=b'000055aa00000000000000080000008b00000000332e33000000000000000500000001e1f56d8b8a2f1f31ac7422455d1f1e8fb4def8bb4f084d0431853079d6c13cf7bce159b786eac5067454bf626ec39732ecee9934d1bacd9909f6923b7f6c95f589b61011970878e08f53ea33549f11e285650c4b48fc064a273bb686243c600eec22c2b1d6a81bedfdee4a0b13fac1f7933ebacb0000aa55'
DEBUG:received message=TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\xe1\xf5m\x8b\x8a/\x1f1\xact"E]\x1f\x1e\x8f\xb4\xde\xf8\xbbO\x08M\x041\x850y\xd6\xc1<\xf7\xbc\xe1Y\xb7\x86\xea\xc5\x06tT\xbfbn\xc3\x972\xec\xee\x994\xd1\xba\xcd\x99\t\xf6\x92;\x7fl\x95\xf5\x89\xb6\x10\x11\x97\x08x\xe0\x8fS\xea3T\x9f\x11\xe2\x85e\x0cKH\xfc\x06J\';\xb6\x86$<`\x0e\xec"\xc2\xb1\xd6\xa8\x1b\xed\xfd\xeeJ\x0b\x13\xfa\xc1\xf7', crc=2470361803, crc_good=True, prefix=21930, iv=None)
DEBUG:raw unpacked message = TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\xe1\xf5m\x8b\x8a/\x1f1\xact"E]\x1f\x1e\x8f\xb4\xde\xf8\xbbO\x08M\x041\x850y\xd6\xc1<\xf7\xbc\xe1Y\xb7\x86\xea\xc5\x06tT\xbfbn\xc3\x972\xec\xee\x994\xd1\xba\xcd\x99\t\xf6\x92;\x7fl\x95\xf5\x89\xb6\x10\x11\x97\x08x\xe0\x8fS\xea3T\x9f\x11\xe2\x85e\x0cKH\xfc\x06J\';\xb6\x86$<`\x0e\xec"\xc2\xb1\xd6\xa8\x1b\xed\xfd\xeeJ\x0b\x13\xfa\xc1\xf7', crc=2470361803, crc_good=True, prefix=21930, iv=None)
DEBUG:decode payload=b'3.3\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\xe1\xf5m\x8b\x8a/\x1f1\xact"E]\x1f\x1e\x8f\xb4\xde\xf8\xbbO\x08M\x041\x850y\xd6\xc1<\xf7\xbc\xe1Y\xb7\x86\xea\xc5\x06tT\xbfbn\xc3\x972\xec\xee\x994\xd1\xba\xcd\x99\t\xf6\x92;\x7fl\x95\xf5\x89\xb6\x10\x11\x97\x08x\xe0\x8fS\xea3T\x9f\x11\xe2\x85e\x0cKH\xfc\x06J\';\xb6\x86$<`\x0e\xec"\xc2\xb1\xd6\xa8\x1b\xed\xfd\xeeJ\x0b\x13\xfa\xc1\xf7'
DEBUG:removing 3.x=b'\xe1\xf5m\x8b\x8a/\x1f1\xact"E]\x1f\x1e\x8f\xb4\xde\xf8\xbbO\x08M\x041\x850y\xd6\xc1<\xf7\xbc\xe1Y\xb7\x86\xea\xc5\x06tT\xbfbn\xc3\x972\xec\xee\x994\xd1\xba\xcd\x99\t\xf6\x92;\x7fl\x95\xf5\x89\xb6\x10\x11\x97\x08x\xe0\x8fS\xea3T\x9f\x11\xe2\x85e\x0cKH\xfc\x06J\';\xb6\x86$<`\x0e\xec"\xc2\xb1\xd6\xa8\x1b\xed\xfd\xeeJ\x0b\x13\xfa\xc1\xf7'
DEBUG:decrypting=b'\xe1\xf5m\x8b\x8a/\x1f1\xact"E]\x1f\x1e\x8f\xb4\xde\xf8\xbbO\x08M\x041\x850y\xd6\xc1<\xf7\xbc\xe1Y\xb7\x86\xea\xc5\x06tT\xbfbn\xc3\x972\xec\xee\x994\xd1\xba\xcd\x99\t\xf6\x92;\x7fl\x95\xf5\x89\xb6\x10\x11\x97\x08x\xe0\x8fS\xea3T\x9f\x11\xe2\x85e\x0cKH\xfc\x06J\';\xb6\x86$<`\x0e\xec"\xc2\xb1\xd6\xa8\x1b\xed\xfd\xeeJ\x0b\x13\xfa\xc1\xf7'
DEBUG:decrypted 3.x payload='{"dps":{"20":true,"21":"colour","24":"0000000003e8","25":"000e0d00002e03e802cc00000000","26":0},"t":1686286177}'
DEBUG:payload type = <class 'str'>
DEBUG:decoded results='{"dps":{"20":true,"21":"colour","24":"0000000003e8","25":"000e0d00002e03e802cc00000000","26":0},"t":1686286177}'
DEBUG:status() received data={'dps': {'20': True, '21': 'colour', '24': '0000000003e8', '25': '000e0d00002e03e802cc00000000', '26': 0}, 't': 1686286177}
{'dps': {'20': True, '21': 'colour', '24': '0000000003e8', '25': '000e0d00002e03e802cc00000000', '26': 0}, 't': 1686286177}

**Comment by Dhruveshp** [comment]
I  am able to set the value to RGB value after running the wizard.

Thank you for your support @jasonacox
