### ISSUE TITLE
How much does it cost to use tinytuya?

### ISSUE THREAD

**Issue by nscoo** [jasonacox/tinytuya#374]
Hello, I am trying to implement a smart home using tinytuya. I know that using tuya iot platform will result in billing, but I wonder if it is possible to charge using tinytuya. and i wonder what's differnce with tuya iot(cloud) platform

**Comment by jasonacox** [comment]
I'm not fully understanding, but I think you are raising the concern about Tuya's commercial products. TinyTuya is opensource and free and you can control "most" of your devices locally without using the iot platform. However, you will need to get the local keys for your devices. One way to get those is to use a free "trial" account at iot.tuya.com (see [instructions](https://github.com/jasonacox/tinytuya#setup-wizard---getting-local-keys) or PDF here: https://github.com/jasonacox/tinytuya/files/8145832/Tuya.IoT.API.Setup.pdf instructions - but make sure not to select developer or organization). Another way is to use android emulation as discussed here: https://github.com/jasonacox/tinytuya/issues/249

Once you have the local keys, you can will not need the iot platform. I hope that helps.

**Comment by nscoo** [comment]
Thank you for answer 😀
The intention of my question is that importing a local key from the tuya iot platform can be charged if a lot of traffic occurs or if the trial version expires. Is that correct?

**Comment by jasonacox** [comment]
Correct, or you will need to create a new trial account.  Most only need to get their keys once and will only need to access the iot platform when they add new devices.

**Comment by nscoo** [comment]
I want to use it for a long time without paying as much as possible. Is there any way?

**Comment by jasonacox** [comment]
I can't speak for Tuya. There is always the chance they will upgrade the devices that block us from using TinyTuya or the local keys we downloaded with the free trial accounts. I haven't seen that yet and have been using this for over 3 years.

**Comment by nscoo** [comment]
Thank you for always quick reply 😀

**Comment by jasonacox** [comment]
I will close this issue for now. Please reopen if you have more questions.
