### ISSUE TITLE
Missing New Authorization instruction for the project in Setup Wizard step

### ISSUE THREAD

**Issue by sudogitclone** [jasonacox/tinytuya#38]
Hello,

I was getting KeyError: 'result' errors when running the wizard after following the instruction to subscribe in API Products:

IMPORTANT Under "Cloud" -> select your project -> "API Management" -> "API Products" that the following API groups have status "Subscribed": Smart Home Devices Management, Authorization and Smart Home Family Management (see screenshot here)

After authorizing each API Product above to my project as described in https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#linking-a-tuya-device-with-smart-link like below

```
Click into the Product and click Subscribe
Select the free tier and Buy Now
Click back to the API Products page and select the API again
Click to the Projects tab
Click **New Authorization
Select your Project from the dropdown and click OK
```

I am able to complete the wizard successfully (note: I did not have to subscribe to Smart Home Data Service
Smart Home Scene Linkage as mentioned in the tuyapi documentation).

**Comment by jasonacox** [comment]
Thank you!!  They keep changing the UI.  I know others are having the same problem.  I'll add this to the instructions.

**Comment by sudogitclone** [comment]
@jasonacox the new authorization process I did is the same as the screenshot you posted above. Thanks for the update, I will close this issue.

**Comment by jasonacox** [comment]
Thanks again!  Do you think this describes it well?

* IMPORTANT Under "API Management" -> "API Products" and esnure the API groups have status "Subscribed": Smart Home Devices Management, Authorization and Smart Home Family Management ([see screenshot here](https://user-images.githubusercontent.com/836718/111419675-1d0d3f80-86a7-11eb-81ad-f6078ee391fe.png)) - To subscribe and authorize your Project to use these 3 API groups:
        - Click each of the API boxes
        - Click to the "Projects" tab
        - Click "**New Authorization**" Button
        - Select your Project from the dropdown and click OK ([see screenshot here](https://user-images.githubusercontent.com/836718/111578175-d5eb8100-8770-11eb-93b3-46342b1a67fa.png) )

**Comment by sudogitclone** [comment]
Yes that describes the process well enough! :+1:
