### ISSUE TITLE
Poll error

### ISSUE THREAD

**Issue by Rafahorn03** [jasonacox/tinytuya#385]
Hi,

I'm having errors when I try to poll my devices (len:22).

It works when I disconnect them from power or when I reboot my router, but some hours later, it stops working.

My devices are Tuya Smart Plugs, I have 4 and it does not work.

When I try pinging them, it does not work either.

**Comment by jasonacox** [comment]
Some devices seem to disappear from the local network after a while but they do seem to stay connected to the cloud.

A few things I would try:
* Update tinytuya to latest (`pip install --upgrade tinytuya`)
* Scan network with debug `python -m tinytuya scan -d`
* See if the devices still ping after they disappear (eg.. `ping 10.10.20.30`)

**Comment by Rafahorn03** [comment]
I tried it. 
As you said, they disappear, when I ping them they don't response, but I can see them connected to my router and tuya app still working.

**Comment by jasonacox** [comment]
Do you have other Tuya devices that don't do this?

Also, if it is related to a bug we have seen with some Tuya devices, the arp broadcasts stop working.  If your router show the MAC address for the Tuya device, you can attempt to do a forced arp mapping on the host running tinytuya:

```
# set the IP to MAC mapping
sudo arp -s 192.168.31.5  0:1e:58:b1:64:40

# test it
ping 192.168.31.5
```

**Comment by Rafahorn03** [comment]
It is working with that. Thanks.
