### ISSUE TITLE
Unable to get local key for v3.4 device - LSC Smart Connect ceiling lamp

### ISSUE THREAD

**Issue by jeanpaul1977** [jasonacox/tinytuya#398]
Hi,

I'm using TinyTuya v1.12.10; I have multiple v3.3 LSC lamps successfully connect and I'm able to control them.
As of today I bought a new LSC ceiling lamp; it's on v3.4 while all other devices are on v3.3

When I run "python3 -m tinytuya scan" I get:

```
'10': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000', '101': True}
Unknown v3.4 Device   Product ID = key8u5XXXXXXX5jw  [Valid Broadcast]:
    Address = 192.168.XXX.XXX   Device ID = bfac9eXXXXXXXX2815agts (len:22)  Local Key =   Version = 3.4  Type = default, MAC = 
    No Stats for 192.168.XXX.XXX: DEVICE KEY required to poll for status

```

The snapshot.json contains (snippet for that device):

```
        {
            "id": "bfac9eXXXXXXXX2815agts",
            "ip": "192.168.XXX.XXX",
            "active": 2,
            "encrypt": true,
            "productKey": "key8XXXXXXXXu5jw",
            "token": true,
            "wf_cfg": true,
            "name": "",
            "key": "",
            "mac": "",
            "ability": 0,
            "dev_type": "default",
            "origin": "broadcast",
            "ver": "3.4"
        },

```
Any idea's on how to get this lamp connected?

**Comment by jeanpaul1977** [comment]
I managed to connect the lamp.

First time I registered the lamp using the "LSC smartconnect" app. For some reason (unknown to me) that resulted in the the situation above.
I noticed I had the "Smart life" app on my phone as well and tried to register the lamp via that app. Now all works!

**Comment by jasonacox** [comment]
Thanks @jeanpaul1977 - You are correct.  The official Tuya "Smart Life" app is required to be able to get local control. I don't know what the third party apps are doing.

**Comment by hamed-jamali-software** [comment]
I have this error
Unknown v3.4 Device   Product ID = key8u54q9dtru5jw  [Valid Broadcast]:
    Address = 192.168.43.16   Device ID = bf5e9d230926e6b12fojsu (len:22)  Local Key =   Version = 3.4  Type = default, MAC = 
    No Stats for 192.168.43.16: DEVICE KEY required to poll for status
