### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by PHunHouse** [jasonacox/tinytuya#4]
Good evening Mr. Cox,

I came across this issue when testing devices on v3.3:
![image](https://user-images.githubusercontent.com/44043484/99481585-6d0e0c80-2928-11eb-9111-6fc0b7ba7796.png)

I am testing on a Windows10 x64-19041; Python 3.8; PyCharm.

Any insight would be greatly appreciated.
I am new to the developing scene. Please, pardon my ignorance.

**Comment by jasonacox** [comment]
Hi!  Can you make sure you are using the latest version of **tinytuya** and provide the output of: 

```
python -m pip install --upgrade tinytuya
python -m tinytuya
```

**Comment by PHunHouse** [comment]
![image](https://user-images.githubusercontent.com/44043484/99485845-47d1cc00-2931-11eb-9160-56de3d723674.png)

C:\Users\rafae\PycharmProjects\tinytuya>python -m tinytuya
TinyTuya (Tuya device scanner) [1.0.4]

Scanning on UDP ports 6666 and 6667 for devices (15 retries)...

FOUND Device [Valid payload]: 192.168.20.226
    ID = 08381200807d3a7d6f80, product = 4bVOiYN0zdh6vTYq, Version = 3.1
    Status = {'devId': '08381200807d3a7d6f80', 'dps': {'1': False, '11': 0, '101': 'QVA=', '102': 'QVA=', '103': 'QVA='}}
FOUND Device [Valid payload]: 192.168.20.222
    ID = 08381200cc50e3c23933, product = 4bVOiYN0zdh6vTYq, Version = 3.1
    Status = {'devId': '08381200cc50e3c23933', 'dps': {'1': False, '11': 0, '101': 'QVA=', '102': 'QVA=', '103': 'QVA='}}
FOUND Device [Valid payload]: 192.168.20.231
    ID = 800061668caab500846a, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.234
    ID = 8000616698f4abfff8f5, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.247
    ID = 8143584140f5203747a4, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.241
    ID = 8143584140f52036c2c1, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.233
    ID = 8143584140f52036c242, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.111
    ID = 5504517310521ceef72f, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.237
    ID = 24887008f4cfa2c2ddbe, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.238
    ID = 24887008d8bfc0ded918, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.253
    ID = 24887008d8bfc0deda71, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.220
    ID = 8833761084cca88ecc27, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.252
    ID = 24887008d8bfc0d116a9, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.251
    ID = 8833761084cca88edf54, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.120
    ID = eb837149a9dd048d3egehw, product = keygg897krt5kk4t, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.108
    ID = 5504517310521ceeae53, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.240
    ID = 8833761084cca88eec5a, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.248
    ID = 8833761084cca88f5214, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.223
    ID = 02067036b4e62d5c7ef9, product = heeU2AWVxpxfqP6D, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.118
    ID = 800061668caab5008284, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.109
    ID = 5504517310521cef3957, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.221
    ID = 02067036ecfabc2d6f04, product = heeU2AWVxpxfqP6D, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.242
    ID = 8143584140f5203624ae, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.5
    ID = eb5bf860df61f8dea0hwfd, product = keygg897krt5kk4t, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.245
    ID = 8000616698f4abfff95e, product = key4fv3xs8twchhy, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.224
    ID = 02230402ecfabc2d55d9, product = heeU2AWVxpxfqP6D, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.110
    ID = 5504517310521cef3cbf, product = 5abhrka6ejfr0hvx, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.225
    ID = 02230402ecfabc2d5136, product = heeU2AWVxpxfqP6D, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.239
    ID = 8143584140f52036bda3, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.20.244
    ID = 8143584140f520363a10, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status

Scan Complete!  Found 30 devices.



> Hi! Can you make sure you are using the latest version of **tinytuya** and provide the output of:
> 
> ```
> python -m pip install --upgrade tinytuya
> python -m tinytuya
> ```

**Comment by jasonacox** [comment]
Thank you!  

Which of these devices are you trying to poll?  Also, can you share the code of your `testingSocket.py`?   
Do not include your key.

**Comment by PHunHouse** [comment]
> Thank you!
> 
> Which of these devices are you trying to poll? Also, can you share the code of your `testingSocket.py`?
> Do not include your key.


Polling:
![image](https://user-images.githubusercontent.com/44043484/99486981-4c977f80-2933-11eb-819b-cec7b50c8dee.png)

Code:

`import tinytuya

deviceID = "eb837149a9dd048d3egehw"
ipAddress = "192.168.20.120"
localKey = "REDACTED"

d = tinytuya.OutletDevice(deviceID, ipAddress, local_key=localKey)
d.set_version(3.3)
data = d.status()  # NOTE this does NOT require a valid key for version 3.1

# Show status of first controlled switch on device
print('Dictionary %r' % data)
print('State (bool, true is ON) %r' % data['dps']['1'])
'''
# Toggle switch state
switch_state = data['dps']['1']
data = d.set_status(not switch_state)  # This requires a valid key
if data:
    print('set_status() result %r' % data)
'''
'''# On a switch that has 4 controllable ports, turn the fourth OFF (1 is the first)
data = d.set_status(False, 4)
if data:
    print('set_status() result %r' % data)
    print('set_status() extra %r' % data[20:-8])
'''
`

I commented out the bottom for troubleshooting purposes, my good sir.

**Comment by jasonacox** [comment]
I see - that device has an ID of 22 characters and for some reason, they can behave differently from the standard devices.  TinyTuya has a "device22" type that you can use but also requires setting dps values you want to poll (which also seem to vary for these device types).  

Try something like this:

```python
import tinytuya

deviceID = "eb837149a9dd048d3egehw"
ipAddress = "192.168.20.120"
localKey = "REDACTED"

d = tinytuya.OutletDevice(deviceID, ipAddress, local_key=localKey, 'device22')
d.set_version(3.3)
d.set_dpsUsed({"1": None})
data = d.status() 

print('Dictionary %r' % data)
print('State (bool, true is ON) %r' % data['dps']['1'])
```

**Comment by PHunHouse** [comment]
> I see - that device has an ID of 22 characters and for some reason, they can behave differently from the standard devices. TinyTuya has a "device22" type that you can use but also requires setting dps values you want to poll (which also seem to vary for these device types).
> 
> Try something like this:
> 
> ```python
> import tinytuya
> 
> deviceID = "eb837149a9dd048d3egehw"
> ipAddress = "192.168.20.120"
> localKey = "REDACTED"
> 
> d = tinytuya.OutletDevice(deviceID, ipAddress, local_key=localKey, 'device22')
> d.set_version(3.3)
> d.set_dpsUsed({"1": None})
> data = d.status() 
> 
> print('Dictionary %r' % data)
> print('State (bool, true is ON) %r' % data['dps']['1'])
> ```

![image](https://user-images.githubusercontent.com/44043484/99489788-80c06f80-2936-11eb-84ed-bc4839f76d75.png)

![image](https://user-images.githubusercontent.com/44043484/99489799-87e77d80-2936-11eb-8a8c-4d2eb721da9a.png)

**Comment by jasonacox** [comment]
Sorry I didn't notice your local_key setup.  We need to make sure that all positional arguments come before keyword arguments.  Remove the `local_key=localKey` you have and replace it with just `localKey`.

```
import tinytuya

deviceID = "eb837149a9dd048d3egehw"
ipAddress = "192.168.20.120"
localKey = "REDACTED"

d = tinytuya.OutletDevice(deviceID, ipAddress, local_key, 'device22')
d.set_version(3.3)
d.set_dpsUsed({"1": None})
data = d.status() 

print('Dictionary %r' % data)
print('State (bool, true is ON) %r' % data['dps']['1'])
```

**Comment by PHunHouse** [comment]
> Sorry I didn't notice your local_key setup. We need to make sure that all positional arguments come before keyword arguments. Remove the `local_key=localKey` you have and replace it with just `localKey`.
> 
> ```
> import tinytuya
> 
> deviceID = "eb837149a9dd048d3egehw"
> ipAddress = "192.168.20.120"
> localKey = "REDACTED"
> 
> d = tinytuya.OutletDevice(deviceID, ipAddress, local_key, 'device22')
> d.set_version(3.3)
> d.set_dpsUsed({"1": None})
> data = d.status() 
> 
> print('Dictionary %r' % data)
> print('State (bool, true is ON) %r' % data['dps']['1'])
> ```

![image](https://user-images.githubusercontent.com/44043484/99546472-6e6d2280-2984-11eb-92ec-914516672c57.png)

Mr. Cox,

It is working correctly.

With the changes you mentioned, I am able to send commands to the device.

**Comment by PHunHouse** [comment]
Mr. Cox, 
Can you help me understand the output here:
![image](https://user-images.githubusercontent.com/44043484/99614698-02bca100-29e8-11eb-9a24-9ea15e3aadfd.png)

**Comment by jasonacox** [comment]
I assume you mean the "set_status()" response.  That is the encrypted payload respond back from the device when you change the state of the device.  I haven't had time to do anything with that to see if it is even useful.  It isn't needed to perform functions on your devices or read status.  If you have time to figure out how to decrypt it, I would love to add that logic to the set_status() function.

**Comment by ShaneSpina** [comment]
Hi guys.. I've just started down this road today.. I I've gotten tinytuya to poll devices but when I run the wizard I get these errors:

Traceback (most recent call last):
  File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya\__main__.py", line 48, in <module>
    tinytuya.wizard(color)
  File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya\__init__.py", line 1442, in wizard
    token = response_dict['result']['access_token']
KeyError: 'result'

The tinytuya.json file is created and the file looks correct but I do not get an output file with my device keys (devices.json)..

**Comment by jasonacox** [comment]
Hi Shane, this means the wizard is unable to use your credentials to get an authorization token from iot.tuya.com.  I recommend you check your apiKey, apiSecret and apiRegion values to ensure they are correct (should be stored in the tinytuya.json file).

> On Dec 6, 2020, at 11:49 AM, ShaneSpina wrote:
> 
> Hi guys.. I've just started down this road today.. I I've gotten tinytuya to poll devices but when I run the wizard I get these errors:
> Traceback (most recent call last):
> File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
> return run_code(code, main_globals, None,
> File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in run_code
> exec(code, run_globals)
> File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya_main.py", line 48, in 
> tinytuya.wizard(color)
> File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya_init.py", line 1442, in wizard
> token = response_dict['result']['access_token']
> KeyError: 'result'
> 
> The tinytuya.json file is created and the file looks correct but I do not get an output file with my device keys (devices.json)..
>

**Comment by ShaneSpina** [comment]
> Hi Shane, this means the wizard is unable to use your credentials to get an authorization token from iot.tuya.com. I recommend you check your apiKey, apiSecret and apiRegion values to ensure they are correct (should be stored in the tinytuya.json file).
> […](#)
> On Dec 6, 2020, at 11:49 AM, ShaneSpina wrote: Hi guys.. I've just started down this road today.. I I've gotten tinytuya to poll devices but when I run the wizard I get these errors: Traceback (most recent call last): File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main return run_code(code, main_globals, None, File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in run_code exec(code, run_globals) File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya_main.py", line 48, in tinytuya.wizard(color) File "C:\Users\shane\AppData\Local\Programs\Python\Python39\lib\site-packages\tinytuya_init.py", line 1442, in wizard token = response_dict['result']['access_token'] KeyError: 'result' The tinytuya.json file is created and the file looks correct but I do not get an output file with my device keys (devices.json)..

Sorry yes, I figured it out and deleted my question :) but thanks for replying and awesome tool!

**Comment by burgas1** [comment]
Hi
I have similar problem with a bulb. tinytuya on RPi Zero. Python 3.7.3
3 equal bulbs. 2 of them I can read just fine. 

```
TinyTuya (Tuya device scanner) [1.1.3]

Scanning on UDP ports 6666 and 6667 for devices (15 retries)...

3.1 Device Found [Valid payload]: 192.168.0.115
    ID = 37800275840d8e54d1d2, Product ID = keyneruwsdethu7u, Version = 3.1
    Status: {'1': False, '9': 0, '18': 0, '19': 0, '20': 2344, '21': 1, '22': 748, '23': 32838, '24': 22222, '25': 935}
3.3 Device Found [Valid payload]: 192.168.0.109
    ID = 8052770184f3ebeec5b1, Product ID = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
3.3 Device Found [Valid payload]: 192.168.0.189
    ID = 01147546600194dd1765, Product ID = keyjcr45yfptp7h7, Version = 3.3
    No Stats - Device Key required to poll for status
3.3 Device Found [Valid payload]: 192.168.0.161
    ID = 80527701ecfabc47dfac, Product ID = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
3.3 Device Found [Valid payload]: 192.168.0.138
    ID = 8052770184f3ebf633b5, Product ID = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
                    
Scan Complete!  Found 5 devices.
```
```
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    get_tuya_data_test('80527701ecfabc47dfac', '192.168.0.161', '6af642384da9f2d1')
  File "/root/tee/tee/data.py", line 262, in get_tuya_data_test
    d.set_version(3.3)
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/__init__.py", line 891, in set_version
    status = self.status()
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/__init__.py", line 589, in status
    result = json.loads(result)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
def get_tuya_data_test(tuya_id, ip_addr, tuya_key):
    
        d = tinytuya.BulbDevice(tuya_id, ip_addr, tuya_key)
        d.set_version(3.3)
        data = d.status()
        print(data)
```

**Comment by jasonacox** [comment]
This generally indicates that the tuya_key you are using is wrong.  Can you confirm that the key retrieved by `python -m tinytuya wizard` is what you are using in your test code? 

Keep in mind that if you re-pair a device, it will generate a new local key and you will need to run the wizard again to get it.

**Comment by jasonacox** [comment]
Additional error checking and retry logic has been added to the TinyTuya v1.2.x version.  It may help with these error or at least provide more information on what is going on.  I recommend you upgrade and try again.

```
pip install --upgrade tinytuya
```
