### ISSUE TITLE
Cover Control time

### ISSUE THREAD

**Issue by mupsje** [jasonacox/tinytuya#40]
Hi, After log time I finaly found this great py....

I have bought the [Loratap blinds cover](https://nl.aliexpress.com/item/33052311020.html?spm=a2g0o.productlist.0.0.1fce6edfWhEofY&algo_pvid=4a8c0398-bc03-4c6a-8910-49a94bf9925e&algo_expid=4a8c0398-bc03-4c6a-8910-49a94bf9925e-0&btsid=0b0a050116172030867828749e1023&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)

[https://nl.aliexpress.com/item/33052311020.html?spm=a2g0o.productlist.0.0.1fce6edfWhEofY&algo_pvid=4a8c0398-bc03-4c6a-8910-49a94bf9925e&algo_expid=4a8c0398-bc03-4c6a-8910-49a94bf9925e-0&btsid=0b0a050116172030867828749e1023&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_](url)

And when i pull the status I get

Dictionary {u'dps': {u'1': u'stop', u'3': 15, u'2': u'forward'}}

I made 3 scripts...  open/stop/close
e.g.
import tinytuya
  
d = tinytuya.CoverDevice('#####', '######', '#######')
d.set_version(3.3)  
data = d.status()
#print(data)
  
d.open_cover(switch=1)

# Show status of first controlled switch on device
#print('Dictionary %r' % data)
print('State %r' % data['dps']['1']) 
print('State %r' % data['dps']['2'])
print('State %r' % data['dps']['3']) 

Now comes the parts I want to controll the u3: 15
This the time that the cover(shutter) rolls....
I did allot of commands but i don't get the right one..

let's say I want to get to 21 value.....
please help..
thanks

Remco aka mupsje

**Comment by jasonacox** [comment]
You can use the set_value() function to change each of the DPS values.  Here is an example:

```python
import tinytuya

d = tinytuya.CoverDevice('#####', '######', '#######')
d.set_version(3.3)

# Get status
data = d.status()
print('Status: %r' % data)

# Change DPS 3 to value 21
d.set_value(3, 21) 

# Get status
data = d.status()
print('Status: %r' % data)


```

**Comment by jasonacox** [comment]
I'm closing this for now.  Please reopen if the issues still exists.
