### ISSUE TITLE
There may be a decoding problem

### ISSUE THREAD

**Issue by garry0garry** [jasonacox/tinytuya#410]
One device out of three shows an incorrect local key:
`Local Key = ts<+N?_PN(_EDu+m`
What can you do to find the correct key?

**Comment by garry0garry** [comment]
The IoT website has the same information.

**Comment by uzlonewolf** [comment]
What makes you think it's incorrect?  They switched to including symbols a few months ago https://github.com/jasonacox/tinytuya/discussions/341
