### ISSUE TITLE
Thermostatdevice gives warning message for manual mode

### ISSUE THREAD

**Issue by erdebe** [jasonacox/tinytuya#427]
Received value 'manual' for key '2'/'mode' not in enum list ['auto', 'cool', 'heat', 'emergencyheat', 'off'] !  Perhaps enum list needs to be updated?

This is the message I get, when executing

dps = tstatdev.status()['dps']

Note that I have a wired thermostat with product name "ETOP-HT"

Anyway : thanks for the great interface to tuya AND the great documentation!
Works like a charm!

Groeten,
Ronald de Bruijn

**Comment by erdebe** [comment]
I tried Device(), had to add 
version=3.3
The output for me is the same as with the ThermostatDevice, without warning message. Fine for me. I only want to perform read only polling. 
In the Tuya app setup, I saw that I have only read permissions, good enough for me.

**Comment by uzlonewolf** [comment]
Since it sounds like Device() is good enough I'm going to go ahead and close this.  Feel free to re-open it if you think we should create/modify a special device type specifically for this thermostat.
