### ISSUE TITLE
Repository structure for v1.13.1 is not compliant

### ISSUE THREAD

**Issue by rahimpaleri** [jasonacox/tinytuya#428]
<Integration jasonacox/tinytuya> Repository structure for v1.13.1 is not compliant

**Comment by uzlonewolf** [comment]
Compliant with what?  Which part isn't compliant?  I don't see any failures in https://github.com/jasonacox/tinytuya/actions

**Comment by jasonacox** [comment]
Thanks @rahimpaleri  - as @uzlonewolf mentions, we aren't aware of any gaps.  Can you provide more specifics?

**Comment by uzlonewolf** [comment]
As it's been 2 weeks without clarification I'm gonna close this one out as invalid.  @rahimpaleri if you can provide more clarification then feel free to re-open it.

**Comment by uzlonewolf** [comment]
It seems this is the error you get when you try to install tinytuya as a HomeAssistant module https://github.com/PlusPlus-ua/ha_tuya_ble/issues/87#issuecomment-1869381700  I'm keeping it closed as invalid since tinytuya is not a HA module.
