### ISSUE TITLE
Strange data on dp 18

### ISSUE THREAD

**Issue by popokio** [jasonacox/tinytuya#43]
Hello, I'm completely new in smart home devices but i'm running very fast and set multiple devices that runs ok. 
Maybe i've lost something during this fast way but i cannot read data from my new  wattmeter .  I can read from other plugs but i would like to use a din mount device.
this is what comes out from the status:
{'dps': {'1': 1277, '10': 0, '16': True, '18': '111111111111'}}
1277 is the total power consumption (12.77Kwh) 
16: true is the switch on or off
the main info that i needed was the current, active power, and voltage (that are readable on smartlife app) but does not appear here.     there is only that 18: 1111111111 
Have you got any suggestion.
the device is https://www.amazon.it/gp/product/B07TJS27D6/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1
All the other i can see on italian amazon seem to be the same product with different label....  have you got any way to make it work or a suggestion on an alternative device working with tinytuya?
Thank you

**Comment by jasonacox** [comment]
Hi @popokio - You are correct, it does not seem that you are getting all of the DPS index values in the status response.  It may be sending only those index values that are updating.  You can try something like this to see all the debug data:

```python
import tinytuya

tinytuya.set_debug(True)  # Sets debug output - use tinytuya.set_debug(True,False) for non-ANSI color terminal

d = tinytuya.OutletDevice('DEVICEID', 'DEVICEIP', 'DEVICEKEY')
d.set_version(3.3)
print(" > Reading Status < ")
data = d.status()
print(data)
```

You can also try to set up a loop to see what status the device is sending over time:

```python
import tinytuya

# tinytuya.set_debug(True)

d = tinytuya.OutletDevice('DEVICEID', 'DEVICEIP', 'DEVICEKEY')
d.set_version(3.3)
d.set_socketPersistent(True)

print(" > Send Request for Status < ")
payload = d.generate_payload(tinytuya.DP_QUERY)
d.send(payload)

while(True):
    # See if any data is available
    data = d.receive()
    print('Received Payload: %r' % data)

    # Send keyalive heartbeat
    print(" > Send Heartbeat Ping < ")
    payload = d.generate_payload(tinytuya.HEART_BEAT)
    d.send(payload)
```
