### ISSUE TITLE
Dark Reader browser extension prevents QR code from scanning

### ISSUE THREAD

**Issue by Osprey00** [jasonacox/tinytuya#463]
When following the TinyTuya installation instructions and getting to the "Add to Tuya Account" step, the QR code on the Tuya website won't scan if you have the Dark Reader browser extension enabled. The simple fix is to temporarily turn it off so that you can scan the code, but I and others (link: https://github.com/codetheweb/tuyapi/issues/515) pulled our hair out until we discovered it.

This is just a suggestion to maybe add a note about this somewhere in the TinyTuya installation instructions to help prevent others from pulling their hair out over the issue.

**Comment by uzlonewolf** [comment]
Really?  Shutting DR off was the first thing I did when mine wouldn't scan.

**Comment by jasonacox** [comment]
Thanks @Osprey00 !
