### ISSUE TITLE
Valve controller

### ISSUE THREAD

**Issue by fmarzocca** [jasonacox/tinytuya#473]
Hi,

I have a valve controller which is connected to a Tuya gateway via BT. The valve controller has no IP. How can I handle it with tinytuya?

Thanks

**Comment by jasonacox** [comment]
Hi @fmarzocca  - You control the valve through the gateway.  Here is an example:

https://github.com/jasonacox/tinytuya/blob/master/examples/zigbee_gateway.py

```python
gw = tinytuya.Device( 'eb...4', address=None, local_key='aabbccddeeffgghh', persist=True, version=3.3 )

print( 'GW IP found:', gw.address )

# configure one or more children.  Every dev_id must be unique!
#   cid is the "node_id" from devices.json
valve = tinytuya.OutletDevice( 'eb14...w', cid='0011223344556601', parent=gw )

print(valve.status())
```

**Comment by fmarzocca** [comment]
Cool! Thank you!
