### ISSUE TITLE
requirements.txt is missing pyaes

### ISSUE THREAD

**Issue by Poil** [jasonacox/tinytuya#474]
Hi,

It looks like requirements.txt is missing pyaes as a new requirement ?

Best regards

**Comment by uzlonewolf** [comment]
Hi @Poil !

pyaes is not a requirement.  TinyTuya supports 3 different crypto libraries and will use whichever one you have installed.  pyca/cryptography is recommended and listed in requirements.txt, but if it's not found then PyCryptodome or pyaes can also be used.

**Comment by uzlonewolf** [comment]
pyaes is actually not recommended as it does not support AES-GCM which is required for v3.5 devices.

**Comment by Poil** [comment]
I've uninstalled pyaes he is no more asking for it

**Comment by uzlonewolf** [comment]
What was the error message?  It shouldn't say anything about pyaes if it finds cryptography.
