### ISSUE TITLE
Set Scene Not Doing Anything

### ISSUE THREAD

**Issue by LightSlashM** [jasonacox/tinytuya#48]
I have been trying to get my bulb to use one of the scenes but nothing appears to happen on my bulb when I run the code. Are my bulbs just not compatible?

```
import tinytuya

d = tinytuya.BulbDevice('XXXX', 'XXXX', 'XXXX')
d.set_version(3.3)
data = d.status()

d.set_mode('scene')
d.set_scene(3)
```

**Comment by jasonacox** [comment]
It seems that for many Tuya version 3.3 devices, you need to specify the sequence (string of values) you want to use for the scene via DPS index 25.  See DPS details here: https://github.com/jasonacox/tinytuya#version-33---light-type-rgb 

The scene is a string value in that case and the set_scene() function won't work.  For a feature request, I need to update `TinyTuya` to detect and allow string data for those devices.  This would be one example/workaround that should work:

```python
import tinytuya

d = tinytuya.BulbDevice('XXXX', 'XXXX', 'XXXX')
d.set_version(3.3)
data = d.status()

d.set_mode('scene')

# Example: Color rotation mode
d.set_value(25, '07464602000003e803e800000000464602007803e803e80000000046460200f003e803e800000000464602003d03e803e80000000046460200ae03e803e800000000464602011303e803e800000000')

# Example: Read scene
# d.set_value(25, '010e0d0000000000000003e803e8')

```

If you want to see what scenes your bulb has (and grab the string so you can use yourself), run this script and then use the *SmartLife* app to change between the scenes.  You will see the status updates come back with the different index 25 values.

```python
# TinyTuya Example
# -*- coding: utf-8 -*-
"""
 TinyTuya - Example showing async persistent connection to device with
 continual loop watching for device updates.

 Author: Jason A. Cox
 For more information see https://github.com/jasonacox/tinytuya

"""
import tinytuya

d = tinytuya.OutletDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)

print(" > Send Request for Status < ")
payload = d.generate_payload(tinytuya.DP_QUERY)
d.send(payload)

print(" > Begin Monitor Loop <")
while(True):
    # See if any data is available
    data = d.receive()
    print('Received Payload: %r' % data)

    # Send keyalive heartbeat
    print(" > Send Heartbeat Ping < ")
    payload = d.generate_payload(tinytuya.HEART_BEAT)
    d.send(payload)
```

**Comment by LightSlashM** [comment]
Thank you so much for the help!
