### ISSUE TITLE
Failed: No response

### ISSUE THREAD

**Issue by tr1ckz** [jasonacox/tinytuya#484]
Hello,

I recently stumbled upon tuya-local and tinytuya and have been trying to add my Diivoo Smart Water Timer For Garden Hose to tuya-local. The suggestion on their wiki is to use tinytuya to grab the ids and other information from the device, which I successfully did. But I'm encountering an issue on adding it to tuya-local as well as polling from tinytuya.
I keep getting Failed: No Reponse, but the device is pingable and reachable otherwise.. Any ideas?
Thanks for the solution, great work on it!

![image](https://github.com/jasonacox/tinytuya/assets/48994713/3ae565fd-e780-486c-a05f-5d82cc93746a)

**Comment by jasonacox** [comment]
Hi @tr1ckz - some thoughts:
* If this is a battery powered device, it will not respond to polling. To save power, battery powered Tuya devices disable local access except for brief moments when they connect to the cloud to send updates or get state changes.
* If this is a device that requires a "gateway" (noticed the name) you will need to connect to it using the gateway parent/child method (see https://github.com/jasonacox/tinytuya/blob/master/examples/zigbee_gateway.py example).
* Power cycle device - We see some Tuya devices that get into a bad state, will only communicate with the Tuya Cloud and provide limited local access, but a power cycle often fixe them.
* Check your local key - If you re-paired your device you will need to get a local key. The `python -m tinytuya wizard` will help fetch the local key from the Tuya Cloud again (I assume you already did this and have a `devices.json` file).

**Comment by tr1ckz** [comment]
Thanks for the quick response @jasonacox. I kept trying to powercycle the hub... but for whatever reason never thought about powercycling the actual wireless unit too, that did the trick!
Thanks for everything!
