### ISSUE TITLE
relax requirement for netifaces

### ISSUE THREAD

**Issue by rdenham** [jasonacox/tinytuya#522]
Recently a change was made to make netifaces a dependency. I've got some issues installing netifaces on my chromebook, and since I don't need the scanning part there, I'm ok if I don't have it.

I _think_ you've written the code in a way that means the package is still functional without netifaces, I can see:

```python
try:
    import netifaces # pylint: disable=E0401
    NETIFLIBS = True
except ImportError:
    NETIFLIBS = False
```

in `scanner.py` anyway. So I was wondering if you'd consider making `netifaces` and extra dependency. So users could install it without needing netifcases, something like:

```sh
pip install tinytuya # wouldn't have netifaces

pip install tinytuya[netiface] # if you need it.
```

Probably would have been nicer the othe way around, so users could opt out of netifiaces, while the default would be to include it, but I'm not sure pip has an opt-out approach, just an opt in one.

**Comment by uzlonewolf** [comment]
Yeah, I keep going back and forth on it being a hard requirement.  It's basically a requirement on multi-interface machines, but I'm not sure how many people actually have multi-interface machines.  For now I have removed it in #519.  Let's see what @jasonacox thinks.

**Comment by jasonacox** [comment]
I agree. Reducing the dependencies is a good move. Thanks @uzlonewolf and @rdenham - let's get that merged and released as a minor update.
