### ISSUE TITLE
Cannot get current and power -data from new version of power plug

### ISSUE THREAD

**Issue by jarsiv** [jasonacox/tinytuya#534]
I have previously six power plugs, and I'm polling those manually.

I bought couple new power plugs and these are little bit newer versions with last state -memory function.
I linked these with Smart Life app to my account and got the keys. First notice was that there are much more DP ID's with these new socket. Ok, that is not the issue. Issue is that for example power and current are all the time as value 0. Seems that only "Switch" is changing after pressing the power button on socket.

Same thing with from calling from cloud.

Strangest thing was that while testing local calling and looking the data what I got, I got values while I was looking the power consumptions from Smart Life -app from phone ?!? I think usually the app should be closed that local polling is working at all.

This is the data I got:` {'dps': {'1': True, '9': 0, '17': 12, '18': 0, '19': 0, '20': 2386, '21': 1, '22': 563, '23': 24975, '24': 13594, '25': 3060, '26': 0, '38': 'memory'}}`

So power and current are "0"

What I'm missing with this new version of socket?

Is the device now with 22 character IDs..? Well I tried this:
import tinytuya

```
a = tinytuya.OutletDevice("bfcb8bcf586201cc2f2nxx", "192.168.2.xx", "y)0n;hp@'o*e/*xx", "device22")
a.set_version(3.3)
a.set_dpsUsed({"1": None})  # This needs to be a datapoint available on the device
data =  a.status()
print(data)
```
and as result got only this:
`{'dps': {'1': True}, 'type': 'query', 't': 1725608632}`

EDIT: triple checked that Smart life -app need to be open on phone that current and power will be updated. How to solve this issue?

**Comment by uzlonewolf** [comment]
Have you tried calling `.updatedps(...)`?

https://github.com/jasonacox/tinytuya/blob/7d8922ee096b5519018fa068ffb698ef43a213cc/examples/monitor.py#L39-L43

**Comment by jarsiv** [comment]
Thank you, that was the case. DSP Update was needed
