### ISSUE TITLE
Reconnecting to my lamp doesn't work after the computer is restarted, unless I physically turn the lamp on and off

### ISSUE THREAD

**Issue by justkanji** [jasonacox/tinytuya#552]
I wrote a script that lets me control my lamp via keyboard presses, and from the system tray on windows (to change colors, turn it on and off etc.), Everything works as it should but-
The issue is that when my pc goes to sleep, or it is restarted - restarting the script doesn't seem to connect to the lamp, unless I turn the lamp physically off, then back on and only then "d = tinytuya.BulbDevice('DEVICE_ID_HERE', 'IP_ADDRESS_HERE', 'LOCAL_KEY_HERE')"
works.
I am pretty sure this is user error but I don't really understand what's going wrong, some timeout probably.

**Comment by justkanji** [comment]
`from pystray import Icon, Menu, MenuItem
from PIL import Image, ImageDraw
from keyboard import on_press_key, unhook_all
from tinytuya import BulbDevice

DEVICE_ID = 
DEVICE_IP = 
LOCAL_KEY =

class SmartLamp:
    def __init__(self, device_id, device_ip, local_key):
        self.device_id = device_id
        self.device_ip = device_ip
        self.local_key = local_key
        self.device = None
        self.is_on = False  # Boolean for lamp status (on/off)
        self.is_white_mode = True  # Boolean for mode (white/colour)
        self.tray_icon = None

    @staticmethod
    def mode_to_color(is_on, is_white_mode, is_connecting=False):
        """Map boolean status to colors."""
        if is_connecting:
            return (128, 128, 128, 255)  # Gray when connecting
        if not is_on:
            return (0, 0, 0, 255)  # Black when off
        return (255, 255, 255, 255) if is_white_mode else (0, 0, 255, 255)  # White or blue

    @staticmethod
    def create_image(color):
        """Create an image with the specified RGBA color."""
        width, height = 16, 16
        image = Image.new('RGBA', (width, height), (0, 0, 0, 0))  # Transparent background
        draw = ImageDraw.Draw(image)
        draw.rectangle(
            (width // 4, height // 4, 3 * width // 4, 3 * height // 4),
            fill=color
        )
        return image

    def connect_to_device(self):
        """Connect to the Tuya device."""
        self.update_tray_icon(is_connecting=True)  # Update icon to gray while connecting
        try:
            d = BulbDevice(self.device_id, self.device_ip, self.local_key)
            d.set_version(3.5)
            self.device = d
            self.initialize_mode()  # Initialize mode after connecting
        except Exception as e:
            print(f"Failed to connect to the device: {e}")
            self.device = None
            self.update_tray_icon()  # Update icon back after failed connection

    def initialize_mode(self):
        """Initialize the lamp mode after connection."""
        if self.device:
            # Retrieve the current state of the device
            state = self.device.status()  # Get the current state from the device
            self.is_on = state.get('dps').get('20', False)  # Assuming '20' is the power status
            self.is_white_mode = state.get('dps').get('21', 'white') == 'white'  # Assuming '21' is the mode
            self.update_tray_icon()

    def update_tray_icon(self, is_connecting=False):
        """Update the tray icon based on the current lamp state."""
        if self.tray_icon:
            color = self.mode_to_color(self.is_on, self.is_white_mode, is_connecting)
            self.tray_icon.icon = self.create_image(color)

    def toggle_power(self):
        """Toggle the lamp's power."""
        if self.device:
            self.is_on = not self.is_on  # Switch power state
            if self.is_on:
                self.device.turn_on()
            else:
                self.device.turn_off()
            self.update_tray_icon()
        else:
            print("Device not connected.")

    def toggle_mode(self):
        """Toggle the lamp's mode between white and color."""
        if self.device and self.is_on:
            self.is_white_mode = not self.is_white_mode  # Switch mode
            new_mode = 'white' if self.is_white_mode else 'colour'
            self.device.set_mode(new_mode)
            self.update_tray_icon()
        else:
            print("Device not connected or is off.")

    def on_key_event(self, event):
        """Handle key events."""
        if event.name == 'pause':
            self.toggle_power()
        elif event.scan_code == 70:  # Scroll Lock key scan code
            self.toggle_mode()

    def exit_action(self):
        """Stop the icon and clean up."""
        if self.tray_icon:
            self.tray_icon.visible = False
            self.tray_icon.stop()
        unhook_all()  # Remove all keyboard hooks

    def setup_tray_icon(self, icon):
        """Setup the tray icon and manage state."""
        self.update_tray_icon()
        icon.visible = True
        self.connect_to_device()  # Start the connection after setting up the tray icon

    def init_tray_icon(self):
        """Initialize the system tray icon."""
        self.tray_icon = Icon('name', self.create_image(self.mode_to_color(self.is_on, self.is_white_mode)), 'Smart Lamp Script')
        self.tray_icon.menu = Menu(
            MenuItem('Toggle Power', self.toggle_power),
            MenuItem('Change Mode', self.toggle_mode),
            MenuItem('Exit', self.exit_action)
        )
        on_press_key('pause', self.on_key_event)
        on_press_key(70, self.on_key_event)
        self.tray_icon.run(self.setup_tray_icon)

def main():
    lamp = SmartLamp(DEVICE_ID, DEVICE_IP, LOCAL_KEY)
    lamp.init_tray_icon()

if __name__ == '__main__':
    main()`

This is my code, with API keys and the such removed.

**Comment by jasonacox** [comment]
It may help to see your script or better understand what device this is, but I can't think of anything that would be causing this.  

Are you able to ping the device after the reboot?

```bash
ping IP_ADDRESS_HERE
```

**Comment by justkanji** [comment]
> It may help to see your script or better understand what device this is, but I can't think of anything that would be causing this.
> 
> Are you able to ping the device after the reboot?
> 
> ```shell
> ping IP_ADDRESS_HERE
> ```

Here is my code. My device is just a smart bulb.
And no I can't ping it after a reboot of my computer, it's pretty strange, only after turning it off for like 5s and then back  on, pinging works and then my code works again, so somehow restarting my pc makes the device not return a ping. If I use things like the 'Smart Home' app on my phone or https://smartathome.co.uk/smartlife/ (it's a website that uses tuyapy to control tuya devices, also on github) they always work, even if I restart my PC.

```import pystray
from PIL import Image, ImageDraw
import keyboard
import tinytuya
import threading

# Replace these with your actual device information
DEVICE_ID = 
DEVICE_IP = 
LOCAL_KEY = 

def connect_to_device():
    d = tinytuya.BulbDevice(DEVICE_ID, DEVICE_IP, LOCAL_KEY)
    d.set_version(3.5)
    d.set_socketPersistent(True)
    return d

device = connect_to_device()  # Initialize the device object globally

def get_bulb_state():
    state = device.state()
    return state.get('is_on', False), state.get('mode', 'white')

def toggle_bulb_power_and_update_icon():
    is_on, mode = get_bulb_state()
    if is_on:
        device.turn_off()
    else:
        device.turn_on()
    update_tray_icon()

def toggle_bulb_mode_and_update_icon():
    is_on, mode = get_bulb_state()
    new_mode = 'white' if mode == 'colour' else 'colour'
    if is_on:
        device.set_mode(new_mode)
    update_tray_icon()

def on_pause_key(e):
    toggle_bulb_power_and_update_icon()

def on_scrolllock_key(e):
    toggle_bulb_mode_and_update_icon()

def create_image(color):
    width, height = 64, 64
    image = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    draw.rectangle(
        (width // 4, height // 4, 3 * width // 4, 3 * height // 4),
        fill=color
    )
    return image

def update_tray_icon():
    is_on, mode = get_bulb_state()
    if not is_on:
        icon.icon = create_image('black')
    elif mode == 'white':
        icon.icon = create_image('white')
    elif mode == 'colour':
        icon.icon = create_image('blue')

def toggle_power(icon, item):
    toggle_bulb_power_and_update_icon()

def change_mode(icon, item):
    toggle_bulb_mode_and_update_icon()

def exit_action(icon, item):
    icon.stop()
    global running
    running = False

def setup_tray_icon():
    global icon
    is_on, mode = get_bulb_state()
    initial_color = 'white' if is_on and mode == 'white' else 'blue' if is_on and mode == 'colour' else 'black'
    icon = pystray.Icon('name', create_image(initial_color), 'Smart Lamp Script')
    icon.menu = pystray.Menu(
        pystray.MenuItem('Toggle Power', toggle_power),
        pystray.MenuItem('Change Mode', change_mode),
        pystray.MenuItem('Exit', exit_action)
    )
    icon.run()

if __name__ == '__main__':
    keyboard.on_press_key('pause', on_pause_key)
    keyboard.on_press_key(70, on_scrolllock_key)

    tray_thread = threading.Thread(target=setup_tray_icon)
    tray_thread.start()

    try:
        tray_thread.join()
    except KeyboardInterrupt:
        pass

    keyboard.unhook_all()
```
I am not a programmer and got some help from ChatGPT to get the basic functionality I wanted, I have a different version with more stuff for brightness/color picker but this has the stuff I wanted (just turn it off and of and change to a single color when I want via keypress)

**Comment by jasonacox** [comment]
Thanks @justkanji - thanks for sharing the code. This seems straightforward, but the fact that you can't ping the device is the key issue.

A few questions:

> If I use things like the 'Smart Life' app on my phone or https://smartathome.co.uk/smartlife/ (it's a website that uses tuyapy to control tuya devices, also on github) they always work, even if I restart my PC.

The https://smartathome.co.uk/smartlife/ site uses the Tuya Cloud API, same as the Smart Life app. They do not need to talk to the device locally. Keep in mind that Tuya devices are "cloud first" devices, specifically designed to connect to the Tuya Cloud so that feature is by far the more reliable part of the device.  The local access that TinyTuya uses is a secondary API on the devices that SmartLife will use for initial setup of the device but on some devices is not very reliable. A few things to note about that:

* On some devices, the local access will often go offline when you are running SmartLife app. On these devices you need to completely quit all the SmartLife apps before TinyTuya can access them via the local API.
* Some devices disappear from the network until some activity occurs. This is especially the case for battery powered Tuya devices, but I have seen it from some others. These are nearly impossible to control with TinyTuya.
* Rebooting your computer won't matter. You can use a smartphone to access the smartathome.co.uk site and it would work even if your computer was offline. This is because it is using the Tuya Cloud versus your local network to access the device.
* If you want to use TinyTuya to talk to the device via the cloud, I suspect it would work. Example: https://github.com/jasonacox/tinytuya/blob/master/examples/cloud_rgb_bulb.py but keep in mind that Tuya limits the number of API calls w/o paying.

> no I can't ping it after a reboot of my computer

This is the reason that TinyTuya doesn't work. It require network connectivity from your computer to the Tuya Device. Why does it disappear when your computer restarts? Do you have another computer or laptop you can use to see if it still pings? I'm not sure I have any good suggestions for you to troubleshoot this.

**Comment by justkanji** [comment]
I tried pinging on a different device, it just disappears until I turn it off and back on. Maybe it's a power saving feature or the sort.
I'll try to find a solution ~ I guess for now I can just turn the lamp off and on when I reboot my PC.
Thank you for answering 👍  I'll close the issue.
