### ISSUE TITLE
Incomplete files

### ISSUE THREAD

**Issue by grosjo** [jasonacox/tinytuya#561]
Hi
Wren I clone the repo, or look at files via github. Files are cut to the first 78 lines
Is that on purpose ?
Thanks

**Comment by jasonacox** [comment]
I don't see that behavior. What are you looking at?

https://github.com/jasonacox/tinytuya/blob/master/tinytuya/wizard.py

<img width="797" alt="image" src="https://github.com/user-attachments/assets/af5a782a-7896-46a7-ae01-244d5d36e5e4">

**Comment by grosjo** [comment]
![image](https://github.com/user-attachments/assets/cfdf36a1-58bb-4ac9-be32-a0d7dfa38d05)

I can' t get the complete file

Also when I "git clone"  it, same, files are cut

**Comment by jasonacox** [comment]
OutletDevice.py is 78 lines longs. That is correct for that file. The class OutletDevice inherits the majority of its functions from this line:

```python
from .core import Device
```

Please look at [core.py](https://github.com/jasonacox/tinytuya/blob/master/tinytuya/core.py) to confirm that you see 2053 lines.

**Comment by grosjo** [comment]
indeed
