### ISSUE TITLE
Wifi selection

### ISSUE THREAD

**Issue by grosjo** [jasonacox/tinytuya#564]
Hi
Is there a command to set programatically the wifi network to use ?

**Comment by jasonacox** [comment]
That would be done during provisioning and not during local operations. I would recommend checking out the https://iot.tuya.com/ developer docs. TinyTuyy does have some Tuya cloud library functions to help, but we haven't explored the setup part which is generally done when users pair/add the device with the SmartLife app.

**Comment by grosjo** [comment]
ok thanks
