### ISSUE TITLE
Error from Tuya server: sign invalid

### ISSUE THREAD

**Issue by leopoldwang** [jasonacox/tinytuya#57]
Unable to connect to Tuya iot anymore.

Perhaps related to this change.

To better secure your cloud development, Tuya will upgrade the signature algorithm. Projects created after June 30, 2021 are subject to signature verification with the new algorithm. View details.
https://developer.tuya.com/en/docs/iot/singnature?id=Ka43a5mtx1gsc

**Comment by prostolyubo** [comment]
Same here. I went through all the steps in the readme. I can see my devices in the Tuya Cloud. But the wizard fails.

**Comment by leopoldwang** [comment]
I ended up using tuya cli to extract key which was updated yesterday using new signature algorithm. Once local key is retrieved, tinytuya works as expected.

**Comment by prostolyubo** [comment]
> I ended up using tuya cli to extract key which was updated yesterday using new signature algorithm. Once local key is retrieved, tinytuya works as expected.

Thanks for the workaround! I used Postman (Tuya also has a [guide ](https://developer.tuya.com/en/docs/iot/set-up-postman-environment?id=Ka7o385w1svns) how to do that) to retrieve the secret and am able to communicate with the device locally.

**Comment by jasonacox** [comment]
Thanks for the issue and info.  I'll update the tinytuya wizard to use the new signature algorithm.

**Comment by jasonacox** [comment]
I couldn't get the current wizard to fail.  I'm only seeing one difference in the IoT example from Tuya.  Basically adding`headers['secret'] = apiSecret` and checked in the update.  I didn't see any code change on tuya cli, just instructions.  I will review those.

What region were you testing (e.g. us, eu, cn, in)?

**Comment by prostolyubo** [comment]
In my case it was EU.
Have you created a new project? As tuya said, not signed  requests will fail only to projects created after June 30th. So if you tested on some older project the wizard wouldn't fail.

**Comment by leopoldwang** [comment]
My project was created in July as well so a new one which subjected to new signing requirement.

**Comment by WestXu** [comment]
It seems the new token sign process is demonstrated here in the official js repo: https://github.com/tuya/tuya-connector-nodejs/blob/23098c2a276ac1672772f88e88cb10cd359da7c2/examples/highway.ts#L65

Need to translate this func to python.

**Comment by WestXu** [comment]
Hey I just find out that there is a new [tuya_iot_python_sdk](https://github.com/tuya/tuya-iot-python-sdk) from tuya official. 

And their sign process is implemented [here](https://github.com/tuya/tuya-iot-python-sdk/blob/master/tuya_iot/openapi.py).

I tested it and it works. 

Maybe this project could just copy that. Or add it as a dep.

**Comment by jasonacox** [comment]
Thanks!  I agree, it makes a lot of sense to import the tuya developed sdk as it will help stay in front of any future changes on their cloud API.  Great find!   I won't be able to get to it for a few weeks due to a death in our family.  Look for tinytuya updates soon... and PRs welcome in the meantime.

**Comment by WestXu** [comment]
Sorry for your loss.

**Comment by davidkashtan-github** [comment]
I have the new signing code working if you would like a diff to integrate.

**Comment by arrmo** [comment]
So sorry to hear about your loss. My sincere condolonces.

**Comment by jasonacox** [comment]
Thanks for the kind words everyone. @davidkashtan-github yes, I would love to get a diff to merge.  Thanks for your help!

**Comment by davidkashtan-github** [comment]
Here is the diff against the current repository.  I added a parameter to tuyaPlatform
to control the signing algorithm and a couple of parameters that are really not used
other than to show how to include caller-defined body/headers in the signing.
-----------------------------------------------------------------------------

diff --git a/tinytuya/wizard.py b/tinytuya/wizard.py
index 4019e7f..79dca22 100644
--- a/tinytuya/wizard.py
+++ b/tinytuya/wizard.py
@@ -37,7 +37,7 @@ try:
 except NameError:
     pass
 
-def tuyaPlatform(apiRegion, apiKey, apiSecret, uri, token=None):
+def tuyaPlatform(apiRegion, apiKey, apiSecret, uri, token=None, new_sign_algorithm=False, body=None, headers=None):
     """Tuya IoT Platform Data Access
 
     Parameters:
@@ -70,13 +70,21 @@ def tuyaPlatform(apiRegion, apiKey, apiSecret, uri, token=None):
     """
     url = "https://openapi.tuya%s.com/v1.0/%s" % (apiRegion,uri)
     now = int(time.time()*1000)
-    headers = {}
+    headers = dict(list(headers.items()) + [('Signature-Headers', ":".join(headers.keys()))]) if headers else {}
     if(token==None):
         payload = apiKey + str(now)
         headers['secret'] = apiSecret
     else:
         payload = apiKey + token + str(now)
 
+    # If running the post 6-30-2021 signing algorithm update the payload to include it's data
+    if new_sign_algorithm: payload += ('GET\n' +                                                                # HTTPMethod
+                                       hashlib.sha256(bytes((body or "").encode('utf-8'))).hexdigest() + '\n' + # Content-SHA256
+                                       ''.join(['%s:%s\n'%(key, headers[key])                                   # Headers
+                                                for key in headers.get("Signature-Headers", "").split(":")
+                                                if key in headers]) + '\n' +
+                                       '/' + url.split('//', 1)[-1].split('/', 1)[-1])                          # Url (extracted from 'url')
+
     # Sign Payload
     signature = hmac.new(
         apiSecret.encode('utf-8'),

**Comment by davidkashtan-github** [comment]
Well, that did not go well as a comment...  How would you like me to deliver the diff to you?

**Comment by jasonacox** [comment]
You can have github format the code by using the code markdown tags (see [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)).  I edited your post for a diff code markdown.

Thanks for sending!

**Comment by ch491** [comment]
New to the Tuya API. A new cloud project (created after June 30th, 2021) requires the new signature (https://developer.tuya.com/en/docs/iot/singnature?id=Ka43a5mtx1gsc#title-3-stringToSign%20signature%20string) and I think that is my problem. I run the wizard and received "sign invalid" and cannot communicate with the Tuya Cloud.

**Comment by jasonacox** [comment]
Thanks @ch491 and @davidkashtan-github - Is there any reason we would not have this set to True by default now?

`
new_sign_algorithm=True
`

**Comment by prostolyubo** [comment]
It can be set to true. According to Tuya documentation the new signing
method is optional (backwards compatible) for old projects and mandatory
for new ones.

**Comment by jasonacox** [comment]
Thanks @prostolyubo - I set it to True.  I have released a new version to PyPI as [TinyTuya v1.2.7](https://pypi.org/project/tinytuya/1.2.7/).
