### ISSUE TITLE
run scan on other subnet

### ISSUE THREAD

**Issue by vespino** [jasonacox/tinytuya#573]
My IoT devices are on a dedicated VLAN that is different from the one I'm running TinyTuya on. Is it possible to run `python -m tinytuya scan` on another subnet?

**Comment by uzlonewolf** [comment]
Kind of.  Tuya devices transmit their device ID, protocol version, and IP address by sending out broadcast packets to the local subnet.  When scanning from a different network the only way to figure out the device ID and protocol version is to blindly try every combination until you find one that works.  TinyTuya does this with `python -m tinytuya scan -f 192.168.x.y/24` but it may or may not be successful.

**Comment by vespino** [comment]
It wasn’t successful, but no worries, I’ll get the data from my DHCP server and set the IPs static when found.
