### ISSUE TITLE
New To Python, Tuya & TinyTuya, tips to start & operate Garage Door control

### ISSUE THREAD

**Issue by Bignose3** [jasonacox/tinytuya#58]
I hate to ask as a real newbie to this but not sure where to start. I can program VBA so not a complete idiot.
Have Garage door set up fine on Tuya, works fine, Alexa etc.
Would like a script to operate from PC. Windows 10. 
Have installed Python, py V 3.93, has the built in PIP installer.
TinyTuya seemed to installed OK
python -m tinytuya - runs OK but says 0 devices found
I have no idea what to do with sudo apt-get install python-crypto python-pip # for RPi, Linux
from py command prompt, above gives syntax error, with or without the # bit
Could you just point me in the right direction.
Many thanks I/A

**Comment by jasonacox** [comment]
It sounds like you have it installed and set up correctly and don't need the apt-get (or you would get an error running tinytuya).  Garage door Tuya device may not broadcast the UDP discovery packets so tinytuya won't see it.  Do you have any other Tuya devices?  Try having tinytuya scan wait longer:

```
python -m tinytuya scan 50
```

**Comment by Bignose3** [comment]
Managed to get working, search took (100) Thank you, works great 90%.
Have local ID & works with code below but again hate to ask but really cannot work out the final operation.

I guessed to use CoverDevice & worked so sticking with that for the moment.

I had the sensor on the garage door wifi  magnet sensor taped together as if always closed.
so: d.open_cover(switch=1) worked, opened, closed & stopped (mid way) on each run. (cycles through)

now using sensor as intended & d.open_cover(switch=1) WORKS fine to open but not if gate is closed, understandable.
BUT neither d.close_cover(switch=1) or d.stop_cover(switch=1) will close either.

if open or opening
Current Status of XXXX: {'devId': '4235401524a160122b36', 'dps': {'1': True, '7': 0, '101': True}}
if closed
Current Status of XXXX: {'devId': '4235401524a160122b36', 'dps': {'1': False, '7': 0, '101': False}}

The Tuya app knows if open & closed & works accordingly, just wonder what other command I might try or if CoverDevice is the wrong choice to start with.

"""
    OUTLET Device
"""

import tinytuya
import time
import os
import random

DEVICEID = "4235401524a160122b36"
DEVICEIP = "192.168.2.132"
DEVICEKEY = "9c668ca5613fbdb3"
DEVICEVERS = "3.3"

# Check for environmental variables and always use those if available
DEVICEID = os.getenv("DEVICEID", DEVICEID)
DEVICEIP = os.getenv("DEVICEIP", DEVICEIP)
DEVICEKEY = os.getenv("DEVICEKEY", DEVICEKEY)
DEVICEVERS = os.getenv("DEVICEVERS", DEVICEVERS)

d = tinytuya.CoverDevice(DEVICEID, DEVICEIP, DEVICEKEY)

print('TESTING: Device %s at %s with key %s version %s' %
      (DEVICEID, DEVICEIP, DEVICEKEY, DEVICEVERS))

if(DEVICEVERS == '3.3'):    # IMPORTANT to always set version
    d.set_version(3.3)
    print("Is Version 3.3")
else:
    d.set_version(3.1)
    print("3.1")
# Keep socket connection open between commands
#d.set_socketPersistent(True)

data = d.status()
print('\nCurrent Status of XXXX: %r' % data)

#d.open_cover(switch=1)
#d.close_cover(switch=1)
#d.stop_cover(switch=1)

**Comment by jasonacox** [comment]
I don't have a device class for garage door so as you suspected, `CoverDevice` is probably not the right choice for you.  `CoverDevice` is for windows covers/blinds.  I know it is similar function but the garage device may use a different DPS for controlling the action.  From the status you show, it looks like `1` or `101` could be the index that controls or provides status.  With you help, I would love to gather the information and add this to TinyTuya, at least for the README or example scripts.

I would try something like this and try the different DPS numbers (1 or 101).

```python
import tinytuya
import time

d = tinytuya.OutletDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
data = d.status()
print('\nCurrent Status: %r' % data)

# try to open
print('Open')
d.set_value(101, True)
time.sleep(10)
data = d.status()
print('\nStatus: %r' % data)

# try to close
print('Open')
d.set_value(101, False)
time.sleep(10)
data = d.status()
print('\nStatus: %r' % data)
```

To find out more about status we get back and state changes that the Tuya device reports, you can use this code snip.  Run it and then manually open and close the garage to see what status data you get.

```python
import tinytuya

d = tinytuya.OutletDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)

print(" > Send Request for Status < ")
payload = d.generate_payload(tinytuya.DP_QUERY)
d.send(payload)

print(" > Begin Monitor Loop <")
while(True):
    # See if any data is available
    data = d.receive()
    print('Received Payload: %r' % data)

    # Send keyalive heartbeat
    print(" > Send Heartbeat Ping < ")
    payload = d.generate_payload(tinytuya.HEART_BEAT)
    d.send(payload)

```

**Comment by jasonacox** [comment]
Thanks for opening this issue.  I'm closing this for now. Please reopen if an issue still exists or you have a suggestion for a fix/feature.
