### ISSUE TITLE
Error from Tuya server: permission deny

### ISSUE THREAD

**Issue by wongcheehong** [jasonacox/tinytuya#59]
After running through the wizard I get this error saying "Error from Tuya server: permission deny". Is this because of the new Tuya new signature algorithm implementation? 
![image](https://user-images.githubusercontent.com/11075969/128029888-61f9c9b4-891d-4476-9c3c-847a8949becf.png)
https://developer.tuya.com/en/docs/iot/singnature?id=Ka43a5mtx1gsc

**Comment by jags9415** [comment]
@wongcheehong I'm having the same issue, were you able to fix it?

**Comment by wongcheehong** [comment]
@jags9415 I select all the region available and found mine tuya device is on different server
