### ISSUE TITLE
[question] LED Strip

### ISSUE THREAD

**Issue by vos6434** [jasonacox/tinytuya#61]
I have an addressable LED strip, how can I control each led on it?

**Comment by jasonacox** [comment]
Hi @vos6434 - I haven't seen one of those before.  The Tuya LED strip I have operates like an RGB bulb (all LEDs same color).  For yours, I don't know the DPS index it may use to control those.  However, we might be able to figure it out:

Can you run the wizard and copy/paste the details from the LED stip?  If you already ran the wizard, you can skip the first step.

* Step 1:
```bash
python -m tinytuya wizard
```
* Step 2:

That will create a file `tuya-raw.json` - look for the LED strip in that file and paste the details here, but remove the sensitive information (e.g. local_key, id, uuid).  

Here is an example from one of my LED strips:

```json
{
            "active_time": 1614268453,
            "biz_type": 18,
            "category": "dd",
            "create_time": 1614268453,
            "icon": "smart/icon/ay14906729310721fNjn/f266b748d1b92584887cde26ea9212ca.png",
            "name": "LED Strip Lights",
            "online": false,
            "owner_id": "1837218",
            "product_id": "e8naaq4xcsfvuunf",
            "product_name": "LED Strip Lights",
            "status": [
                {
                    "code": "switch_led",
                    "value": false
                },
                {
                    "code": "work_mode",
                    "value": "colour"
                },
                {
                    "code": "colour_data",
                    "value": "{\"h\":296,\"s\":810,\"v\":643}"
                },
                {
                    "code": "scene_data",
                    "value": "{\"scene_num\":1,\"scene_units\":[{\"bright\":0,\"h\":46,\"s\":1000,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":716}]}"
                },
                {
                    "code": "countdown",
                    "value": 0
                }
            ],
            "sub": false,
            "time_zone": "-08:00",
            "uid": "az1519057395035qo12o",
            "update_time": 1621661912,
            "uuid": ""
        }
```

**Comment by vos6434** [comment]
The app comes with some scenes and also a DIY profile where I can control segments of the strip.
`{
    "result": [
        {
            "active_time": 1628811951,
            "biz_type": 0,
            "category": "dj",
            "create_time": 1628783168,
            "icon": "smart/icon/ay1535688520667EMyk6/f232386eb497b992590299725bc6c79c.png",
            "id": "",
            "ip": "",
            "lat": "51.6812976",
            "local_key": "",
            "lon": "-0.4168953",
            "model": "RGB\u706f\u5e26\u5957\u88c5",
            "name": "Led Strip Lights",
            "online": true,
            "owner_id": "35592569",
            "product_id": "e9k85bsuxs0ppehx",
            "product_name": "Led Strip Lights",
            "status": [
                {
                    "code": "switch_led",
                    "value": true
                },
                {
                    "code": "work_mode",
                    "value": "white"
                },
                {
                    "code": "colour_data_v2",
                    "value": "{\"h\":120,\"s\":1000,\"v\":1000}"
                },
                {
                    "code": "scene_data_v2",
                    "value": "{\"scene_num\":1,\"scene_units\":[]}"
                }
            ],
            "sub": false,
            "time_zone": "+01:00",
            "uid": "eu1628807625179viNGl",
            "update_time": 1628958820,
            "uuid": ""
        }
    ],
    "success": true,
    "t": 1628959729410
}`

**Comment by jasonacox** [comment]
Ah!  So it likely controls the individual LEDs via scene data (the DPS scene_data_v2 and colour_data_v2).  So, the best way to figure out how to control it would be to monitor the actual "value" changes of those as you use the app.  So run this and notice the changes you see as you update the colors/LEDs in the app:

```python
# TinyTuya Example
import tinytuya

# Led Strip Lights
d = tinytuya.OutletDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)

print(" > Send Request for Status < ")
payload = d.generate_payload(tinytuya.DP_QUERY)
d.send(payload)

print(" > Begin Monitor Loop <")
while(True):
    # See if any data is available
    data = d.receive()
    print('Received Payload: %r' % data)

    # Send keyalive heartbeat
    print(" > Send Heartbeat Ping < ")
    payload = d.generate_payload(tinytuya.HEART_BEAT)
    d.send(payload)

    # Only uncomment if you don't get any status updates
    # print(" > Send Request for Status < ")
    # payload = d.generate_payload(tinytuya.DP_QUERY)
    # d.send(payload)

```

**Comment by vos6434** [comment]
Whats the command to apply the siaid dps scene?
how could i use this in the command {'dps': {'25': '08'}, 't': 1628963519}

**Comment by jasonacox** [comment]
You would do something like this:

```python
import tinytuya

d = tinytuya.BulbDevice('XXXX', 'XXXX', 'XXXX')
d.set_version(3.3)
data = d.status()

# Switch Bulb to scene mode if you haven't already
d.set_mode('scene')

# Example: Set scene
d.set_value(25, '08')

# Example: What I use for my LED strip
# d.set_value(25, '07464602000003e803e800000000464602007803e803e80000000046460200f003e803e800000000464602003d03e803e80000000046460200ae03e803e800000000464602011303e803e800000000')
```

**Comment by vos6434** [comment]
It seems like the DIY feature changes the LEDs in segments.

**Comment by vos6434** [comment]
Is it possible to use music scene but instead of using the LED Controller mic, it uses system audio?

**Comment by jasonacox** [comment]
Hi @vos6434  - Did you run the loop code above to see what DPS values you were getting when you changed LED settings with the app?   I have not had time to decipher how DPS 25 is used.  From my experience, if you send back (set_value) what you see while using the monitor code, you will get the same results as the app.  That should include setting individual segments.  Based on the differences in the values, you may be able to determine a way to set individual LEDs.

I'm not aware of any ability to send audio streams to Tuya devices.  I believe the music scene is only designed to use the onboard mic.  If you discover any way, please let us know!

**Comment by vos6434** [comment]
Yes I did run it, it uses set_value 103 for the DIY mode but the rest i cant figure out

**Comment by vos6434** [comment]
Now I can no longer control the strip at all.
![image](https://user-images.githubusercontent.com/21976486/129457727-bbc073e6-5660-4ebd-a027-7b24e6f5e94c.png)

**Comment by vos6434** [comment]
the DIY part of the app doesn't let me keep the colours still.

**Comment by jasonacox** [comment]
Thanks for sharing your experience.  Can you post the device details and link to where you got it?  Any data, screenshots, code examples or output you can share with the community about your experiments would be helpful for others working with the same device.  Perhaps someone else has the same device and has figure out more about the DIY mode.

**Comment by vos6434** [comment]
Got it from Amazon here https://amzn.to/3m0eGRv
you can set it to DIY by d.set_mode(mode='DIY')
