### ISSUE TITLE
Empty Payload Response

### ISSUE THREAD

**Issue by atomdog** [jasonacox/tinytuya#64]
Hi,
I'm using an Energizer bulb I realized was talking to the Tuya servers. It works from the Tuya app, but Tuya demands that I use their beta IoT solutions app, and when I try to control it locally I get the following error.

`DEBUG:raw unpacked message = TuyaMessage(seqno=1, cmd=10, retcode=1, payload=b"\x96\xa2\x8d\x9dB\xf1\xcc\xae\xe6{K\xc9'\xe8\x19\x11\xab\xbf\x8dL\x91v\x13\xa9!\xd2\xdck\x89\xc1\x96n", crc=2352078917)
DEBUG:decode payload=b"\x96\xa2\x8d\x9dB\xf1\xcc\xae\xe6{K\xc9'\xe8\x19\x11\xab\xbf\x8dL\x91v\x13\xa9!\xd2\xdck\x89\xc1\x96n"
DEBUG:decrypting=b"\x96\xa2\x8d\x9dB\xf1\xcc\xae\xe6{K\xc9'\xe8\x19\x11\xab\xbf\x8dL\x91v\x13\xa9!\xd2\xdck\x89\xc1\x96n"
DEBUG:decrypted 3.3 payload=''
DEBUG:decoded results=''
DEBUG:ERROR Invalid JSON Response from Device - 900 - payload: ""
DEBUG:status() received data={'Error': 'Invalid JSON Response from Device', 'Err': '900', 'Payload': ''}`

This is after requesting a status. It is worth noting I cannot poll locally.

**Comment by jasonacox** [comment]
Hi @atomdog - can you try running an async monitor loop on the device to see what data it is giving off?  While this is running, use the SmartLife app to change the state of the bulb (power, brightness, color, etc.).

```python
import tinytuya

# tinytuya.set_debug(True)

d = tinytuya.OutletDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)

print(" > Send Request for Status < ")
payload = d.generate_payload(tinytuya.DP_QUERY)
d.send(payload)

print(" > Begin Monitor Loop <")
while(True):
    # See if any data is available
    data = d.receive()
    print('Received Payload: %r' % data)

    # Send keyalive heartbeat
    print(" > Send Heartbeat Ping < ")
    payload = d.generate_payload(tinytuya.HEART_BEAT)
    d.send(payload)

```

**Comment by atomdog** [comment]
> Hi @atomdog - can you try running an async monitor loop on the device to see what data it is giving off? While this is running, use the SmartLife app to change the state of the bulb (power, brightness, color, etc.).
> 
> ```python
> import tinytuya
> 
> # tinytuya.set_debug(True)
> 
> d = tinytuya.OutletDevice(DEVICEID, DEVICEIP, DEVICEKEY)
> d.set_version(3.3)
> d.set_socketPersistent(True)
> 
> print(" > Send Request for Status < ")
> payload = d.generate_payload(tinytuya.DP_QUERY)
> d.send(payload)
> 
> print(" > Begin Monitor Loop <")
> while(True):
>     # See if any data is available
>     data = d.receive()
>     print('Received Payload: %r' % data)
> 
>     # Send keyalive heartbeat
>     print(" > Send Heartbeat Ping < ")
>     payload = d.generate_payload(tinytuya.HEART_BEAT)
>     d.send(payload)
> ```

No, I did something else. Your code runs well, it's Tuya's fault. gg brother thanks for the help. solid work all around.
