### ISSUE TITLE
Unable to control RGB led strip, scanner yielding strange results

### ISSUE THREAD

**Issue by mervinvb** [jasonacox/tinytuya#67]
Hello! I recently purchased an RGB led strip with wifi connection for use with the Tuya Smart Home system. (This is the one: https://www.amazon.nl/gp/product/B08FXBD8J9/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1, I'm sure it's a fairly generic wifi led strip). I am having some issues controlling it with TinyTuya. Here's a rundown of the issues I've encountered:

It starts off with the TinyTuya scanner (the `python -m tinytuya scan` command). My smart sockets register just fine, but my led strip is giving some strange results:
```
Unknown v Device   Product ID =   [Unknown payload]:
    Address = 192.168.178.87,  Device ID = , Local Key = ,  Version = 
    No Stats for 192.168.178.87: DEVICE KEY required to poll for status
```

After this it prints out an unexpected payload, I am however unsure what data this contains and thus cautious about sharing it. It _looks_ like this:
```
b"/jd8/x87f3oi/bex/10r/dj5/jf7/fxj/kjsd*.y/n58+eL/x92'd/.... (continues like this for a total of 400 characters)
```

Knowing the IP address of the light, I shrugged it off and continued with trying to control it. Trying to control the device gave me a new error:
```
{'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': ''}
```

I didn't really know what this error meant, so I went here on GitHub to look at some issues other users were facing. There, I found this code that monitors the device: https://github.com/jasonacox/tinytuya/issues/61#issuecomment-898936843

Some interesting behavior happens when I run that code while controlling the lights via the Smart Life app. Every time I make a change, like turning off or on the led strip, I do actually receive something:
```
Received Payload: {'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
 > Send Heartbeat Ping < 
Received Payload: {'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
 > Send Heartbeat Ping < 
Received Payload: {'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
 > Send Heartbeat Ping < 
Received Payload: {'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
 > Send Heartbeat Ping < 
```
More 904 error codes. This was after turning my led strip off and on twice, so it did register every change, which makes the problem even stranger to me. 

Clearly there is an established connection thru TinyTuya, but for some reason this led strip doesn't want to play nice. I've tried using TinyTuya for my smart sockets, and I am able to control them without any problems.

Any help with this would be greatly appreciated, as I really have no idea what is causing this issue.

Thanks!

**Comment by jasonacox** [comment]
It does not appear you are using the correct device KEY.   The payload you pasted above is encrypted so you will need the right device local KEY as well as the ID and IP address to decrypt the status payload and send updates.   What do you see when you run the wizard?
```
python -m tinytuya wizard
```

(see https://github.com/jasonacox/tinytuya#tuya-device-preparation for more info on device keys)

**Comment by mervinvb** [comment]
Thank you for your reply! Running the wizard does give me an error, although the error happens at the "Poll local devices" stage. This is the error:

```
Polling local devices...
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tinytuya/__main__.py", line 49, in <module>
    wizard.wizard(color)
  File "/usr/local/lib/python3.9/site-packages/tinytuya/wizard.py", line 284, in wizard
    (ip, ver) = getIP(devices, i['id'])
  File "/usr/local/lib/python3.9/site-packages/tinytuya/wizard.py", line 275, in getIP
    if (gwid == d[ip]['gwId']):
KeyError: 'gwId'
```

I'm not sure what this means. 

The first part of the wizard did go well, I got the JSON of all of my devices and their associated IDs and keys.

Any clue what is causing this error?

**Comment by jasonacox** [comment]
Thats very interesting.  That means the scan found a device that did not provide its ID.  But I'm assuming the device provided some scan data back that did not include its device ID (gwId).  Can you find the RGB led strip device in the `devices.json` that was created during the wizard?  I would like to see it (please remove the KEY data) if you don't mind posting it. 

Now that you ran the wizard to get the device KEYs can you run `python -m tinytuya scan` to see if the RGB led strip device shows up?

**Comment by mervinvb** [comment]
The devices.json looks perfectly normal to me, it just shows me the devices I have registered in the Smart Life app:

```
[
    {
        "name": "RGB led strip",
        "id": "bf07edf111ed1d31dbd1p2",
        "key": "1234567890"
    },
    {
        "name": "spotlight switch",
        "id": "012002876001949347b8",
        "key": "1234567890"
    }
]

(Key data changed to 1234567890)
```


Running the scan yields the same results as I described in my original post:
```
*  Unexpected payload=%r
 b"/jd8/x87f3oi/bex/10r/dj5/jf7/fxj/kjsd*.y/n58+eL/x92'd/...." (Goes on for a little while...)

Unknown v Device   Product ID =   [Unknown payload]:
    Address = 192.168.178.87,  Device ID = , Local Key = ,  Version = 
    No Stats for 192.168.178.87: DEVICE KEY required to poll for status

*  Unexpected payload=%r
 b"/jd8/x87f3oi/bex/10r/dj5/jf7/fxj/kjsd*.y/n58+eL/x92'd/...." (Goes on for a little while...)
```

I have verified that 192.168.178.87 is indeed the IP address of the led strip. So it does show up, it just doesn't seem to communicate properly.

**Comment by jasonacox** [comment]
> Unknown v Device   Product ID =   [Unknown payload]:
    Address = 192.168.178.87,  Device ID = , Local Key = ,  Version = 
    No Stats for 192.168.178.87: DEVICE KEY required to poll for status

Thanks @mervinvb  - can you also post the `tuya-raw.json` file that the wizard pulled from Tuya Cloud?  I'm hunting for clues as to why the device is not sending its ID back (it should be sending bf07edf111ed1d31dbd1p2 based on the devices.json file you posted).  In this exmaple, the ID is empty and TinyTuya is therefore unable to match it to the device local key to decrypt the payload.

By chance, does the SmartLife app happen to show if the device needs a firmware upgrade?

Based on the number of characters in the ID, it may require special treatment we randomly see with some devices (which tinytuya should auto-detect and correct). But you can try this:
```python
import tinytuya

a = tinytuya.OutletDevice('bf07edf111ed1d31dbd1p2', '192.168.178.87', KEY, 'device22')
a.set_version(3.3)
a.set_dpsUsed({"1": None})  # This needs to be a datapoint available on the device
data =  a.status()
print(data)
```

Out of curiosity, does your *"spotlight switch"* work with TinyTuya?

**Comment by mervinvb** [comment]
Here's the tuya-raw.json data (with some data being censored for privacy):

```
        {
            "active_time": 1631554174,
            "biz_type": 18,
            "category": "dd",
            "create_time": 1631554174,
            "icon": "smart/icon/ay1498203399759ASLsi/a491ae23567d589e29a0fb1517548bf6.png",
            "id": "bf07edf111ed1d31dbd1p2",
            "ip": "******",
            "lat": "******",
            "local_key": "******",
            "lon": "*****",
            "model": "",
            "name": "RGB led strip",
            "online": true,
            "owner_id": "*****",
            "product_id": "bz7cvkzjx40nzoje",
            "product_name": "RGBstriplight",
            "status": [
                {
                    "code": "switch_led",
                    "value": false
                },
                {
                    "code": "work_mode",
                    "value": "colour"
                },
                {
                    "code": "colour_data",
                    "value": "{\"h\":0,\"s\":0,\"v\":1000}"
                },
                {
                    "code": "scene_data",
                    "value": "{\"scene_num\":5,\"scene_units\":[{\"bright\":0,\"h\":120,\"s\":1000,\"temperature\":0,\"unit_change_mode\":\"gradient\",\"unit_gradient_duration\":70,\"unit_switch_duration\":70,\"v\":1000},{\"bright\":0,\"h\":120,\"s\":1000,\"temperature\":0,\"unit_change_mode\":\"gradient\",\"unit_gradient_duration\":70,\"unit_switch_duration\":70,\"v\":10}]}"
                },
                {
                    "code": "countdown",
                    "value": 0
                }
            ],
            "sub": false,
            "time_zone": "+02:00",
            "uid": "********",
            "update_time": 1632320097,
            "uuid": "*******"
        },
```

> By chance, does the SmartLife app happen to show if the device needs a firmware upgrade?
Both devices are on the latest firmware.

> Out of curiosity, does your "spotlight switch" work with TinyTuya?
This is where it gets interesting. It _used to_ work when I initially tested TinyTuya. (As I said in my initial post)
Now however, it doesn't show up on the scan anymore. It does still work with the smart life app though. 


I've done some testing with [TuyAPI](https://github.com/codetheweb/tuyapi) to figure out whether or not this whole issue actually has to do with TinyTuya, which gave me some insights. Running the example code on the RGB strip gave me this:
```
Data from device: {
  dps: {
    '20': false,
    '21': 'colour',
    '24': '0000000003e8',
    '25': '04464602007803e803e800000000464602007803e8000a00000000',
    '26': 0
  }
}
Boolean status of default property: undefined.
Disconnected from device.
Error! Timeout waiting for status response from device id: bf07edf111ed1d31dbd1p2
```

Interestingly enough, the device does return some information, however, quickly thereafter a timeout occurs. TuyAPI was also unable to connect to my _spotlight switch_ device. 

This shows me that my issue might not have to do with TinyTuya. It might be an issue on only my network and with my devices. I'd understand if you'd prefer not to spend more time trying to troubleshoot this with me, as I don't suppose many others will face this issue. 

Any help will still be greatly appreciated though!

**Comment by jasonacox** [comment]
Yes, that is interesting!  I don't mind helping.  It could point to some feature for TinyTuya. 

Tuya devices often only handle one connection at a time.  Make sure SmartLife app is closed before you run TinyTuya or TuyAPI.   The tuya-raw.json looks good, but I'll poke around to see if there are any issues reported with that profile.  

If you run a ping against the IP address for the devices, do you see any packet loss?

**Comment by mervinvb** [comment]
Thank you for your help! 

Both of my devices have a 0% packet loss after pinging them for a few minutes. 

I've tested some more, and for some reason now my _spotlight switch_ is working again. I can fully control (and find) it with TinyTuya. Something strange did happen when testing: I was turning my _spotlight switch_ on and off a few times while connecting my RGB strip light. The _spotlight switch_ stopped working after plugging in my RGB strip light. This only happened once though, and I am unable to replicate this behavior. 

So right now I'm back to the same issue as before: _spotlight switch_ working fine, but RGB led strip giving the same error as always:
```
{'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': ''}
```

Hopefully you have some idea about where to further the debugging form here.

**Comment by jasonacox** [comment]
Yes, let's try turning on debug mode to see if there is anything to see in the verbose handshakes:

First as a simple outlet class:
```python
DEVICEID = "bf07edf111ed1d31dbd1p2"
DEVICEIP = "Auto"
DEVICEKEY = "******"

import tinytuya

print("TinyTuya (Tuya Interface) [%s]\n" % tinytuya.__version__)

# SET DEBUG MODE
tinytuya.set_debug(True)

d = tinytuya.OutletDevice(DEVICEID, DEVICEIP, DEVICEKEY)
print(d)
d.set_version(3.3)

print(" >>> Fetch Status <<< ")
data = d.status()
print(data)

print(" >>> Fetch Status <<< ")
data = d.status()
print(data)

```

Then as an bulb class:
```python
DEVICEID = "bf07edf111ed1d31dbd1p2"
DEVICEIP = "Auto"
DEVICEKEY = "******"

import tinytuya

print("TinyTuya (Tuya Interface) [%s]\n" % tinytuya.__version__)

# SET DEBUG MODE
tinytuya.set_debug(True)

d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)
d.set_socketPersistent(True)  

print(" >>> Fetch Status <<< ")
data = d.status()
print(data)

print(" >>> Fetch Status <<< ")
data = d.status()
print(data)

```

**Comment by mervinvb** [comment]
Setting DEVICEIP to "Auto" did not yield any results, filling in the right IP did work. Running it as the outlet class gives me this large wall of text:

```
 >>> Fetch Status <<< 
DEBUG:status() entry (dev_type is default)
DEBUG:building payload=b'{"gwId":"bf07edf111ed1d31dbd1p2","devId":"bf07edf111ed1d31dbd1p2","uid":"bf07edf111ed1d31dbd1p2","t":"1632557812"}'
DEBUG:payload generated=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x88fH/\r\x1d\xccM\x14X\x1d\xd8HG\x1d\xa2\x03\xf1:0\x0bpg\x96\xf3M\x82\x06\xc3.\xad|A\xc1\xdc^f\x19u\t\xd2i\xc4\x0e\x03m[\x7f\xef\xbaJ`\xac\xcb\\:\xb2m^\xc3\xbd\xa0\x80\xf2\x80\xe4\xc3|\xe4\xd0\xbf\xd9\x87\t\xff\xbc\xa0\x06~\xb4\x92\xf1:0\x0bpg\x96\xf3M\x82\x06\xc3.\xad|A\x13\n\x1fXpX\xc0\xa5j\xb1\x1d\xfd\xc0[\x83`\r\xd4*\xdd\x08;\xeb<\xae\xf0\xdb\xad\xd7\xb2[\x9b\x1b\\;\x86\x00\x00\xaaU'
DEBUG:received data=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x8c\x00\x00\x00\x00\xe9qW\xfe]\n\xc6\x7f.rI\r\xf0\xa6\xde`\xb9\xfew!\x8e\x17\xaf\x02\x07M\xd3\x16\xcf\xcb\xff\x99J\xbf\x7f\xd1fM\xf4\xf4\x8d\xf8\xe4\x00FF\xa2x\xe5\xea\x7f\xb1\x87\x963a\x8b\xe9\xc9\xd37\xa9g[u\x95;\xc5\x11@\xd5\\\xb9\xfb.\xb1Q:Cl\xe4\x04\t\xfa\x80L\x80?\x17[\xc9"g\xec\xd7\x91\x9c\x1d\x0c\xdc\xb7\xfe\xd59\x14\xb2Q\xdcj\xeb1\x01\x8a\xcf\xde\xf3\x17)\xb30\xf8\xe9EO)\x02=\x8a\xfa\t<\x8d\x00\x00\xaaU'
DEBUG:raw unpacked message = TuyaMessage(seqno=0, cmd=10, retcode=0, payload=b'\xe9qW\xfe]\n\xc6\x7f.rI\r\xf0\xa6\xde`\xb9\xfew!\x8e\x17\xaf\x02\x07M\xd3\x16\xcf\xcb\xff\x99J\xbf\x7f\xd1fM\xf4\xf4\x8d\xf8\xe4\x00FF\xa2x\xe5\xea\x7f\xb1\x87\x963a\x8b\xe9\xc9\xd37\xa9g[u\x95;\xc5\x11@\xd5\\\xb9\xfb.\xb1Q:Cl\xe4\x04\t\xfa\x80L\x80?\x17[\xc9"g\xec\xd7\x91\x9c\x1d\x0c\xdc\xb7\xfe\xd59\x14\xb2Q\xdcj\xeb1\x01\x8a\xcf\xde\xf3\x17)\xb30\xf8\xe9EO)\x02=\x8a', crc=4194909325)
DEBUG:decode payload=b'\xe9qW\xfe]\n\xc6\x7f.rI\r\xf0\xa6\xde`\xb9\xfew!\x8e\x17\xaf\x02\x07M\xd3\x16\xcf\xcb\xff\x99J\xbf\x7f\xd1fM\xf4\xf4\x8d\xf8\xe4\x00FF\xa2x\xe5\xea\x7f\xb1\x87\x963a\x8b\xe9\xc9\xd37\xa9g[u\x95;\xc5\x11@\xd5\\\xb9\xfb.\xb1Q:Cl\xe4\x04\t\xfa\x80L\x80?\x17[\xc9"g\xec\xd7\x91\x9c\x1d\x0c\xdc\xb7\xfe\xd59\x14\xb2Q\xdcj\xeb1\x01\x8a\xcf\xde\xf3\x17)\xb30\xf8\xe9EO)\x02=\x8a'
DEBUG:decrypting=b'\xe9qW\xfe]\n\xc6\x7f.rI\r\xf0\xa6\xde`\xb9\xfew!\x8e\x17\xaf\x02\x07M\xd3\x16\xcf\xcb\xff\x99J\xbf\x7f\xd1fM\xf4\xf4\x8d\xf8\xe4\x00FF\xa2x\xe5\xea\x7f\xb1\x87\x963a\x8b\xe9\xc9\xd37\xa9g[u\x95;\xc5\x11@\xd5\\\xb9\xfb.\xb1Q:Cl\xe4\x04\t\xfa\x80L\x80?\x17[\xc9"g\xec\xd7\x91\x9c\x1d\x0c\xdc\xb7\xfe\xd59\x14\xb2Q\xdcj\xeb1\x01\x8a\xcf\xde\xf3\x17)\xb30\xf8\xe9EO)\x02=\x8a'
DEBUG:decrypted 3.3 payload=b'{"dps":{"20":false,"21":"colour","24":"0000000003e8","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}'
DEBUG:unexpected result unpacking tuya payload
DEBUG:ERROR Unexpected Payload from Device - 904 - payload: null
DEBUG:status() received data={'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
{'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}

(This same text gets repeated)
```

What catches my eye about this blob is text is this part:
```
DEBUG:decrypted 3.3 payload=b'{"dps":{"20":false,"21":"colour","24":"0000000003e8","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}'
```
This seems like decrypted info about the device. Turning on the device and running the program again changed the value of `20` to `true`, which shows that `20` indicates the power status of the device. So there is some data after all...


This is the result for running it as a bulb class:
```
 >>> Fetch Status <<< 
DEBUG:status() entry (dev_type is default)
DEBUG:building payload=b'{"gwId":"bf07edf111ed1d31dbd1p2","devId":"bf07edf111ed1d31dbd1p2","uid":"bf07edf111ed1d31dbd1p2","t":"1632558130"}'
DEBUG:payload generated=b'\x00\x00U\xaa\x00\x00\x00\x01\x00\x00\x00\n\x00\x00\x00\x88fH/\r\x1d\xccM\x14X\x1d\xd8HG\x1d\xa2\x03\xf1:0\x0bpg\x96\xf3M\x82\x06\xc3.\xad|A\xc1\xdc^f\x19u\t\xd2i\xc4\x0e\x03m[\x7f\xef\xbaJ`\xac\xcb\\:\xb2m^\xc3\xbd\xa0\x80\xf2\x80\xe4\xc3|\xe4\xd0\xbf\xd9\x87\t\xff\xbc\xa0\x06~\xb4\x92\xf1:0\x0bpg\x96\xf3M\x82\x06\xc3.\xad|A\xa0\xf03\xc7\xcc6\xae\x04\x8d\xec\xb25\xbb\xe9\x04[\r\xd4*\xdd\x08;\xeb<\xae\xf0\xdb\xad\xd7\xb2[\x9b\x018\xaa\x8c\x00\x00\xaaU'
DEBUG:received data=b"\x00\x00U\xaa\x00\x00\x00\x01\x00\x00\x00\n\x00\x00\x00\x8c\x00\x00\x00\x00\xceG\xf3\xf0\xf6\x1bt\xe8\x93b\xe2Z\xcf8\x9b\xb9\x96e\xc8\x1cE\xabm^\xed\xfb\xedIO\x98\xb4\xeb\x0e\x87\x97\x93gP\x14\xed\xbby;\xf7g\xc2\xc5\xde\x90<\xf2\xba\xc1/\xfd\x13\xebQ9N\x98\xf3{\x1f\xdc\x98T\xdb\xad\x95\x91\x8c\xaa\xd6\xca\xd0I'\x89\xf3m.\xdf\x90\xd1q%\xc9\xeb\xfa\xf8\xf6a\xff\x84\xc4]\xff\x82\x8e(\x08\xe4\xf7\xda\x0bA\xa0\x81]j/X\x01\xaa\x1bN\xa2\xc8\x9c\x0b\xd5\xf8UY\xee\xd2\xf7\x9c\xf7}r\x00\x00\xaaU"
DEBUG:raw unpacked message = TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b"\xceG\xf3\xf0\xf6\x1bt\xe8\x93b\xe2Z\xcf8\x9b\xb9\x96e\xc8\x1cE\xabm^\xed\xfb\xedIO\x98\xb4\xeb\x0e\x87\x97\x93gP\x14\xed\xbby;\xf7g\xc2\xc5\xde\x90<\xf2\xba\xc1/\xfd\x13\xebQ9N\x98\xf3{\x1f\xdc\x98T\xdb\xad\x95\x91\x8c\xaa\xd6\xca\xd0I'\x89\xf3m.\xdf\x90\xd1q%\xc9\xeb\xfa\xf8\xf6a\xff\x84\xc4]\xff\x82\x8e(\x08\xe4\xf7\xda\x0bA\xa0\x81]j/X\x01\xaa\x1bN\xa2\xc8\x9c\x0b\xd5\xf8UY\xee\xd2\xf7", crc=2633465202)
DEBUG:decode payload=b"\xceG\xf3\xf0\xf6\x1bt\xe8\x93b\xe2Z\xcf8\x9b\xb9\x96e\xc8\x1cE\xabm^\xed\xfb\xedIO\x98\xb4\xeb\x0e\x87\x97\x93gP\x14\xed\xbby;\xf7g\xc2\xc5\xde\x90<\xf2\xba\xc1/\xfd\x13\xebQ9N\x98\xf3{\x1f\xdc\x98T\xdb\xad\x95\x91\x8c\xaa\xd6\xca\xd0I'\x89\xf3m.\xdf\x90\xd1q%\xc9\xeb\xfa\xf8\xf6a\xff\x84\xc4]\xff\x82\x8e(\x08\xe4\xf7\xda\x0bA\xa0\x81]j/X\x01\xaa\x1bN\xa2\xc8\x9c\x0b\xd5\xf8UY\xee\xd2\xf7"
DEBUG:decrypting=b"\xceG\xf3\xf0\xf6\x1bt\xe8\x93b\xe2Z\xcf8\x9b\xb9\x96e\xc8\x1cE\xabm^\xed\xfb\xedIO\x98\xb4\xeb\x0e\x87\x97\x93gP\x14\xed\xbby;\xf7g\xc2\xc5\xde\x90<\xf2\xba\xc1/\xfd\x13\xebQ9N\x98\xf3{\x1f\xdc\x98T\xdb\xad\x95\x91\x8c\xaa\xd6\xca\xd0I'\x89\xf3m.\xdf\x90\xd1q%\xc9\xeb\xfa\xf8\xf6a\xff\x84\xc4]\xff\x82\x8e(\x08\xe4\xf7\xda\x0bA\xa0\x81]j/X\x01\xaa\x1bN\xa2\xc8\x9c\x0b\xd5\xf8UY\xee\xd2\xf7"
DEBUG:decrypted 3.3 payload=b'{"dps":{"20":true,"21":"colour","24":"0000000003e8","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}'
DEBUG:unexpected result unpacking tuya payload
DEBUG:ERROR Unexpected Payload from Device - 904 - payload: null
DEBUG:status() received data={'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}
{'Error': 'Unexpected Payload from Device', 'Err': '904', 'Payload': None}

(This same text gets repeated)
```

There is some information flying around in those endless strings of encrypted payloads after all! Interesting stuff...

**Comment by jasonacox** [comment]
This is great!  Confusing, but GREAT.  It does mean we are getting a valid payload back that can be decrypted with the local key.  However, something is throwing an exception that is getting trapped during the json decode.   I'm not able to replicate any JSON exception using the payload:

```python
>>> d=b'{"dps":{"20":false,"21":"colour","24":"0000000003e8","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}'
>>> json.loads(d)
{'dps': {'20': False, '21': 'colour', '24': '0000000003e8', '25': '04464602007803e803e800000000464602007803e8000a00000000', '26': 0}}
```

That means it is likely something else.  The _send_receive() function is the one that is catching the exception resulting in the 904 error.  The section of interest:

```python
        # Unpack Message into TuyaMessage format
        # and return payload decrypted
        try:
            msg = unpack_message(data)
            # Data available seqno cmd retcode payload crc
            log.debug("raw unpacked message = %r", msg)
            result = self._decode_payload(msg.payload)
        except:
            log.debug("unexpected result unpacking tuya payload")
            result = error_json(ERR_PAYLOAD)
```

That is a wildcard `except:` so it would capture anything.  I suspect the device could be doing something that is causing a socket error that is getting intercepted in this `try:` block tripping the exception.  If that is the case, I can trap a `except socket.error:` branch before the wildcard.  I've never seen this before so I could be wrong.  Ideally, I would love for you to help troubleshoot before I add that logic:
1.  Download a clone of TinyTuya to your local machine
```bash
git clone https://github.com/jasonacox/tinytuya.git
cd tinytuya
```
2. Edit  `tinytuya/__init__.py` and remove the `try:` block in the  _send_receive() function and let the raw exception happen, something like this:
```python
        # Unpack Message into TuyaMessage format
        # and return payload decrypted

        msg = unpack_message(data)
        # Data available seqno cmd retcode payload crc
        log.debug("raw unpacked message = %r", msg)
        result = self._decode_payload(msg.payload)
```
3. Run your test script from inside the tinytuya clone (forcing python to use the local version instead of the pip installed library)

**Comment by jasonacox** [comment]
UPDATE:  For a test, I added the additional exception handling to the pre-release code on github:

```python
        # Unpack Message into TuyaMessage format
        # and return payload decrypted
        try:
            msg = unpack_message(data)
            # Data available seqno cmd retcode payload crc
            log.debug("raw unpacked message = %r", msg)
            result = self._decode_payload(msg.payload)
        except socket.error as e: 
            log.debug("device caused socket error, ignoring %s" % e)
        except ValueError:
            log.debug("error unpacking tuya JSON payload")
            result = error_json(ERR_PAYLOAD)
        except:
            log.debug("unexpected error occurred, ignoring")
```

You can just pull this down and test if you would like:

```bash
# clone repo
git clone https://github.com/jasonacox/tinytuya.git

# move into repo
cd tinytuya

# copy over your test script and run it
python3 testscript.py
```

**Comment by mervinvb** [comment]
Using the pre-release code, I got the following exception:

```
(Same large decoded string as before)

DEBUG:decrypted 3.3 payload=b'{"dps":{"20":false,"21":"colour","24":"0000000003e8","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}'
DEBUG:unexpected error occurred, ignoring


Traceback (most recent call last):
  File "/Users/mervin/tinytuya/debug_lights.py", line 13, in <module>
    d.set_version(3.3)
  File "/Users/mervin/tinytuya/tinytuya/__init__.py", line 1266, in set_version
    status = self.status()
  File "/Users/mervin/tinytuya/tinytuya/__init__.py", line 905, in status
    data = self._send_receive(payload)
  File "/Users/mervin/tinytuya/tinytuya/__init__.py", line 616, in _send_receive
    return result
UnboundLocalError: local variable 'result' referenced before assignment
```
It would appear to have been caught by the wildcard `except:`, after which `result` is never defined, causing the UnboundLocalError (not sure if I'm correct about this). 

I also tried your first described approach, which caused the following error:
```
Traceback (most recent call last):
  File "/Users/mervin/tinytuya/debug_lights.py", line 13, in <module>
    d.set_version(3.3)
  File "/Users/mervin/tinytuya/tinytuya/__init__.py", line 1260, in set_version
    status = self.status()
  File "/Users/mervin/tinytuya/tinytuya/__init__.py", line 899, in status
    data = self._send_receive(payload)
  File "/Users/mervin/tinytuya/tinytuya/__init__.py", line 598, in _send_receive
    result = self._decode_payload(msg.payload)
  File "/Users/mervin/tinytuya/tinytuya/__init__.py", line 637, in _decode_payload
    if "data unvalid" in payload:
TypeError: a bytes-like object is required, not 'str'
```

It seems like the TypeError is caused by checking if the string `data unvalid` is in the variable `payload`. The payload in this case is:
```
b'{"dps":{"20":false,"21":"colour","24":"0000000003e8","25":"04464602007803e803e800000000464602007803e8000a00000000","26":0}}
```
The variable `payload` is seen as a `<class 'bytes'>`, which I have never used nor seen before. I decoded the payload back into the proper type using this rather sketchy looking code: `payload = json.dumps(json.loads(payload.decode('utf8')))`. And lo and behold, I am now able to set the color and brightness of the RGB strip light! I've had no luck yet turning the device on or off, but I think I'm just not using the right function to do so. 

At least I have some control over the RGB light now, which is a major breakthrough!

**Comment by jasonacox** [comment]
Nice work!  You may have a unusual Tuya device that sends back an encode and encrypted payload, but I do see how the "data unvalid" conditional will error out.   The `_decode_payload()` function does test for non-string payloads and does try to decode them, but that happens after looking for the "data unvalid" string.  I've haven't heard of a case, outside of yours, where the 3.3 version payload comes back encoded, but this is a great opportunity to fix it.  I'll add that test and attempt to decode before the comparison:

```python
             log.debug('decrypted 3.3 payload=%r', payload)
            # Try to detect if device22 found
            log.debug("payload type = %s" % type(payload))
            if not isinstance(payload, str):
                try:
                    payload = payload.decode()
                except:
                    log.debug("payload was not string type and decoding failed")
                    return error_json(ERR_JSON,payload)
            if "data unvalid" in payload:
                self.dev_type = "device22"
                # set at least one DPS
                self.dps_to_request = {"1": None}
                log.debug(
                    "'data unvalid' error detected: switching to dev_type %r",
                    self.dev_type,
                )
                return None
```

I've check this into the pre-release version on Github.  Would you be willing to pull/clone another copy to help test?  

On your device, you should be able to use something like this to power it on/off:

```python
# Set the value directly
d.set_value(20, True)  # On
d.set_value(20, False)  # Off

# Set the value with status
d.set_status(True, switch=20)  # On
d.set_status(False, switch=20)  # Off
```

**Comment by mervinvb** [comment]
I cloned the latest pre-release version and tested it for a bit. Everything runs now without errors! I can fully control power, color and brightness. Very satisfying to finally control my lights with some code :)

If there's anything else you'd like me to test, please let me know. If not, I guess this issue is fixed.

Thank you very much for your help!

**Comment by jasonacox** [comment]
This is great news!   Are you able to use the same code to also manage your "spotlight switch" as well?

I'll run my battery of tests on the change and prepare it for release as PyPI v 1.2.9. 

Thanks for raising the issue.  It may be a small population of devices that needed this, but you never know.  The project will be better thanks to your help.

**Comment by mervinvb** [comment]
The "spotlight switch" device also functions normally with the new code. Debugging this whole thing was actually pretty fun, although I'm glad it's fixed now. Hopefully our efforts will help someone in the future!

**Comment by jasonacox** [comment]
Thank for all your help with this @mervinvb!  I have release v1.2.9 - https://pypi.org/project/tinytuya/ - soon available via `pip install --upgrade tinytuya`.  I'll close this issue but we can re-open if you see other issues.
