### ISSUE TITLE
Network Error: Device Unreachable in windows

### ISSUE THREAD

**Issue by mojtabavi** [jasonacox/tinytuya#72]
I get device unreachable error in windows
what is the problem???

**Comment by jasonacox** [comment]
Make sure nothing else is talking to the Tuya device.  Close SmartLife or Tuya apps.

```python
python -m tinytuya scan
```

In your Tuya code you can activate debugging mode:

```python
import tinytuya

tinytuya.set_debug(True)  # Windows terminal may not translate escape codes so use tinytuya.set_debug(True,False)
```
