### ISSUE TITLE
How to pass the Local Key to the scan?

### ISSUE THREAD

**Issue by leoheck** [jasonacox/tinytuya#73]
Hello, I am trying to find and identify devices on my network.
I am receiving this output. 

Do I have a way to pass the `Local Key` to the scan process?

```
➜ python3 -m tinytuya scan

TinyTuya (Tuya device scanner) [1.2.9]

Scanning on UDP ports 6666 and 6667 for devices (15 retries)...

Unknown v3.3 Device   Product ID = keygg897krt5kk4t  [Valid payload]:
    Address = 192.168.86.41,  Device ID = [ID_HERE], Local Key = ,  Version = 3.3
    No Stats for 192.168.86.41: DEVICE KEY required to poll for status
Unknown v3.3 Device   Product ID = keygg897krt5kk4t  [Valid payload]:
    Address = 192.168.86.242,  Device ID = [ID_HERE], Local Key = ,  Version = 3.3
    No Stats for 192.168.86.242: DEVICE KEY required to poll for status
```

**Comment by jasonacox** [comment]
Hi @leoheck - to get the device information, you will need the local key.  Follow the [setup instructions](https://github.com/jasonacox/tinytuya#setup-wizard) and run:

```bash
python3 -m tinytuya wizard
```

This will create the devices.json file that scan will use for future scans to identify and poll the devices using the local key.

In your exmaple, scan found 2 devices.  If you have more devices, there is a chance that you will need to have TinyTuya wait longer to sense those devices.  There is no active scan, TinyTuya just listens to your network to hear the UDP broadcast packets from the Tuya devices.  You can provide a number after scan to tell TinyTuya how may times to retry/wait. 

```bash
python3 -m tinytuya scan 50
```

**Comment by leoheck** [comment]
Hi. I ran it. Something wierd is happening then. Which file the scan uses?

**Comment by leoheck** [comment]
Ah, one of the devices is always sleeping. This is an issue totally.

**Comment by jasonacox** [comment]
Is it a battery powered Tuya device?  I see that as well. They only wake up periodically to save power.  You can sometimes activate them (power cycle) and get enough of a window for TinyTuya to see the UDP packet.

TinyTuya uses `devices.json` for the devices, but the wizard also creates `tinytuya.json` to save your settings and `tuya-raw.json` as the raw output from the Tuya Cloud.
