### ISSUE TITLE
Timeout or exception in _send_receive()

### ISSUE THREAD

**Issue by tortoisehamster** [jasonacox/tinytuya#84]
The device (dimmer switch) is recognized and d.status() works no problem, but anytime I try to change the state of the device it times out with error 902. Every time I try to do anything it says "received null payload ... fetch new one". I've checked the version and device key and both seem fine so I'm very confused. Any help would be greatly appreciated!

**Comment by jasonacox** [comment]
Hi @tortoisehamster can you turn on debug to see what is happening?

```python
tinytuya.set_debug(True)   # use tinytuya.set_debug(True,False) for non-ANSI color terminal
```

**Comment by tortoisehamster** [comment]
Ended up solving it, thanks!
