### ISSUE TITLE
Scheduling a bulb

### ISSUE THREAD

**Issue by bthxyzx** [jasonacox/tinytuya#88]
How can i schedule a bulb to open everyday at same hour like smart life app?Thanks if you can help.Thank you for this app it helped me a lot.

**Comment by jasonacox** [comment]
Great questions @bthxyzx .  The Tuya devices (bulbs) don't seem to contain a real time clock so the timer function is likely actually performed by the Tuya Cloud.

For me, I have a basic Raspberry Pi that is always on and performs the timer function.  It turns switches and lights on/off or changes colors at certain times.  I'm using simple cron scripts (see `crontab`) which is part of Raspberry Pi OS or Linux systems.   

I recommend also looking at [home-assistant.io](https://www.home-assistant.io/) as it provides an easy to use interface to do all of this without getting into the OS.

**Comment by bthxyzx** [comment]
Thanks jasonacox.Looks like Smart life app scheduling is on the cloud.
