### ISSUE TITLE
Do you have an example with set_colour(r,g,b) ?

### ISSUE THREAD

**Issue by johncohn** [jasonacox/tinytuya#9]
THanks for a very useful package !

I'm able to turn on/off  on my Tuya enabled lights and able to set their brightness, but I'm not able to    get the set_colour(r,g,b) to work properly. set_colour(r,g,b) seems to hang no matter what values I put in for r,g,b. I can't find an example of being used… So perhaps I'm doing it wrong. It looks OK from the source code… Any suggestions?

John Cohn
johncohnvt@gmail.com

thanks again !

here's my code 

```
import tinytuya
import random

candles = {}
candles[0] = tinytuya.BulbDevice('868515018caab5ef1554', '192.168.1.26', '03ca98398a11c78a')
candles[1] = tinytuya.BulbDevice('86851501e09806ac519d', '192.168.1.27', '970cdd010944cf8b')
candles[2] = tinytuya.BulbDevice('868515018caab5e57b07', '192.168.1.28', '5aa724e67b0b4bd9')
candles[3] = tinytuya.BulbDevice('868515018caab5ef1d2b', '192.168.1.29', '129668119d3e840c')
candles[4] = tinytuya.BulbDevice('868515018caab5e48e96', '192.168.1.30', '431b646c91ffca5c')
candles[5] = tinytuya.BulbDevice('868515018caab5ef529e', '192.168.1.31', 'daf67a675bf9287d')
candles[6] = tinytuya.BulbDevice('eb14adb45f8dfeb872fk5x', '192.168.1.25', '2f239ce262516e4b')
candles[7] = tinytuya.BulbDevice('ebe1eb6797591db8eslal', '192.168.1.24', 'eefb1deb6155f9f6')
candles[8] = tinytuya.BulbDevice('eb044207ff02162f1f248g', '192.168.1.4', '44b9d8edcf92ca3e')
for i in range (9):
    candles[i].set_version(3.3)

for i in range (9):
    candles[i].set_value('20',True) # turn on each light                                                                                                                             
    z = random.randint(10, 1000) # choose a random brightness                                                                                                                        
    candles[i].set_value('22',z) # set brighntess (this works)                                                                                                                       
## if uncommented, the next line hangss                                                                                                                                              
#    candles[i].set_colour(100,100,100) # attempt to set a colour .. (this does NOT work.. iit hangs  forever))                                                                      
    data = candles[i].status()  # NOTE this does NOT require a valid key vor version 3.1                                                                                             
    print(data)




```

**Comment by jasonacox** [comment]
Hi John,

Your code logic seem sound.  However, you are sending a lot of controls to these in short order.  Thanks to @elfman03 we have added logic in TinyTuya to better accommodate frequent repeat socket calls to the devices. I recommend you try adding these two settings to your code:
```python
candles[i].set_socketPersistent(True)
candles[i].set_socketNODELAY(False)
```
Also, I notice that some of your devices have 22 character IDs.  Some of these devices require a special treatment, specifically switching them to use the device22 profile, `dev_type='device22` in the initialization. 

A few questions to help troubleshoot:
* What version of TinyTuya are you using (may want to `python3 -m pip install --upgrade tinytuya`)?
* What happens when you try to control just one device - do they behave differently (may indicate the device22 issue)?

**Comment by jasonacox** [comment]
You might need to set the Bulb into "colour" mode - something like this:
```python
for i in range (9):
    candles[i].set_version(3.3)
    candles[i].set_value('21','colour')
```
I just picked up a new RGB Bulb and have been testing and noticed it needed the colour mode set. I've also discovered some improvements I want to make on the code. :)

**Comment by johncohn** [comment]
Jason
    Thanks for that… I’ll try it.… I now realize I can set the colors by doing a set_value On field 24 and use a hex string for the
 rrggbb0hhssvv representation directly .

I do think one of the type 22 bulbs might be defective. It used to work, but When I try to write to it now, My python script hangs up. If I skip that bulb everything else works.

I’ve tried resetting the bulb… But that doesn’t seem to help. The odd thing is I can still control it from the Smart Life app and Alexa… Just not from python.… Not sure if that’s a clue. Is there a way to get control back if one of the commands hangs up?… I’m not sure what’s blocking because I was thinking that it was all on UDP protocol… Is there some sort of acknowledgment that is supposed to come back from the bulb?

-jc

Ps .. I could tell you my favorite UDP joke ... 
.. but you might not get it 

Budabump :-)

**Comment by jasonacox** [comment]
In my investigation, I discovered there are at least two types of Bulbs.  One uses the "rrggbb0hhssvv" format you mention, but the other uses HSV values only with higher (16 bit) ranges "hhhhssssvvvv".   I suspect you have an hsv-only version in which case tinytuya is getting an error back when you send the rgb+hsv payload.  Instead of failing out, it keeps retrying.  You could fix the hanging by turning off retry via `candles[i].set_retry(False)` but it still will not change the color.  

I'm working on some code changes to handle the hsv-only bulbs.

What would be a big help is to get a list of the data points (DPS) from all of your devices and let me know which one(s) are not responding.  Run something like this:
```
python3 -m tinytuya
```
Bonus points if you can set them all too red (255,0,0) before grabbing that so we can see if there is any delta in index 24. 

Thanks John!

PS - love the UDP joke :-)

**Comment by johncohn** [comment]
Jason
 
  Here's the tinytuya scan

(base) Johns-MacBook-Pro-10:~ johncohn@us.ibm.com$ python3 -m tinytuya
TinyTuya (Tuya device scanner) [1.0.5]

Scanning on UDP ports 6666 and 6667 for devices (15 retries)...

FOUND Device [Valid payload]: 192.168.1.24
    ID = ebe91eb6797591db8eslal, product = keytg5kq8gvkv9dh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.25
    ID = eb14adb45f8dfeb872fk5x, product = keytg5kq8gvkv9dh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.28
    ID = 868515018caab5e57b07, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.31
    ID = 868515018caab5ef529e, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.29
    ID = 868515018caab5ef1d2b, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.30
    ID = 868515018caab5e48e96, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.4
    ID = eb044207ff02162f1f248g, product = keytg5kq8gvkv9dh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.26
    ID = 868515018caab5ef1554, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
FOUND Device [Valid payload]: 192.168.1.27
    ID = 86851501e09806ac519d, product = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
 
Scan Complete!  Found 9 devices.


I then wrote this code to try to dump the DPS

import tinytuya
import random

candles = {}
candles[0] = tinytuya.BulbDevice('868515018caab5ef1554', '192.168.1.26', 
'03ca98398a11c78a')
candles[1] = tinytuya.BulbDevice('86851501e09806ac519d', '192.168.1.27', 
'970cdd010944cf8b')
candles[2] = tinytuya.BulbDevice('868515018caab5e57b07', '192.168.1.28', 
'5aa724e67b0b4bd9')
candles[3] = tinytuya.BulbDevice('868515018caab5ef1d2b', '192.168.1.29', 
'129668119d3e840c')
candles[4] = tinytuya.BulbDevice('868515018caab5e48e96', '192.168.1.30', 
'431b646c91ffca5c')
candles[5] = tinytuya.BulbDevice('868515018caab5ef529e', '192.168.1.31', 
'daf67a675bf9287d')
#candles[6] = tinytuya.BulbDevice('eb14adb45f8dfeb872fk5x', 
'192.168.1.25', '2f239ce262516e4b','device22')
#candles[7] = tinytuya.BulbDevice('ebe1eb6797591db8eslal', '192.168.1.24', 
'd609fce2333acd34','device22')
#candles[8] = tinytuya.BulbDevice('eb044207ff02162f1f248g', '192.168.1.4', 
'44b9d8edcf92ca3e','device22')
candles[6] = tinytuya.BulbDevice('eb14adb45f8dfeb872fk5x', '192.168.1.25', 
'2f239ce262516e4b')
candles[7] = tinytuya.BulbDevice('ebe1eb6797591db8eslal', '192.168.1.24', 
'd609fce2333acd34')
candles[8] = tinytuya.BulbDevice('eb044207ff02162f1f248g', '192.168.1.4', 
'44b9d8edcf92ca3e')


for i in range (9):
    candles[i].set_version(3.3)
    candles[i].set_socketPersistent(True)
    candles[i].set_socketNODELAY(False)
    candles[i].set_retry(False)
    try :
        data = candles[i].status()  # NOTE this does NOT require a valid 
key vor version 3.1 
        print('data:' + str(data))
 
    except:
        print("could not retreive candle: " + str(i))
 
 
I then set all bulbs to bright red using alexa.. and verified they all 
changed.. then ran the code
Here's the output. Note if I put the device type 'device22' on the three 
'differnt' bulbs, i cannot dump their DPS


(base) Johns-MacBook-Pro-10:~ johncohn@us.ibm.com$ python3 tuya.py
data:{'devId': '868515018caab5ef1554', 'dps': {'20': True, '21': 'colour', 
'22': 800, '23': 400, '24': '000003e802f8', '25': 
'06464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000', 
'26': 0}}
data:{'devId': '86851501e09806ac519d', 'dps': {'20': True, '21': 'colour', 
'22': 580, '23': 400, '24': '000003e802f8', '25': 
'000e0d0000000000000000c80000', '26': 0}}
data:{'devId': '868515018caab5e57b07', 'dps': {'20': True, '21': 'colour', 
'22': 780, '23': 400, '24': '000003e802f8', '25': 
'000e0d0000000000000000c80000', '26': 0}}
data:{'devId': '868515018caab5ef1d2b', 'dps': {'20': True, '21': 'colour', 
'22': 470, '23': 400, '24': '000003e802f8', '25': 
'000e0d0000000000000000c80000', '26': 0}}
data:{'devId': '868515018caab5e48e96', 'dps': {'20': True, '21': 'colour', 
'22': 760, '23': 400, '24': '000003e802f8', '25': 
'000e0d0000000000000000c80000', '26': 0}}
data:{'devId': '868515018caab5ef529e', 'dps': {'20': True, '21': 'colour', 
'22': 750, '23': 400, '24': '000003e802f8', '25': 
'000e0d0000000000000000c80000', '26': 0}}
data:{'dps': {'20': True, '21': 'colour', '22': 800, '23': 400, '24': 
'000003e802f8', '25': '000e0d0000000000000000c80000', '26': 0}}
data:{'dps': {'20': True, '21': 'colour', '22': 1000, '23': 0, '24': 
'000003e803e8', '25': '000e0d0000000000000000c80000', '26': 0}}
data:{'dps': {'20': True, '21': 'colour', '22': 700, '23': 400, '24': 
'000003e802f8', '25': 
'04464602007803e803e800000000464602007803e8000a00000000', '26': 0}}


hope this helps !


John Cohn Ph.D, 
IBM Fellow , MIT-IBM Watson AI Lab
phone 802-578-0985

**Comment by jasonacox** [comment]
Thanks, John!  That helps confirm the hsv-only colour - at least that is how it represents it. Can you try the 3 different ones without the device22?  Do they not respond to the status() call?  I have one with a 22 character ID but it is working without the device22 mode but required I send a different.

```python
candles[6] = tinytuya.BulbDevice('eb14adb45f8dfeb872fk5x',
'192.168.1.25', '2f239ce262516e4b')
candles[7] = tinytuya.BulbDevice('ebe1eb6797591db8eslal', '192.168.1.24',
'd609fce2333acd34')
candles[8] = tinytuya.BulbDevice('eb044207ff02162f1f248g', '192.168.1.4',
'44b9d8edcf92ca3e')

for i in candles:
    i.set_version(3.3)
    i.set_socketPersistent(True)
    i.set_socketNODELAY(False)
    i.set_retry(False)
    data = i.status() 
    print('data:' + str(data))
```

By the way, I am testing code to handle the different Bulb types.  The new conversion is showing that the 2 colours found in your output are both Red:
```python
>>> d._hexvalue_to_rgb('000003e803e8','B')
(255, 0, 0)
>>> d._hexvalue_to_rgb('000003e802f8','B')
(193, 0, 0)
```

**Comment by jasonacox** [comment]
Hi @johncohn - I upgraded the BulbDevice class. Try the new version when you can:
```
pip install --upgrade tinytuya
```
Also, check out the example script I built for my own bulbs.  Let me know if this works better for your devices: https://github.com/jasonacox/tinytuya/blob/master/examples/bulb.py

Thanks!

**Comment by johncohn** [comment]
Jason,
  Just tried the new code on one of my type 22 bulbs and it works 
perfectly !  Thank you so much  !
-jc

Here's the listing: 

(base) Johns-MacBook-Pro-10:~ johncohn@us.ibm.com$ python bulb.py
TinyTuya - Smart Bulb RGB Test [1.1.1]

TESTING: Device eb044207ff02162f1f248g at 192.168.1.4 with key 
44b9d8edcf92ca3e version 3.3

Current Status of Bulb: {'dps': {'20': True, '21': 'white', '22': 1000, 
'23': 0, '24': '006c02740283', '25': 
'04464602000000000000000a0000464602000000000000000a0144464602000000000000000a000046460200f703e8012200000000', 
'26': 0}}

Warm White Test

Power Control Test
    Turn off lamp
    Turn on lamp

Dimmer Control Test
    Level: 0%
    Level: 10%
    Level: 20%
    Level: 30%
    Level: 40%
    Level: 50%
    Level: 60%
    Level: 70%
    Level: 80%
    Level: 90%
    Level: 100%

Colortemp Control Test (Warm to Cool)
    Level: 0%
    Level: 10%
    Level: 20%
    Level: 30%
    Level: 40%
    Level: 50%
    Level: 60%
    Level: 70%
    Level: 80%
    Level: 90%
    Level: 100%

Color Test - Cycle through rainbow
    red (255,0,0)
    orange (255,127,0)
    yellow (255,200,0)
    green (0,255,0)
    blue (0,0,255)
    indigo (46,43,95)
    violet (139,0,255)

    red (255,0,0)
    orange (255,127,0)
    yellow (255,200,0)
    green (0,255,0)
    blue (0,0,255)
    indigo (46,43,95)
    violet (139,0,255)


Random Color Test
    RGB (99,123,235)
    RGB (237,243,129)
    RGB (21,53,139)
    RGB (95,153,105)
    RGB (250,195,165)
    RGB (59,195,248)
    RGB (126,107,181)
    RGB (68,45,216)
    RGB (68,46,128)
    RGB (228,124,76)

Testing Bulb Modes
    White
    Colour
    Scene
    Music

Done

John Cohn Ph.D, 
IBM Fellow , MIT-IBM Watson AI Lab
phone 802-578-0985

**Comment by jasonacox** [comment]
I'm closing out this issue.  Thanks for your help troubleshooting and improving the BulbDevice code.

**Comment by johncohn** [comment]
Thanks Jason. All is working well now !
