### ISSUE TITLE
Network Error: Device Unreachable', 'Err': '905' on ubuntu

### ISSUE THREAD

**Issue by Electrik-rich546456** [jasonacox/tinytuya#92]
@jasonacox Hi Hows it going ?
I have a new device its a wifi plug but it says:
 `DEBUG:TinyTuya [1.2.11]

DEBUG:status() entry (dev_type is default)

DEBUG:ERROR Network Error: Device Unreachable - 905 - payload: null

DEBUG:status() received data={'Error': 'Network Error: Device Unreachable', 'Err': '905', 'Payload': None}

{'Error': 'Network Error: Device Unreachable', 'Err': '905', 'Payload': None}

`
Even though the scan command found it and there is an entry for it in the tuya-raw.json file. 
However the dps data has not gone to the snapshot file if that's any help.

Ps smart life works turning it on and off, I can also see it in iot toya dev site

**Comment by Electrik-rich546456** [comment]
Oh hey my bad I think i fixed it with a power cycle as i couldn't ping it with local ip address but i could with external one

**Comment by jasonacox** [comment]
I'll close this for now but feel free to re-open if there is an issue to raise.
