### ISSUE TITLE
clarify setup instructions

### ISSUE THREAD

**Issue by vuvova** [jasonacox/tinytuya#93]
> Under "Service API" ensure this API is listed: `IoT Core` -

that's not enough. Should be (as https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md says) **at least** `IoT Core` and `Authorization`. I also added `Smart Home Scene Linkage` but `IoT Data Analytics` no longer exists.

And, very important, **disable popup blockers** — otherwise subscribing doesn't work without any indication of what is wrong (normally a popup blocker indicates that it blocked a popup. Not in this case though)

**Comment by jasonacox** [comment]
Thanks @vuvova - GREAT tips!  Thanks for opening the issue.  I'll update to add the note.  I wish Tuya would stop changing their UI, or better yet, give us an easier way to get our local keys. :)

**Comment by jasonacox** [comment]
Closing Issue - thanks for the help!
