### ISSUE TITLE
Code 1106 permission deny, cannot access any device

### ISSUE THREAD

**Issue by cy1110** [jasonacox/tinytuya#96]
I've probably spent more than 4 hours trying to get this script set up, and haven't got anywhere. I've first done the following: 

1. Followed the steps on readme.md and installed 1.3.1
2. Paired the device with Smart Life app, devices can be successfully controlled with the app.
3. Scanned and detected the local device (a smart plug). The device showed a Product ID and Device ID but no Local Key, and the firmware version was 3.3. 
4. Set up Tuya IoT account + cloud project and configured it following the instructions of step 3 on readme.md. Confirmed that the datacenter region was "Eastern America Data Center", app account QR was scanned with Smart Life, Service APIs are subscribed and authorized. Also recorded the Client ID and API Secret values, which are displayed under the labels "Access ID/Client ID" and "Access Secret/Client Secret" respectively.
5. Ran the wizard and filled in the client ID, API secret, Device ID of the earlier scanned device, and region (us-e), which resulted in the error "permission deny". 

I've then done the following steps to debug, following a number of different guides online: 

1. Attempted to pair with the npm project tuyapi, which gave the same error
2. Created a new account with a different email, unlinked all devices, and repeated the entire pairing process
3. Created a new user in the Users tab of the project page
4. Ensured that the passwords were 10 character alphanumeric
5. Tested various commands with the Tuya API Explorer web tool with the Device ID above, which give the same error 
```
"code": 1106,
"msg": "permission deny",
```

So far nothing I have tried seems to have worked. Any ideas what I am doing wrong and what can be done to solve this issue or debug it further?

**Comment by jasonacox** [comment]
Thanks for opening the issue @cy1110 .  This is the most frustrating part.  Tuya keeps changing their process so automating it is difficult.  The error number doesn't give us much more detail (see [here](https://developer.tuya.com/en/docs/iot/error-code?id=K989ruxx88swc)).

Some ideas:

1) Tuya is aggressive about regions.  If you call from an IP that looks like it is outside of the region they expect, it will be denied.   I would try "Western American Datacenter" in the Tuya cloud portal to your project and try using "us" in the Wizard.

2) Tuya IoT Service permission selection can be glitchy.  Try navigating to https://iot.tuya.com/ then "Cloud" -> "My Services" and make sure "IoT Core"  "Authorization" and "Smart Home Scene Linkage" show "subscribed" like this:
![image](https://user-images.githubusercontent.com/836718/148671037-db96a4a9-af96-4130-89da-f4f7badebfc1.png)
Also make sure they are authorized:  Go to https://iot.tuya.com/ then "Cloud" -> select your project ->  "Service API" tab  and make sure "IoT Core"  "Authorization" and "Smart Home Scene Linkage" show "authorized" like this:
![image](https://user-images.githubusercontent.com/836718/148671256-96c116ef-a0cf-4673-918f-c533aa237ddd.png)


3) There is an "Allow List" option that can be turned on in the project.  Try navigation to https://iot.tuya.com/ then "Cloud" ->  Click on your project and ensure "allow list" is not turned on:
![image](https://user-images.githubusercontent.com/836718/148671131-b6779e9b-7f6c-42aa-9473-0547e6b8ef5e.png)

**Comment by cy1110** [comment]
>     1. Tuya is aggressive about regions.  If you call from an IP that looks like it is outside of the region they expect, it will be denied.   I would try "Western American Datacenter" in the Tuya cloud portal to your project and try using "us" in the Wizard.

OMG yes thank you so much, this one did the trick. The difference immediately showed, when creating a new project with the other datacenter as server, the devices showed up in the Cloud->Development->Devices->All Devices folder. Previously they never showed up in there. 

I've PRed a screenshot and some instructions https://github.com/jasonacox/tinytuya/pull/97

**Comment by jasonacox** [comment]
Thank you, @cy1110 !   I merged your PR.
